// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentRepository creates a new instance of MockPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepository {
	mock := &MockPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentRepository is an autogenerated mock type for the PaymentRepository type
type MockPaymentRepository struct {
	mock.Mock
}

type MockPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRepository) EXPECT() *MockPaymentRepository_Expecter {
	return &MockPaymentRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) Find(ctx context.Context, paymentID string) (*Payment, error) {
	ret := _mock.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *Payment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Payment, error)); ok {
		return returnFunc(ctx, paymentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Payment); ok {
		r0 = returnFunc(ctx, paymentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Payment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, paymentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPaymentRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockPaymentRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID string
func (_e *MockPaymentRepository_Expecter) Find(ctx interface{}, paymentID interface{}) *MockPaymentRepository_Find_Call {
	return &MockPaymentRepository_Find_Call{Call: _e.mock.On("Find", ctx, paymentID)}
}

func (_c *MockPaymentRepository_Find_Call) Run(run func(ctx context.Context, paymentID string)) *MockPaymentRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_Find_Call) Return(payment *Payment, err error) *MockPaymentRepository_Find_Call {
	_c.Call.Return(payment, err)
	return _c
}

func (_c *MockPaymentRepository_Find_Call) RunAndReturn(run func(ctx context.Context, paymentID string) (*Payment, error)) *MockPaymentRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) Save(ctx context.Context, payment *Payment) error {
	ret := _mock.Called(ctx, payment)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Payment) error); ok {
		r0 = returnFunc(ctx, payment)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPaymentRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockPaymentRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - payment *Payment
func (_e *MockPaymentRepository_Expecter) Save(ctx interface{}, payment interface{}) *MockPaymentRepository_Save_Call {
	return &MockPaymentRepository_Save_Call{Call: _e.mock.On("Save", ctx, payment)}
}

func (_c *MockPaymentRepository_Save_Call) Run(run func(ctx context.Context, payment *Payment)) *MockPaymentRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Payment
		if args[1] != nil {
			arg1 = args[1].(*Payment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_Save_Call) Return(err error) *MockPaymentRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPaymentRepository_Save_Call) RunAndReturn(run func(ctx context.Context, payment *Payment) error) *MockPaymentRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
