// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCustomerRepository creates a new instance of MockCustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerRepository {
	mock := &MockCustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCustomerRepository is an autogenerated mock type for the CustomerRepository type
type MockCustomerRepository struct {
	mock.Mock
}

type MockCustomerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerRepository) EXPECT() *MockCustomerRepository_Expecter {
	return &MockCustomerRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockCustomerRepository
func (_mock *MockCustomerRepository) Find(ctx context.Context, customerID string) (*Customer, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Customer, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Customer); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockCustomerRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
func (_e *MockCustomerRepository_Expecter) Find(ctx interface{}, customerID interface{}) *MockCustomerRepository_Find_Call {
	return &MockCustomerRepository_Find_Call{Call: _e.mock.On("Find", ctx, customerID)}
}

func (_c *MockCustomerRepository_Find_Call) Run(run func(ctx context.Context, customerID string)) *MockCustomerRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerRepository_Find_Call) Return(customer *Customer, err error) *MockCustomerRepository_Find_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockCustomerRepository_Find_Call) RunAndReturn(run func(ctx context.Context, customerID string) (*Customer, error)) *MockCustomerRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}
