// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCustomerCacheRepository creates a new instance of MockCustomerCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerCacheRepository {
	mock := &MockCustomerCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCustomerCacheRepository is an autogenerated mock type for the CustomerCacheRepository type
type MockCustomerCacheRepository struct {
	mock.Mock
}

type MockCustomerCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerCacheRepository) EXPECT() *MockCustomerCacheRepository_Expecter {
	return &MockCustomerCacheRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockCustomerCacheRepository
func (_mock *MockCustomerCacheRepository) Add(ctx context.Context, customerID string, name string) error {
	ret := _mock.Called(ctx, customerID, name)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, customerID, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCustomerCacheRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockCustomerCacheRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
//   - name string
func (_e *MockCustomerCacheRepository_Expecter) Add(ctx interface{}, customerID interface{}, name interface{}) *MockCustomerCacheRepository_Add_Call {
	return &MockCustomerCacheRepository_Add_Call{Call: _e.mock.On("Add", ctx, customerID, name)}
}

func (_c *MockCustomerCacheRepository_Add_Call) Run(run func(ctx context.Context, customerID string, name string)) *MockCustomerCacheRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCustomerCacheRepository_Add_Call) Return(err error) *MockCustomerCacheRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCustomerCacheRepository_Add_Call) RunAndReturn(run func(ctx context.Context, customerID string, name string) error) *MockCustomerCacheRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockCustomerCacheRepository
func (_mock *MockCustomerCacheRepository) Find(ctx context.Context, customerID string) (*Customer, error) {
	ret := _mock.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *Customer
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Customer, error)); ok {
		return returnFunc(ctx, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Customer); ok {
		r0 = returnFunc(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Customer)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCustomerCacheRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockCustomerCacheRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
func (_e *MockCustomerCacheRepository_Expecter) Find(ctx interface{}, customerID interface{}) *MockCustomerCacheRepository_Find_Call {
	return &MockCustomerCacheRepository_Find_Call{Call: _e.mock.On("Find", ctx, customerID)}
}

func (_c *MockCustomerCacheRepository_Find_Call) Run(run func(ctx context.Context, customerID string)) *MockCustomerCacheRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCustomerCacheRepository_Find_Call) Return(customer *Customer, err error) *MockCustomerCacheRepository_Find_Call {
	_c.Call.Return(customer, err)
	return _c
}

func (_c *MockCustomerCacheRepository_Find_Call) RunAndReturn(run func(ctx context.Context, customerID string) (*Customer, error)) *MockCustomerCacheRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}
