// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Add(ctx context.Context, order *Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockOrderRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - order *Order
func (_e *MockOrderRepository_Expecter) Add(ctx interface{}, order interface{}) *MockOrderRepository_Add_Call {
	return &MockOrderRepository_Add_Call{Call: _e.mock.On("Add", ctx, order)}
}

func (_c *MockOrderRepository_Add_Call) Run(run func(ctx context.Context, order *Order)) *MockOrderRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Order
		if args[1] != nil {
			arg1 = args[1].(*Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Add_Call) Return(err error) *MockOrderRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_Add_Call) RunAndReturn(run func(ctx context.Context, order *Order) error) *MockOrderRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Get(ctx context.Context, orderID string) (*Order, error) {
	ret := _mock.Called(ctx, orderID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Order, error)); ok {
		return returnFunc(ctx, orderID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Order); ok {
		r0 = returnFunc(ctx, orderID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, orderID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockOrderRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
func (_e *MockOrderRepository_Expecter) Get(ctx interface{}, orderID interface{}) *MockOrderRepository_Get_Call {
	return &MockOrderRepository_Get_Call{Call: _e.mock.On("Get", ctx, orderID)}
}

func (_c *MockOrderRepository_Get_Call) Run(run func(ctx context.Context, orderID string)) *MockOrderRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Get_Call) Return(order *Order, err error) *MockOrderRepository_Get_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_Get_Call) RunAndReturn(run func(ctx context.Context, orderID string) (*Order, error)) *MockOrderRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Search(ctx context.Context, filters *SearchFilters) ([]*Order, error) {
	ret := _mock.Called(ctx, filters)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SearchFilters) ([]*Order, error)); ok {
		return returnFunc(ctx, filters)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SearchFilters) []*Order); ok {
		r0 = returnFunc(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *SearchFilters) error); ok {
		r1 = returnFunc(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockOrderRepository_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - filters *SearchFilters
func (_e *MockOrderRepository_Expecter) Search(ctx interface{}, filters interface{}) *MockOrderRepository_Search_Call {
	return &MockOrderRepository_Search_Call{Call: _e.mock.On("Search", ctx, filters)}
}

func (_c *MockOrderRepository_Search_Call) Run(run func(ctx context.Context, filters *SearchFilters)) *MockOrderRepository_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *SearchFilters
		if args[1] != nil {
			arg1 = args[1].(*SearchFilters)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Search_Call) Return(orders []*Order, err error) *MockOrderRepository_Search_Call {
	_c.Call.Return(orders, err)
	return _c
}

func (_c *MockOrderRepository_Search_Call) RunAndReturn(run func(ctx context.Context, filters *SearchFilters) ([]*Order, error)) *MockOrderRepository_Search_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Update(ctx context.Context, orderID string, updater func(*Order) error) error {
	ret := _mock.Called(ctx, orderID, updater)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, func(*Order) error) error); ok {
		r0 = returnFunc(ctx, orderID, updater)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOrderRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - updater func(*Order) error
func (_e *MockOrderRepository_Expecter) Update(ctx interface{}, orderID interface{}, updater interface{}) *MockOrderRepository_Update_Call {
	return &MockOrderRepository_Update_Call{Call: _e.mock.On("Update", ctx, orderID, updater)}
}

func (_c *MockOrderRepository_Update_Call) Run(run func(ctx context.Context, orderID string, updater func(*Order) error)) *MockOrderRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 func(*Order) error
		if args[2] != nil {
			arg2 = args[2].(func(*Order) error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Update_Call) Return(err error) *MockOrderRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_Update_Call) RunAndReturn(run func(ctx context.Context, orderID string, updater func(*Order) error) error) *MockOrderRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
