// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStoreRepository creates a new instance of MockStoreRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoreRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoreRepository {
	mock := &MockStoreRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStoreRepository is an autogenerated mock type for the StoreRepository type
type MockStoreRepository struct {
	mock.Mock
}

type MockStoreRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoreRepository) EXPECT() *MockStoreRepository_Expecter {
	return &MockStoreRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockStoreRepository
func (_mock *MockStoreRepository) Find(ctx context.Context, storeID string) (*Store, error) {
	ret := _mock.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *Store
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Store, error)); ok {
		return returnFunc(ctx, storeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Store); ok {
		r0 = returnFunc(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Store)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoreRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockStoreRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - storeID string
func (_e *MockStoreRepository_Expecter) Find(ctx interface{}, storeID interface{}) *MockStoreRepository_Find_Call {
	return &MockStoreRepository_Find_Call{Call: _e.mock.On("Find", ctx, storeID)}
}

func (_c *MockStoreRepository_Find_Call) Run(run func(ctx context.Context, storeID string)) *MockStoreRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoreRepository_Find_Call) Return(store *Store, err error) *MockStoreRepository_Find_Call {
	_c.Call.Return(store, err)
	return _c
}

func (_c *MockStoreRepository_Find_Call) RunAndReturn(run func(ctx context.Context, storeID string) (*Store, error)) *MockStoreRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}
