// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tm

import (
	"context"
	"eda-in-golang/internal/am"

	mock "github.com/stretchr/testify/mock"
)

// NewMockInboxStore creates a new instance of MockInboxStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInboxStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInboxStore {
	mock := &MockInboxStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInboxStore is an autogenerated mock type for the InboxStore type
type MockInboxStore struct {
	mock.Mock
}

type MockInboxStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInboxStore) EXPECT() *MockInboxStore_Expecter {
	return &MockInboxStore_Expecter{mock: &_m.Mock}
}

// Save provides a mock function for the type MockInboxStore
func (_mock *MockInboxStore) Save(ctx context.Context, msg am.RawMessage) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, am.RawMessage) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInboxStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockInboxStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - msg am.RawMessage
func (_e *MockInboxStore_Expecter) Save(ctx interface{}, msg interface{}) *MockInboxStore_Save_Call {
	return &MockInboxStore_Save_Call{Call: _e.mock.On("Save", ctx, msg)}
}

func (_c *MockInboxStore_Save_Call) Run(run func(ctx context.Context, msg am.RawMessage)) *MockInboxStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 am.RawMessage
		if args[1] != nil {
			arg1 = args[1].(am.RawMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockInboxStore_Save_Call) Return(err error) *MockInboxStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInboxStore_Save_Call) RunAndReturn(run func(ctx context.Context, msg am.RawMessage) error) *MockInboxStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
