// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package tm

import (
	"context"
	"eda-in-golang/internal/am"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOutboxStore creates a new instance of MockOutboxStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutboxStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutboxStore {
	mock := &MockOutboxStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOutboxStore is an autogenerated mock type for the OutboxStore type
type MockOutboxStore struct {
	mock.Mock
}

type MockOutboxStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutboxStore) EXPECT() *MockOutboxStore_Expecter {
	return &MockOutboxStore_Expecter{mock: &_m.Mock}
}

// FindUnpublished provides a mock function for the type MockOutboxStore
func (_mock *MockOutboxStore) FindUnpublished(ctx context.Context, limit int) ([]am.RawMessage, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for FindUnpublished")
	}

	var r0 []am.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]am.RawMessage, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []am.RawMessage); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]am.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOutboxStore_FindUnpublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindUnpublished'
type MockOutboxStore_FindUnpublished_Call struct {
	*mock.Call
}

// FindUnpublished is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockOutboxStore_Expecter) FindUnpublished(ctx interface{}, limit interface{}) *MockOutboxStore_FindUnpublished_Call {
	return &MockOutboxStore_FindUnpublished_Call{Call: _e.mock.On("FindUnpublished", ctx, limit)}
}

func (_c *MockOutboxStore_FindUnpublished_Call) Run(run func(ctx context.Context, limit int)) *MockOutboxStore_FindUnpublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutboxStore_FindUnpublished_Call) Return(rawMessages []am.RawMessage, err error) *MockOutboxStore_FindUnpublished_Call {
	_c.Call.Return(rawMessages, err)
	return _c
}

func (_c *MockOutboxStore_FindUnpublished_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]am.RawMessage, error)) *MockOutboxStore_FindUnpublished_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAsPublished provides a mock function for the type MockOutboxStore
func (_mock *MockOutboxStore) MarkAsPublished(ctx context.Context, ids ...string) error {
	var tmpRet mock.Arguments
	if len(ids) > 0 {
		tmpRet = _mock.Called(ctx, ids)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MarkAsPublished")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...string) error); ok {
		r0 = returnFunc(ctx, ids...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOutboxStore_MarkAsPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAsPublished'
type MockOutboxStore_MarkAsPublished_Call struct {
	*mock.Call
}

// MarkAsPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - ids ...string
func (_e *MockOutboxStore_Expecter) MarkAsPublished(ctx interface{}, ids ...interface{}) *MockOutboxStore_MarkAsPublished_Call {
	return &MockOutboxStore_MarkAsPublished_Call{Call: _e.mock.On("MarkAsPublished",
		append([]interface{}{ctx}, ids...)...)}
}

func (_c *MockOutboxStore_MarkAsPublished_Call) Run(run func(ctx context.Context, ids ...string)) *MockOutboxStore_MarkAsPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		var variadicArgs []string
		if len(args) > 1 {
			variadicArgs = args[1].([]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockOutboxStore_MarkAsPublished_Call) Return(err error) *MockOutboxStore_MarkAsPublished_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOutboxStore_MarkAsPublished_Call) RunAndReturn(run func(ctx context.Context, ids ...string) error) *MockOutboxStore_MarkAsPublished_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockOutboxStore
func (_mock *MockOutboxStore) Save(ctx context.Context, msg am.RawMessage) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, am.RawMessage) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOutboxStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockOutboxStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - msg am.RawMessage
func (_e *MockOutboxStore_Expecter) Save(ctx interface{}, msg interface{}) *MockOutboxStore_Save_Call {
	return &MockOutboxStore_Save_Call{Call: _e.mock.On("Save", ctx, msg)}
}

func (_c *MockOutboxStore_Save_Call) Run(run func(ctx context.Context, msg am.RawMessage)) *MockOutboxStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 am.RawMessage
		if args[1] != nil {
			arg1 = args[1].(am.RawMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutboxStore_Save_Call) Return(err error) *MockOutboxStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOutboxStore_Save_Call) RunAndReturn(run func(ctx context.Context, msg am.RawMessage) error) *MockOutboxStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
