// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package di

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockContainer creates a new instance of MockContainer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContainer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContainer {
	mock := &MockContainer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContainer is an autogenerated mock type for the Container type
type MockContainer struct {
	mock.Mock
}

type MockContainer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContainer) EXPECT() *MockContainer_Expecter {
	return &MockContainer_Expecter{mock: &_m.Mock}
}

// AddScoped provides a mock function for the type MockContainer
func (_mock *MockContainer) AddScoped(key string, fn DepFactoryFunc) {
	_mock.Called(key, fn)
	return
}

// MockContainer_AddScoped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddScoped'
type MockContainer_AddScoped_Call struct {
	*mock.Call
}

// AddScoped is a helper method to define mock.On call
//   - key string
//   - fn DepFactoryFunc
func (_e *MockContainer_Expecter) AddScoped(key interface{}, fn interface{}) *MockContainer_AddScoped_Call {
	return &MockContainer_AddScoped_Call{Call: _e.mock.On("AddScoped", key, fn)}
}

func (_c *MockContainer_AddScoped_Call) Run(run func(key string, fn DepFactoryFunc)) *MockContainer_AddScoped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 DepFactoryFunc
		if args[1] != nil {
			arg1 = args[1].(DepFactoryFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainer_AddScoped_Call) Return() *MockContainer_AddScoped_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContainer_AddScoped_Call) RunAndReturn(run func(key string, fn DepFactoryFunc)) *MockContainer_AddScoped_Call {
	_c.Run(run)
	return _c
}

// AddSingleton provides a mock function for the type MockContainer
func (_mock *MockContainer) AddSingleton(key string, fn DepFactoryFunc) {
	_mock.Called(key, fn)
	return
}

// MockContainer_AddSingleton_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddSingleton'
type MockContainer_AddSingleton_Call struct {
	*mock.Call
}

// AddSingleton is a helper method to define mock.On call
//   - key string
//   - fn DepFactoryFunc
func (_e *MockContainer_Expecter) AddSingleton(key interface{}, fn interface{}) *MockContainer_AddSingleton_Call {
	return &MockContainer_AddSingleton_Call{Call: _e.mock.On("AddSingleton", key, fn)}
}

func (_c *MockContainer_AddSingleton_Call) Run(run func(key string, fn DepFactoryFunc)) *MockContainer_AddSingleton_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 DepFactoryFunc
		if args[1] != nil {
			arg1 = args[1].(DepFactoryFunc)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockContainer_AddSingleton_Call) Return() *MockContainer_AddSingleton_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockContainer_AddSingleton_Call) RunAndReturn(run func(key string, fn DepFactoryFunc)) *MockContainer_AddSingleton_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockContainer
func (_mock *MockContainer) Get(key string) any {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 any
	if returnFunc, ok := ret.Get(0).(func(string) any); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	return r0
}

// MockContainer_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockContainer_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - key string
func (_e *MockContainer_Expecter) Get(key interface{}) *MockContainer_Get_Call {
	return &MockContainer_Get_Call{Call: _e.mock.On("Get", key)}
}

func (_c *MockContainer_Get_Call) Run(run func(key string)) *MockContainer_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainer_Get_Call) Return(v any) *MockContainer_Get_Call {
	_c.Call.Return(v)
	return _c
}

func (_c *MockContainer_Get_Call) RunAndReturn(run func(key string) any) *MockContainer_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Scoped provides a mock function for the type MockContainer
func (_mock *MockContainer) Scoped(ctx context.Context) context.Context {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Scoped")
	}

	var r0 context.Context
	if returnFunc, ok := ret.Get(0).(func(context.Context) context.Context); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}
	return r0
}

// MockContainer_Scoped_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scoped'
type MockContainer_Scoped_Call struct {
	*mock.Call
}

// Scoped is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockContainer_Expecter) Scoped(ctx interface{}) *MockContainer_Scoped_Call {
	return &MockContainer_Scoped_Call{Call: _e.mock.On("Scoped", ctx)}
}

func (_c *MockContainer_Scoped_Call) Run(run func(ctx context.Context)) *MockContainer_Scoped_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContainer_Scoped_Call) Return(context1 context.Context) *MockContainer_Scoped_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockContainer_Scoped_Call) RunAndReturn(run func(ctx context.Context) context.Context) *MockContainer_Scoped_Call {
	_c.Call.Return(run)
	return _c
}
