// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	"context"
	"eda-in-golang/internal/ddd"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandPublisher creates a new instance of MockCommandPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandPublisher {
	mock := &MockCommandPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandPublisher is an autogenerated mock type for the CommandPublisher type
type MockCommandPublisher struct {
	mock.Mock
}

type MockCommandPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandPublisher) EXPECT() *MockCommandPublisher_Expecter {
	return &MockCommandPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockCommandPublisher
func (_mock *MockCommandPublisher) Publish(ctx context.Context, topicName string, v ddd.Command) error {
	ret := _mock.Called(ctx, topicName, v)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ddd.Command) error); ok {
		r0 = returnFunc(ctx, topicName, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommandPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockCommandPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - topicName string
//   - v ddd.Command
func (_e *MockCommandPublisher_Expecter) Publish(ctx interface{}, topicName interface{}, v interface{}) *MockCommandPublisher_Publish_Call {
	return &MockCommandPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, topicName, v)}
}

func (_c *MockCommandPublisher_Publish_Call) Run(run func(ctx context.Context, topicName string, v ddd.Command)) *MockCommandPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ddd.Command
		if args[2] != nil {
			arg2 = args[2].(ddd.Command)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCommandPublisher_Publish_Call) Return(err error) *MockCommandPublisher_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommandPublisher_Publish_Call) RunAndReturn(run func(ctx context.Context, topicName string, v ddd.Command) error) *MockCommandPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}
