// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	"eda-in-golang/internal/ddd"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandMessage creates a new instance of MockCommandMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandMessage {
	mock := &MockCommandMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandMessage is an autogenerated mock type for the CommandMessage type
type MockCommandMessage struct {
	mock.Mock
}

type MockCommandMessage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandMessage) EXPECT() *MockCommandMessage_Expecter {
	return &MockCommandMessage_Expecter{mock: &_m.Mock}
}

// CommandName provides a mock function for the type MockCommandMessage
func (_mock *MockCommandMessage) CommandName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CommandName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCommandMessage_CommandName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommandName'
type MockCommandMessage_CommandName_Call struct {
	*mock.Call
}

// CommandName is a helper method to define mock.On call
func (_e *MockCommandMessage_Expecter) CommandName() *MockCommandMessage_CommandName_Call {
	return &MockCommandMessage_CommandName_Call{Call: _e.mock.On("CommandName")}
}

func (_c *MockCommandMessage_CommandName_Call) Run(run func()) *MockCommandMessage_CommandName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommandMessage_CommandName_Call) Return(s string) *MockCommandMessage_CommandName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCommandMessage_CommandName_Call) RunAndReturn(run func() string) *MockCommandMessage_CommandName_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockCommandMessage
func (_mock *MockCommandMessage) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCommandMessage_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockCommandMessage_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockCommandMessage_Expecter) ID() *MockCommandMessage_ID_Call {
	return &MockCommandMessage_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockCommandMessage_ID_Call) Run(run func()) *MockCommandMessage_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommandMessage_ID_Call) Return(s string) *MockCommandMessage_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCommandMessage_ID_Call) RunAndReturn(run func() string) *MockCommandMessage_ID_Call {
	_c.Call.Return(run)
	return _c
}

// MessageName provides a mock function for the type MockCommandMessage
func (_mock *MockCommandMessage) MessageName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MessageName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCommandMessage_MessageName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MessageName'
type MockCommandMessage_MessageName_Call struct {
	*mock.Call
}

// MessageName is a helper method to define mock.On call
func (_e *MockCommandMessage_Expecter) MessageName() *MockCommandMessage_MessageName_Call {
	return &MockCommandMessage_MessageName_Call{Call: _e.mock.On("MessageName")}
}

func (_c *MockCommandMessage_MessageName_Call) Run(run func()) *MockCommandMessage_MessageName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommandMessage_MessageName_Call) Return(s string) *MockCommandMessage_MessageName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCommandMessage_MessageName_Call) RunAndReturn(run func() string) *MockCommandMessage_MessageName_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function for the type MockCommandMessage
func (_mock *MockCommandMessage) Metadata() ddd.Metadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 ddd.Metadata
	if returnFunc, ok := ret.Get(0).(func() ddd.Metadata); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ddd.Metadata)
		}
	}
	return r0
}

// MockCommandMessage_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockCommandMessage_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockCommandMessage_Expecter) Metadata() *MockCommandMessage_Metadata_Call {
	return &MockCommandMessage_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockCommandMessage_Metadata_Call) Run(run func()) *MockCommandMessage_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommandMessage_Metadata_Call) Return(metadata ddd.Metadata) *MockCommandMessage_Metadata_Call {
	_c.Call.Return(metadata)
	return _c
}

func (_c *MockCommandMessage_Metadata_Call) RunAndReturn(run func() ddd.Metadata) *MockCommandMessage_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// OccurredAt provides a mock function for the type MockCommandMessage
func (_mock *MockCommandMessage) OccurredAt() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OccurredAt")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockCommandMessage_OccurredAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OccurredAt'
type MockCommandMessage_OccurredAt_Call struct {
	*mock.Call
}

// OccurredAt is a helper method to define mock.On call
func (_e *MockCommandMessage_Expecter) OccurredAt() *MockCommandMessage_OccurredAt_Call {
	return &MockCommandMessage_OccurredAt_Call{Call: _e.mock.On("OccurredAt")}
}

func (_c *MockCommandMessage_OccurredAt_Call) Run(run func()) *MockCommandMessage_OccurredAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommandMessage_OccurredAt_Call) Return(time1 time.Time) *MockCommandMessage_OccurredAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockCommandMessage_OccurredAt_Call) RunAndReturn(run func() time.Time) *MockCommandMessage_OccurredAt_Call {
	_c.Call.Return(run)
	return _c
}

// Payload provides a mock function for the type MockCommandMessage
func (_mock *MockCommandMessage) Payload() ddd.CommandPayload {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Payload")
	}

	var r0 ddd.CommandPayload
	if returnFunc, ok := ret.Get(0).(func() ddd.CommandPayload); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ddd.CommandPayload)
		}
	}
	return r0
}

// MockCommandMessage_Payload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Payload'
type MockCommandMessage_Payload_Call struct {
	*mock.Call
}

// Payload is a helper method to define mock.On call
func (_e *MockCommandMessage_Expecter) Payload() *MockCommandMessage_Payload_Call {
	return &MockCommandMessage_Payload_Call{Call: _e.mock.On("Payload")}
}

func (_c *MockCommandMessage_Payload_Call) Run(run func()) *MockCommandMessage_Payload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommandMessage_Payload_Call) Return(commandPayload ddd.CommandPayload) *MockCommandMessage_Payload_Call {
	_c.Call.Return(commandPayload)
	return _c
}

func (_c *MockCommandMessage_Payload_Call) RunAndReturn(run func() ddd.CommandPayload) *MockCommandMessage_Payload_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function for the type MockCommandMessage
func (_mock *MockCommandMessage) Subject() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCommandMessage_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type MockCommandMessage_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
func (_e *MockCommandMessage_Expecter) Subject() *MockCommandMessage_Subject_Call {
	return &MockCommandMessage_Subject_Call{Call: _e.mock.On("Subject")}
}

func (_c *MockCommandMessage_Subject_Call) Run(run func()) *MockCommandMessage_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommandMessage_Subject_Call) Return(s string) *MockCommandMessage_Subject_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCommandMessage_Subject_Call) RunAndReturn(run func() string) *MockCommandMessage_Subject_Call {
	_c.Call.Return(run)
	return _c
}
