// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandMessageHandler creates a new instance of MockCommandMessageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandMessageHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandMessageHandler {
	mock := &MockCommandMessageHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandMessageHandler is an autogenerated mock type for the CommandMessageHandler type
type MockCommandMessageHandler struct {
	mock.Mock
}

type MockCommandMessageHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandMessageHandler) EXPECT() *MockCommandMessageHandler_Expecter {
	return &MockCommandMessageHandler_Expecter{mock: &_m.Mock}
}

// HandleMessage provides a mock function for the type MockCommandMessageHandler
func (_mock *MockCommandMessageHandler) HandleMessage(ctx context.Context, msg IncomingCommandMessage) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for HandleMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, IncomingCommandMessage) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCommandMessageHandler_HandleMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleMessage'
type MockCommandMessageHandler_HandleMessage_Call struct {
	*mock.Call
}

// HandleMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg IncomingCommandMessage
func (_e *MockCommandMessageHandler_Expecter) HandleMessage(ctx interface{}, msg interface{}) *MockCommandMessageHandler_HandleMessage_Call {
	return &MockCommandMessageHandler_HandleMessage_Call{Call: _e.mock.On("HandleMessage", ctx, msg)}
}

func (_c *MockCommandMessageHandler_HandleMessage_Call) Run(run func(ctx context.Context, msg IncomingCommandMessage)) *MockCommandMessageHandler_HandleMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 IncomingCommandMessage
		if args[1] != nil {
			arg1 = args[1].(IncomingCommandMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommandMessageHandler_HandleMessage_Call) Return(err error) *MockCommandMessageHandler_HandleMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCommandMessageHandler_HandleMessage_Call) RunAndReturn(run func(ctx context.Context, msg IncomingCommandMessage) error) *MockCommandMessageHandler_HandleMessage_Call {
	_c.Call.Return(run)
	return _c
}
