// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	"eda-in-golang/internal/ddd"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommand creates a new instance of MockCommand. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommand(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommand {
	mock := &MockCommand{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommand is an autogenerated mock type for the Command type
type MockCommand struct {
	mock.Mock
}

type MockCommand_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommand) EXPECT() *MockCommand_Expecter {
	return &MockCommand_Expecter{mock: &_m.Mock}
}

// CommandName provides a mock function for the type MockCommand
func (_mock *MockCommand) CommandName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CommandName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCommand_CommandName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommandName'
type MockCommand_CommandName_Call struct {
	*mock.Call
}

// CommandName is a helper method to define mock.On call
func (_e *MockCommand_Expecter) CommandName() *MockCommand_CommandName_Call {
	return &MockCommand_CommandName_Call{Call: _e.mock.On("CommandName")}
}

func (_c *MockCommand_CommandName_Call) Run(run func()) *MockCommand_CommandName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommand_CommandName_Call) Return(s string) *MockCommand_CommandName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCommand_CommandName_Call) RunAndReturn(run func() string) *MockCommand_CommandName_Call {
	_c.Call.Return(run)
	return _c
}

// Destination provides a mock function for the type MockCommand
func (_mock *MockCommand) Destination() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Destination")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCommand_Destination_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Destination'
type MockCommand_Destination_Call struct {
	*mock.Call
}

// Destination is a helper method to define mock.On call
func (_e *MockCommand_Expecter) Destination() *MockCommand_Destination_Call {
	return &MockCommand_Destination_Call{Call: _e.mock.On("Destination")}
}

func (_c *MockCommand_Destination_Call) Run(run func()) *MockCommand_Destination_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommand_Destination_Call) Return(s string) *MockCommand_Destination_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCommand_Destination_Call) RunAndReturn(run func() string) *MockCommand_Destination_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockCommand
func (_mock *MockCommand) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockCommand_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockCommand_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockCommand_Expecter) ID() *MockCommand_ID_Call {
	return &MockCommand_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockCommand_ID_Call) Run(run func()) *MockCommand_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommand_ID_Call) Return(s string) *MockCommand_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockCommand_ID_Call) RunAndReturn(run func() string) *MockCommand_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function for the type MockCommand
func (_mock *MockCommand) Metadata() ddd.Metadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 ddd.Metadata
	if returnFunc, ok := ret.Get(0).(func() ddd.Metadata); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ddd.Metadata)
		}
	}
	return r0
}

// MockCommand_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockCommand_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockCommand_Expecter) Metadata() *MockCommand_Metadata_Call {
	return &MockCommand_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockCommand_Metadata_Call) Run(run func()) *MockCommand_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommand_Metadata_Call) Return(metadata ddd.Metadata) *MockCommand_Metadata_Call {
	_c.Call.Return(metadata)
	return _c
}

func (_c *MockCommand_Metadata_Call) RunAndReturn(run func() ddd.Metadata) *MockCommand_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// OccurredAt provides a mock function for the type MockCommand
func (_mock *MockCommand) OccurredAt() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OccurredAt")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockCommand_OccurredAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OccurredAt'
type MockCommand_OccurredAt_Call struct {
	*mock.Call
}

// OccurredAt is a helper method to define mock.On call
func (_e *MockCommand_Expecter) OccurredAt() *MockCommand_OccurredAt_Call {
	return &MockCommand_OccurredAt_Call{Call: _e.mock.On("OccurredAt")}
}

func (_c *MockCommand_OccurredAt_Call) Run(run func()) *MockCommand_OccurredAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommand_OccurredAt_Call) Return(time1 time.Time) *MockCommand_OccurredAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockCommand_OccurredAt_Call) RunAndReturn(run func() time.Time) *MockCommand_OccurredAt_Call {
	_c.Call.Return(run)
	return _c
}

// Payload provides a mock function for the type MockCommand
func (_mock *MockCommand) Payload() ddd.CommandPayload {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Payload")
	}

	var r0 ddd.CommandPayload
	if returnFunc, ok := ret.Get(0).(func() ddd.CommandPayload); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ddd.CommandPayload)
		}
	}
	return r0
}

// MockCommand_Payload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Payload'
type MockCommand_Payload_Call struct {
	*mock.Call
}

// Payload is a helper method to define mock.On call
func (_e *MockCommand_Expecter) Payload() *MockCommand_Payload_Call {
	return &MockCommand_Payload_Call{Call: _e.mock.On("Payload")}
}

func (_c *MockCommand_Payload_Call) Run(run func()) *MockCommand_Payload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockCommand_Payload_Call) Return(commandPayload ddd.CommandPayload) *MockCommand_Payload_Call {
	_c.Call.Return(commandPayload)
	return _c
}

func (_c *MockCommand_Payload_Call) RunAndReturn(run func() ddd.CommandPayload) *MockCommand_Payload_Call {
	_c.Call.Return(run)
	return _c
}
