// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	"eda-in-golang/internal/ddd"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventMessage creates a new instance of MockEventMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventMessage {
	mock := &MockEventMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventMessage is an autogenerated mock type for the EventMessage type
type MockEventMessage struct {
	mock.Mock
}

type MockEventMessage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventMessage) EXPECT() *MockEventMessage_Expecter {
	return &MockEventMessage_Expecter{mock: &_m.Mock}
}

// EventName provides a mock function for the type MockEventMessage
func (_mock *MockEventMessage) EventName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEventMessage_EventName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventName'
type MockEventMessage_EventName_Call struct {
	*mock.Call
}

// EventName is a helper method to define mock.On call
func (_e *MockEventMessage_Expecter) EventName() *MockEventMessage_EventName_Call {
	return &MockEventMessage_EventName_Call{Call: _e.mock.On("EventName")}
}

func (_c *MockEventMessage_EventName_Call) Run(run func()) *MockEventMessage_EventName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventMessage_EventName_Call) Return(s string) *MockEventMessage_EventName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEventMessage_EventName_Call) RunAndReturn(run func() string) *MockEventMessage_EventName_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockEventMessage
func (_mock *MockEventMessage) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEventMessage_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockEventMessage_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockEventMessage_Expecter) ID() *MockEventMessage_ID_Call {
	return &MockEventMessage_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockEventMessage_ID_Call) Run(run func()) *MockEventMessage_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventMessage_ID_Call) Return(s string) *MockEventMessage_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEventMessage_ID_Call) RunAndReturn(run func() string) *MockEventMessage_ID_Call {
	_c.Call.Return(run)
	return _c
}

// MessageName provides a mock function for the type MockEventMessage
func (_mock *MockEventMessage) MessageName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MessageName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEventMessage_MessageName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MessageName'
type MockEventMessage_MessageName_Call struct {
	*mock.Call
}

// MessageName is a helper method to define mock.On call
func (_e *MockEventMessage_Expecter) MessageName() *MockEventMessage_MessageName_Call {
	return &MockEventMessage_MessageName_Call{Call: _e.mock.On("MessageName")}
}

func (_c *MockEventMessage_MessageName_Call) Run(run func()) *MockEventMessage_MessageName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventMessage_MessageName_Call) Return(s string) *MockEventMessage_MessageName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEventMessage_MessageName_Call) RunAndReturn(run func() string) *MockEventMessage_MessageName_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function for the type MockEventMessage
func (_mock *MockEventMessage) Metadata() ddd.Metadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 ddd.Metadata
	if returnFunc, ok := ret.Get(0).(func() ddd.Metadata); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ddd.Metadata)
		}
	}
	return r0
}

// MockEventMessage_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockEventMessage_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockEventMessage_Expecter) Metadata() *MockEventMessage_Metadata_Call {
	return &MockEventMessage_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockEventMessage_Metadata_Call) Run(run func()) *MockEventMessage_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventMessage_Metadata_Call) Return(metadata ddd.Metadata) *MockEventMessage_Metadata_Call {
	_c.Call.Return(metadata)
	return _c
}

func (_c *MockEventMessage_Metadata_Call) RunAndReturn(run func() ddd.Metadata) *MockEventMessage_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// OccurredAt provides a mock function for the type MockEventMessage
func (_mock *MockEventMessage) OccurredAt() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OccurredAt")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockEventMessage_OccurredAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OccurredAt'
type MockEventMessage_OccurredAt_Call struct {
	*mock.Call
}

// OccurredAt is a helper method to define mock.On call
func (_e *MockEventMessage_Expecter) OccurredAt() *MockEventMessage_OccurredAt_Call {
	return &MockEventMessage_OccurredAt_Call{Call: _e.mock.On("OccurredAt")}
}

func (_c *MockEventMessage_OccurredAt_Call) Run(run func()) *MockEventMessage_OccurredAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventMessage_OccurredAt_Call) Return(time1 time.Time) *MockEventMessage_OccurredAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockEventMessage_OccurredAt_Call) RunAndReturn(run func() time.Time) *MockEventMessage_OccurredAt_Call {
	_c.Call.Return(run)
	return _c
}

// Payload provides a mock function for the type MockEventMessage
func (_mock *MockEventMessage) Payload() ddd.EventPayload {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Payload")
	}

	var r0 ddd.EventPayload
	if returnFunc, ok := ret.Get(0).(func() ddd.EventPayload); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ddd.EventPayload)
		}
	}
	return r0
}

// MockEventMessage_Payload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Payload'
type MockEventMessage_Payload_Call struct {
	*mock.Call
}

// Payload is a helper method to define mock.On call
func (_e *MockEventMessage_Expecter) Payload() *MockEventMessage_Payload_Call {
	return &MockEventMessage_Payload_Call{Call: _e.mock.On("Payload")}
}

func (_c *MockEventMessage_Payload_Call) Run(run func()) *MockEventMessage_Payload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventMessage_Payload_Call) Return(eventPayload ddd.EventPayload) *MockEventMessage_Payload_Call {
	_c.Call.Return(eventPayload)
	return _c
}

func (_c *MockEventMessage_Payload_Call) RunAndReturn(run func() ddd.EventPayload) *MockEventMessage_Payload_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function for the type MockEventMessage
func (_mock *MockEventMessage) Subject() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEventMessage_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type MockEventMessage_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
func (_e *MockEventMessage_Expecter) Subject() *MockEventMessage_Subject_Call {
	return &MockEventMessage_Subject_Call{Call: _e.mock.On("Subject")}
}

func (_c *MockEventMessage_Subject_Call) Run(run func()) *MockEventMessage_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventMessage_Subject_Call) Return(s string) *MockEventMessage_Subject_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEventMessage_Subject_Call) RunAndReturn(run func() string) *MockEventMessage_Subject_Call {
	_c.Call.Return(run)
	return _c
}
