// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventSubscriber creates a new instance of MockEventSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventSubscriber {
	mock := &MockEventSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventSubscriber is an autogenerated mock type for the EventSubscriber type
type MockEventSubscriber struct {
	mock.Mock
}

type MockEventSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventSubscriber) EXPECT() *MockEventSubscriber_Expecter {
	return &MockEventSubscriber_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function for the type MockEventSubscriber
func (_mock *MockEventSubscriber) Subscribe(topicName string, handler MessageHandler[IncomingEventMessage], options ...SubscriberOption) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(topicName, handler, options)
	} else {
		tmpRet = _mock.Called(topicName, handler)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, MessageHandler[IncomingEventMessage], ...SubscriberOption) error); ok {
		r0 = returnFunc(topicName, handler, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockEventSubscriber_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topicName string
//   - handler MessageHandler[IncomingEventMessage]
//   - options ...SubscriberOption
func (_e *MockEventSubscriber_Expecter) Subscribe(topicName interface{}, handler interface{}, options ...interface{}) *MockEventSubscriber_Subscribe_Call {
	return &MockEventSubscriber_Subscribe_Call{Call: _e.mock.On("Subscribe",
		append([]interface{}{topicName, handler}, options...)...)}
}

func (_c *MockEventSubscriber_Subscribe_Call) Run(run func(topicName string, handler MessageHandler[IncomingEventMessage], options ...SubscriberOption)) *MockEventSubscriber_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 MessageHandler[IncomingEventMessage]
		if args[1] != nil {
			arg1 = args[1].(MessageHandler[IncomingEventMessage])
		}
		var arg2 []SubscriberOption
		var variadicArgs []SubscriberOption
		if len(args) > 2 {
			variadicArgs = args[2].([]SubscriberOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEventSubscriber_Subscribe_Call) Return(err error) *MockEventSubscriber_Subscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventSubscriber_Subscribe_Call) RunAndReturn(run func(topicName string, handler MessageHandler[IncomingEventMessage], options ...SubscriberOption) error) *MockEventSubscriber_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
