// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	"context"
	"eda-in-golang/internal/ddd"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventStream creates a new instance of MockEventStream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventStream(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventStream {
	mock := &MockEventStream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventStream is an autogenerated mock type for the EventStream type
type MockEventStream struct {
	mock.Mock
}

type MockEventStream_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventStream) EXPECT() *MockEventStream_Expecter {
	return &MockEventStream_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockEventStream
func (_mock *MockEventStream) Publish(ctx context.Context, topicName string, v ddd.Event) error {
	ret := _mock.Called(ctx, topicName, v)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ddd.Event) error); ok {
		r0 = returnFunc(ctx, topicName, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventStream_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventStream_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - topicName string
//   - v ddd.Event
func (_e *MockEventStream_Expecter) Publish(ctx interface{}, topicName interface{}, v interface{}) *MockEventStream_Publish_Call {
	return &MockEventStream_Publish_Call{Call: _e.mock.On("Publish", ctx, topicName, v)}
}

func (_c *MockEventStream_Publish_Call) Run(run func(ctx context.Context, topicName string, v ddd.Event)) *MockEventStream_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ddd.Event
		if args[2] != nil {
			arg2 = args[2].(ddd.Event)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEventStream_Publish_Call) Return(err error) *MockEventStream_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventStream_Publish_Call) RunAndReturn(run func(ctx context.Context, topicName string, v ddd.Event) error) *MockEventStream_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockEventStream
func (_mock *MockEventStream) Subscribe(topicName string, handler MessageHandler[IncomingEventMessage], options ...SubscriberOption) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(topicName, handler, options)
	} else {
		tmpRet = _mock.Called(topicName, handler)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, MessageHandler[IncomingEventMessage], ...SubscriberOption) error); ok {
		r0 = returnFunc(topicName, handler, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventStream_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockEventStream_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topicName string
//   - handler MessageHandler[IncomingEventMessage]
//   - options ...SubscriberOption
func (_e *MockEventStream_Expecter) Subscribe(topicName interface{}, handler interface{}, options ...interface{}) *MockEventStream_Subscribe_Call {
	return &MockEventStream_Subscribe_Call{Call: _e.mock.On("Subscribe",
		append([]interface{}{topicName, handler}, options...)...)}
}

func (_c *MockEventStream_Subscribe_Call) Run(run func(topicName string, handler MessageHandler[IncomingEventMessage], options ...SubscriberOption)) *MockEventStream_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 MessageHandler[IncomingEventMessage]
		if args[1] != nil {
			arg1 = args[1].(MessageHandler[IncomingEventMessage])
		}
		var arg2 []SubscriberOption
		var variadicArgs []SubscriberOption
		if len(args) > 2 {
			variadicArgs = args[2].([]SubscriberOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEventStream_Subscribe_Call) Return(err error) *MockEventStream_Subscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventStream_Subscribe_Call) RunAndReturn(run func(topicName string, handler MessageHandler[IncomingEventMessage], options ...SubscriberOption) error) *MockEventStream_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
