// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	"eda-in-golang/internal/ddd"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIncomingReplyMessage creates a new instance of MockIncomingReplyMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIncomingReplyMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIncomingReplyMessage {
	mock := &MockIncomingReplyMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIncomingReplyMessage is an autogenerated mock type for the IncomingReplyMessage type
type MockIncomingReplyMessage struct {
	mock.Mock
}

type MockIncomingReplyMessage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIncomingReplyMessage) EXPECT() *MockIncomingReplyMessage_Expecter {
	return &MockIncomingReplyMessage_Expecter{mock: &_m.Mock}
}

// Ack provides a mock function for the type MockIncomingReplyMessage
func (_mock *MockIncomingReplyMessage) Ack() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingReplyMessage_Ack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ack'
type MockIncomingReplyMessage_Ack_Call struct {
	*mock.Call
}

// Ack is a helper method to define mock.On call
func (_e *MockIncomingReplyMessage_Expecter) Ack() *MockIncomingReplyMessage_Ack_Call {
	return &MockIncomingReplyMessage_Ack_Call{Call: _e.mock.On("Ack")}
}

func (_c *MockIncomingReplyMessage_Ack_Call) Run(run func()) *MockIncomingReplyMessage_Ack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingReplyMessage_Ack_Call) Return(err error) *MockIncomingReplyMessage_Ack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingReplyMessage_Ack_Call) RunAndReturn(run func() error) *MockIncomingReplyMessage_Ack_Call {
	_c.Call.Return(run)
	return _c
}

// Extend provides a mock function for the type MockIncomingReplyMessage
func (_mock *MockIncomingReplyMessage) Extend() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Extend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingReplyMessage_Extend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extend'
type MockIncomingReplyMessage_Extend_Call struct {
	*mock.Call
}

// Extend is a helper method to define mock.On call
func (_e *MockIncomingReplyMessage_Expecter) Extend() *MockIncomingReplyMessage_Extend_Call {
	return &MockIncomingReplyMessage_Extend_Call{Call: _e.mock.On("Extend")}
}

func (_c *MockIncomingReplyMessage_Extend_Call) Run(run func()) *MockIncomingReplyMessage_Extend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingReplyMessage_Extend_Call) Return(err error) *MockIncomingReplyMessage_Extend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingReplyMessage_Extend_Call) RunAndReturn(run func() error) *MockIncomingReplyMessage_Extend_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockIncomingReplyMessage
func (_mock *MockIncomingReplyMessage) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingReplyMessage_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockIncomingReplyMessage_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockIncomingReplyMessage_Expecter) ID() *MockIncomingReplyMessage_ID_Call {
	return &MockIncomingReplyMessage_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockIncomingReplyMessage_ID_Call) Run(run func()) *MockIncomingReplyMessage_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingReplyMessage_ID_Call) Return(s string) *MockIncomingReplyMessage_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingReplyMessage_ID_Call) RunAndReturn(run func() string) *MockIncomingReplyMessage_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Kill provides a mock function for the type MockIncomingReplyMessage
func (_mock *MockIncomingReplyMessage) Kill() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingReplyMessage_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type MockIncomingReplyMessage_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
func (_e *MockIncomingReplyMessage_Expecter) Kill() *MockIncomingReplyMessage_Kill_Call {
	return &MockIncomingReplyMessage_Kill_Call{Call: _e.mock.On("Kill")}
}

func (_c *MockIncomingReplyMessage_Kill_Call) Run(run func()) *MockIncomingReplyMessage_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingReplyMessage_Kill_Call) Return(err error) *MockIncomingReplyMessage_Kill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingReplyMessage_Kill_Call) RunAndReturn(run func() error) *MockIncomingReplyMessage_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// MessageName provides a mock function for the type MockIncomingReplyMessage
func (_mock *MockIncomingReplyMessage) MessageName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MessageName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingReplyMessage_MessageName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MessageName'
type MockIncomingReplyMessage_MessageName_Call struct {
	*mock.Call
}

// MessageName is a helper method to define mock.On call
func (_e *MockIncomingReplyMessage_Expecter) MessageName() *MockIncomingReplyMessage_MessageName_Call {
	return &MockIncomingReplyMessage_MessageName_Call{Call: _e.mock.On("MessageName")}
}

func (_c *MockIncomingReplyMessage_MessageName_Call) Run(run func()) *MockIncomingReplyMessage_MessageName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingReplyMessage_MessageName_Call) Return(s string) *MockIncomingReplyMessage_MessageName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingReplyMessage_MessageName_Call) RunAndReturn(run func() string) *MockIncomingReplyMessage_MessageName_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function for the type MockIncomingReplyMessage
func (_mock *MockIncomingReplyMessage) Metadata() ddd.Metadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 ddd.Metadata
	if returnFunc, ok := ret.Get(0).(func() ddd.Metadata); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ddd.Metadata)
		}
	}
	return r0
}

// MockIncomingReplyMessage_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockIncomingReplyMessage_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockIncomingReplyMessage_Expecter) Metadata() *MockIncomingReplyMessage_Metadata_Call {
	return &MockIncomingReplyMessage_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockIncomingReplyMessage_Metadata_Call) Run(run func()) *MockIncomingReplyMessage_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingReplyMessage_Metadata_Call) Return(metadata ddd.Metadata) *MockIncomingReplyMessage_Metadata_Call {
	_c.Call.Return(metadata)
	return _c
}

func (_c *MockIncomingReplyMessage_Metadata_Call) RunAndReturn(run func() ddd.Metadata) *MockIncomingReplyMessage_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// NAck provides a mock function for the type MockIncomingReplyMessage
func (_mock *MockIncomingReplyMessage) NAck() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NAck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingReplyMessage_NAck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NAck'
type MockIncomingReplyMessage_NAck_Call struct {
	*mock.Call
}

// NAck is a helper method to define mock.On call
func (_e *MockIncomingReplyMessage_Expecter) NAck() *MockIncomingReplyMessage_NAck_Call {
	return &MockIncomingReplyMessage_NAck_Call{Call: _e.mock.On("NAck")}
}

func (_c *MockIncomingReplyMessage_NAck_Call) Run(run func()) *MockIncomingReplyMessage_NAck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingReplyMessage_NAck_Call) Return(err error) *MockIncomingReplyMessage_NAck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingReplyMessage_NAck_Call) RunAndReturn(run func() error) *MockIncomingReplyMessage_NAck_Call {
	_c.Call.Return(run)
	return _c
}

// OccurredAt provides a mock function for the type MockIncomingReplyMessage
func (_mock *MockIncomingReplyMessage) OccurredAt() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OccurredAt")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockIncomingReplyMessage_OccurredAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OccurredAt'
type MockIncomingReplyMessage_OccurredAt_Call struct {
	*mock.Call
}

// OccurredAt is a helper method to define mock.On call
func (_e *MockIncomingReplyMessage_Expecter) OccurredAt() *MockIncomingReplyMessage_OccurredAt_Call {
	return &MockIncomingReplyMessage_OccurredAt_Call{Call: _e.mock.On("OccurredAt")}
}

func (_c *MockIncomingReplyMessage_OccurredAt_Call) Run(run func()) *MockIncomingReplyMessage_OccurredAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingReplyMessage_OccurredAt_Call) Return(time1 time.Time) *MockIncomingReplyMessage_OccurredAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockIncomingReplyMessage_OccurredAt_Call) RunAndReturn(run func() time.Time) *MockIncomingReplyMessage_OccurredAt_Call {
	_c.Call.Return(run)
	return _c
}

// Payload provides a mock function for the type MockIncomingReplyMessage
func (_mock *MockIncomingReplyMessage) Payload() ddd.ReplyPayload {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Payload")
	}

	var r0 ddd.ReplyPayload
	if returnFunc, ok := ret.Get(0).(func() ddd.ReplyPayload); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ddd.ReplyPayload)
		}
	}
	return r0
}

// MockIncomingReplyMessage_Payload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Payload'
type MockIncomingReplyMessage_Payload_Call struct {
	*mock.Call
}

// Payload is a helper method to define mock.On call
func (_e *MockIncomingReplyMessage_Expecter) Payload() *MockIncomingReplyMessage_Payload_Call {
	return &MockIncomingReplyMessage_Payload_Call{Call: _e.mock.On("Payload")}
}

func (_c *MockIncomingReplyMessage_Payload_Call) Run(run func()) *MockIncomingReplyMessage_Payload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingReplyMessage_Payload_Call) Return(replyPayload ddd.ReplyPayload) *MockIncomingReplyMessage_Payload_Call {
	_c.Call.Return(replyPayload)
	return _c
}

func (_c *MockIncomingReplyMessage_Payload_Call) RunAndReturn(run func() ddd.ReplyPayload) *MockIncomingReplyMessage_Payload_Call {
	_c.Call.Return(run)
	return _c
}

// ReplyName provides a mock function for the type MockIncomingReplyMessage
func (_mock *MockIncomingReplyMessage) ReplyName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReplyName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingReplyMessage_ReplyName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplyName'
type MockIncomingReplyMessage_ReplyName_Call struct {
	*mock.Call
}

// ReplyName is a helper method to define mock.On call
func (_e *MockIncomingReplyMessage_Expecter) ReplyName() *MockIncomingReplyMessage_ReplyName_Call {
	return &MockIncomingReplyMessage_ReplyName_Call{Call: _e.mock.On("ReplyName")}
}

func (_c *MockIncomingReplyMessage_ReplyName_Call) Run(run func()) *MockIncomingReplyMessage_ReplyName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingReplyMessage_ReplyName_Call) Return(s string) *MockIncomingReplyMessage_ReplyName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingReplyMessage_ReplyName_Call) RunAndReturn(run func() string) *MockIncomingReplyMessage_ReplyName_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function for the type MockIncomingReplyMessage
func (_mock *MockIncomingReplyMessage) Subject() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingReplyMessage_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type MockIncomingReplyMessage_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
func (_e *MockIncomingReplyMessage_Expecter) Subject() *MockIncomingReplyMessage_Subject_Call {
	return &MockIncomingReplyMessage_Subject_Call{Call: _e.mock.On("Subject")}
}

func (_c *MockIncomingReplyMessage_Subject_Call) Run(run func()) *MockIncomingReplyMessage_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingReplyMessage_Subject_Call) Return(s string) *MockIncomingReplyMessage_Subject_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingReplyMessage_Subject_Call) RunAndReturn(run func() string) *MockIncomingReplyMessage_Subject_Call {
	_c.Call.Return(run)
	return _c
}
