// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	"eda-in-golang/internal/ddd"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIncomingEventMessage creates a new instance of MockIncomingEventMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIncomingEventMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIncomingEventMessage {
	mock := &MockIncomingEventMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIncomingEventMessage is an autogenerated mock type for the IncomingEventMessage type
type MockIncomingEventMessage struct {
	mock.Mock
}

type MockIncomingEventMessage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIncomingEventMessage) EXPECT() *MockIncomingEventMessage_Expecter {
	return &MockIncomingEventMessage_Expecter{mock: &_m.Mock}
}

// Ack provides a mock function for the type MockIncomingEventMessage
func (_mock *MockIncomingEventMessage) Ack() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingEventMessage_Ack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ack'
type MockIncomingEventMessage_Ack_Call struct {
	*mock.Call
}

// Ack is a helper method to define mock.On call
func (_e *MockIncomingEventMessage_Expecter) Ack() *MockIncomingEventMessage_Ack_Call {
	return &MockIncomingEventMessage_Ack_Call{Call: _e.mock.On("Ack")}
}

func (_c *MockIncomingEventMessage_Ack_Call) Run(run func()) *MockIncomingEventMessage_Ack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingEventMessage_Ack_Call) Return(err error) *MockIncomingEventMessage_Ack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingEventMessage_Ack_Call) RunAndReturn(run func() error) *MockIncomingEventMessage_Ack_Call {
	_c.Call.Return(run)
	return _c
}

// EventName provides a mock function for the type MockIncomingEventMessage
func (_mock *MockIncomingEventMessage) EventName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for EventName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingEventMessage_EventName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EventName'
type MockIncomingEventMessage_EventName_Call struct {
	*mock.Call
}

// EventName is a helper method to define mock.On call
func (_e *MockIncomingEventMessage_Expecter) EventName() *MockIncomingEventMessage_EventName_Call {
	return &MockIncomingEventMessage_EventName_Call{Call: _e.mock.On("EventName")}
}

func (_c *MockIncomingEventMessage_EventName_Call) Run(run func()) *MockIncomingEventMessage_EventName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingEventMessage_EventName_Call) Return(s string) *MockIncomingEventMessage_EventName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingEventMessage_EventName_Call) RunAndReturn(run func() string) *MockIncomingEventMessage_EventName_Call {
	_c.Call.Return(run)
	return _c
}

// Extend provides a mock function for the type MockIncomingEventMessage
func (_mock *MockIncomingEventMessage) Extend() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Extend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingEventMessage_Extend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extend'
type MockIncomingEventMessage_Extend_Call struct {
	*mock.Call
}

// Extend is a helper method to define mock.On call
func (_e *MockIncomingEventMessage_Expecter) Extend() *MockIncomingEventMessage_Extend_Call {
	return &MockIncomingEventMessage_Extend_Call{Call: _e.mock.On("Extend")}
}

func (_c *MockIncomingEventMessage_Extend_Call) Run(run func()) *MockIncomingEventMessage_Extend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingEventMessage_Extend_Call) Return(err error) *MockIncomingEventMessage_Extend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingEventMessage_Extend_Call) RunAndReturn(run func() error) *MockIncomingEventMessage_Extend_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockIncomingEventMessage
func (_mock *MockIncomingEventMessage) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingEventMessage_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockIncomingEventMessage_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockIncomingEventMessage_Expecter) ID() *MockIncomingEventMessage_ID_Call {
	return &MockIncomingEventMessage_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockIncomingEventMessage_ID_Call) Run(run func()) *MockIncomingEventMessage_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingEventMessage_ID_Call) Return(s string) *MockIncomingEventMessage_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingEventMessage_ID_Call) RunAndReturn(run func() string) *MockIncomingEventMessage_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Kill provides a mock function for the type MockIncomingEventMessage
func (_mock *MockIncomingEventMessage) Kill() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingEventMessage_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type MockIncomingEventMessage_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
func (_e *MockIncomingEventMessage_Expecter) Kill() *MockIncomingEventMessage_Kill_Call {
	return &MockIncomingEventMessage_Kill_Call{Call: _e.mock.On("Kill")}
}

func (_c *MockIncomingEventMessage_Kill_Call) Run(run func()) *MockIncomingEventMessage_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingEventMessage_Kill_Call) Return(err error) *MockIncomingEventMessage_Kill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingEventMessage_Kill_Call) RunAndReturn(run func() error) *MockIncomingEventMessage_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// MessageName provides a mock function for the type MockIncomingEventMessage
func (_mock *MockIncomingEventMessage) MessageName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MessageName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingEventMessage_MessageName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MessageName'
type MockIncomingEventMessage_MessageName_Call struct {
	*mock.Call
}

// MessageName is a helper method to define mock.On call
func (_e *MockIncomingEventMessage_Expecter) MessageName() *MockIncomingEventMessage_MessageName_Call {
	return &MockIncomingEventMessage_MessageName_Call{Call: _e.mock.On("MessageName")}
}

func (_c *MockIncomingEventMessage_MessageName_Call) Run(run func()) *MockIncomingEventMessage_MessageName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingEventMessage_MessageName_Call) Return(s string) *MockIncomingEventMessage_MessageName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingEventMessage_MessageName_Call) RunAndReturn(run func() string) *MockIncomingEventMessage_MessageName_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function for the type MockIncomingEventMessage
func (_mock *MockIncomingEventMessage) Metadata() ddd.Metadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 ddd.Metadata
	if returnFunc, ok := ret.Get(0).(func() ddd.Metadata); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ddd.Metadata)
		}
	}
	return r0
}

// MockIncomingEventMessage_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockIncomingEventMessage_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockIncomingEventMessage_Expecter) Metadata() *MockIncomingEventMessage_Metadata_Call {
	return &MockIncomingEventMessage_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockIncomingEventMessage_Metadata_Call) Run(run func()) *MockIncomingEventMessage_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingEventMessage_Metadata_Call) Return(metadata ddd.Metadata) *MockIncomingEventMessage_Metadata_Call {
	_c.Call.Return(metadata)
	return _c
}

func (_c *MockIncomingEventMessage_Metadata_Call) RunAndReturn(run func() ddd.Metadata) *MockIncomingEventMessage_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// NAck provides a mock function for the type MockIncomingEventMessage
func (_mock *MockIncomingEventMessage) NAck() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NAck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingEventMessage_NAck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NAck'
type MockIncomingEventMessage_NAck_Call struct {
	*mock.Call
}

// NAck is a helper method to define mock.On call
func (_e *MockIncomingEventMessage_Expecter) NAck() *MockIncomingEventMessage_NAck_Call {
	return &MockIncomingEventMessage_NAck_Call{Call: _e.mock.On("NAck")}
}

func (_c *MockIncomingEventMessage_NAck_Call) Run(run func()) *MockIncomingEventMessage_NAck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingEventMessage_NAck_Call) Return(err error) *MockIncomingEventMessage_NAck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingEventMessage_NAck_Call) RunAndReturn(run func() error) *MockIncomingEventMessage_NAck_Call {
	_c.Call.Return(run)
	return _c
}

// OccurredAt provides a mock function for the type MockIncomingEventMessage
func (_mock *MockIncomingEventMessage) OccurredAt() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OccurredAt")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockIncomingEventMessage_OccurredAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OccurredAt'
type MockIncomingEventMessage_OccurredAt_Call struct {
	*mock.Call
}

// OccurredAt is a helper method to define mock.On call
func (_e *MockIncomingEventMessage_Expecter) OccurredAt() *MockIncomingEventMessage_OccurredAt_Call {
	return &MockIncomingEventMessage_OccurredAt_Call{Call: _e.mock.On("OccurredAt")}
}

func (_c *MockIncomingEventMessage_OccurredAt_Call) Run(run func()) *MockIncomingEventMessage_OccurredAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingEventMessage_OccurredAt_Call) Return(time1 time.Time) *MockIncomingEventMessage_OccurredAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockIncomingEventMessage_OccurredAt_Call) RunAndReturn(run func() time.Time) *MockIncomingEventMessage_OccurredAt_Call {
	_c.Call.Return(run)
	return _c
}

// Payload provides a mock function for the type MockIncomingEventMessage
func (_mock *MockIncomingEventMessage) Payload() ddd.EventPayload {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Payload")
	}

	var r0 ddd.EventPayload
	if returnFunc, ok := ret.Get(0).(func() ddd.EventPayload); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ddd.EventPayload)
		}
	}
	return r0
}

// MockIncomingEventMessage_Payload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Payload'
type MockIncomingEventMessage_Payload_Call struct {
	*mock.Call
}

// Payload is a helper method to define mock.On call
func (_e *MockIncomingEventMessage_Expecter) Payload() *MockIncomingEventMessage_Payload_Call {
	return &MockIncomingEventMessage_Payload_Call{Call: _e.mock.On("Payload")}
}

func (_c *MockIncomingEventMessage_Payload_Call) Run(run func()) *MockIncomingEventMessage_Payload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingEventMessage_Payload_Call) Return(eventPayload ddd.EventPayload) *MockIncomingEventMessage_Payload_Call {
	_c.Call.Return(eventPayload)
	return _c
}

func (_c *MockIncomingEventMessage_Payload_Call) RunAndReturn(run func() ddd.EventPayload) *MockIncomingEventMessage_Payload_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function for the type MockIncomingEventMessage
func (_mock *MockIncomingEventMessage) Subject() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingEventMessage_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type MockIncomingEventMessage_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
func (_e *MockIncomingEventMessage_Expecter) Subject() *MockIncomingEventMessage_Subject_Call {
	return &MockIncomingEventMessage_Subject_Call{Call: _e.mock.On("Subject")}
}

func (_c *MockIncomingEventMessage_Subject_Call) Run(run func()) *MockIncomingEventMessage_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingEventMessage_Subject_Call) Return(s string) *MockIncomingEventMessage_Subject_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingEventMessage_Subject_Call) RunAndReturn(run func() string) *MockIncomingEventMessage_Subject_Call {
	_c.Call.Return(run)
	return _c
}
