// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIncomingMessage creates a new instance of MockIncomingMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIncomingMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIncomingMessage {
	mock := &MockIncomingMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIncomingMessage is an autogenerated mock type for the IncomingMessage type
type MockIncomingMessage struct {
	mock.Mock
}

type MockIncomingMessage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIncomingMessage) EXPECT() *MockIncomingMessage_Expecter {
	return &MockIncomingMessage_Expecter{mock: &_m.Mock}
}

// Ack provides a mock function for the type MockIncomingMessage
func (_mock *MockIncomingMessage) Ack() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingMessage_Ack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ack'
type MockIncomingMessage_Ack_Call struct {
	*mock.Call
}

// Ack is a helper method to define mock.On call
func (_e *MockIncomingMessage_Expecter) Ack() *MockIncomingMessage_Ack_Call {
	return &MockIncomingMessage_Ack_Call{Call: _e.mock.On("Ack")}
}

func (_c *MockIncomingMessage_Ack_Call) Run(run func()) *MockIncomingMessage_Ack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingMessage_Ack_Call) Return(err error) *MockIncomingMessage_Ack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingMessage_Ack_Call) RunAndReturn(run func() error) *MockIncomingMessage_Ack_Call {
	_c.Call.Return(run)
	return _c
}

// Extend provides a mock function for the type MockIncomingMessage
func (_mock *MockIncomingMessage) Extend() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Extend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingMessage_Extend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extend'
type MockIncomingMessage_Extend_Call struct {
	*mock.Call
}

// Extend is a helper method to define mock.On call
func (_e *MockIncomingMessage_Expecter) Extend() *MockIncomingMessage_Extend_Call {
	return &MockIncomingMessage_Extend_Call{Call: _e.mock.On("Extend")}
}

func (_c *MockIncomingMessage_Extend_Call) Run(run func()) *MockIncomingMessage_Extend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingMessage_Extend_Call) Return(err error) *MockIncomingMessage_Extend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingMessage_Extend_Call) RunAndReturn(run func() error) *MockIncomingMessage_Extend_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockIncomingMessage
func (_mock *MockIncomingMessage) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingMessage_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockIncomingMessage_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockIncomingMessage_Expecter) ID() *MockIncomingMessage_ID_Call {
	return &MockIncomingMessage_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockIncomingMessage_ID_Call) Run(run func()) *MockIncomingMessage_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingMessage_ID_Call) Return(s string) *MockIncomingMessage_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingMessage_ID_Call) RunAndReturn(run func() string) *MockIncomingMessage_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Kill provides a mock function for the type MockIncomingMessage
func (_mock *MockIncomingMessage) Kill() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingMessage_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type MockIncomingMessage_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
func (_e *MockIncomingMessage_Expecter) Kill() *MockIncomingMessage_Kill_Call {
	return &MockIncomingMessage_Kill_Call{Call: _e.mock.On("Kill")}
}

func (_c *MockIncomingMessage_Kill_Call) Run(run func()) *MockIncomingMessage_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingMessage_Kill_Call) Return(err error) *MockIncomingMessage_Kill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingMessage_Kill_Call) RunAndReturn(run func() error) *MockIncomingMessage_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// MessageName provides a mock function for the type MockIncomingMessage
func (_mock *MockIncomingMessage) MessageName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MessageName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingMessage_MessageName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MessageName'
type MockIncomingMessage_MessageName_Call struct {
	*mock.Call
}

// MessageName is a helper method to define mock.On call
func (_e *MockIncomingMessage_Expecter) MessageName() *MockIncomingMessage_MessageName_Call {
	return &MockIncomingMessage_MessageName_Call{Call: _e.mock.On("MessageName")}
}

func (_c *MockIncomingMessage_MessageName_Call) Run(run func()) *MockIncomingMessage_MessageName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingMessage_MessageName_Call) Return(s string) *MockIncomingMessage_MessageName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingMessage_MessageName_Call) RunAndReturn(run func() string) *MockIncomingMessage_MessageName_Call {
	_c.Call.Return(run)
	return _c
}

// NAck provides a mock function for the type MockIncomingMessage
func (_mock *MockIncomingMessage) NAck() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NAck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingMessage_NAck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NAck'
type MockIncomingMessage_NAck_Call struct {
	*mock.Call
}

// NAck is a helper method to define mock.On call
func (_e *MockIncomingMessage_Expecter) NAck() *MockIncomingMessage_NAck_Call {
	return &MockIncomingMessage_NAck_Call{Call: _e.mock.On("NAck")}
}

func (_c *MockIncomingMessage_NAck_Call) Run(run func()) *MockIncomingMessage_NAck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingMessage_NAck_Call) Return(err error) *MockIncomingMessage_NAck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingMessage_NAck_Call) RunAndReturn(run func() error) *MockIncomingMessage_NAck_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function for the type MockIncomingMessage
func (_mock *MockIncomingMessage) Subject() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingMessage_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type MockIncomingMessage_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
func (_e *MockIncomingMessage_Expecter) Subject() *MockIncomingMessage_Subject_Call {
	return &MockIncomingMessage_Subject_Call{Call: _e.mock.On("Subject")}
}

func (_c *MockIncomingMessage_Subject_Call) Run(run func()) *MockIncomingMessage_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingMessage_Subject_Call) Return(s string) *MockIncomingMessage_Subject_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingMessage_Subject_Call) RunAndReturn(run func() string) *MockIncomingMessage_Subject_Call {
	_c.Call.Return(run)
	return _c
}
