// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	"eda-in-golang/internal/ddd"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockIncomingCommandMessage creates a new instance of MockIncomingCommandMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIncomingCommandMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIncomingCommandMessage {
	mock := &MockIncomingCommandMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIncomingCommandMessage is an autogenerated mock type for the IncomingCommandMessage type
type MockIncomingCommandMessage struct {
	mock.Mock
}

type MockIncomingCommandMessage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIncomingCommandMessage) EXPECT() *MockIncomingCommandMessage_Expecter {
	return &MockIncomingCommandMessage_Expecter{mock: &_m.Mock}
}

// Ack provides a mock function for the type MockIncomingCommandMessage
func (_mock *MockIncomingCommandMessage) Ack() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingCommandMessage_Ack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ack'
type MockIncomingCommandMessage_Ack_Call struct {
	*mock.Call
}

// Ack is a helper method to define mock.On call
func (_e *MockIncomingCommandMessage_Expecter) Ack() *MockIncomingCommandMessage_Ack_Call {
	return &MockIncomingCommandMessage_Ack_Call{Call: _e.mock.On("Ack")}
}

func (_c *MockIncomingCommandMessage_Ack_Call) Run(run func()) *MockIncomingCommandMessage_Ack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingCommandMessage_Ack_Call) Return(err error) *MockIncomingCommandMessage_Ack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingCommandMessage_Ack_Call) RunAndReturn(run func() error) *MockIncomingCommandMessage_Ack_Call {
	_c.Call.Return(run)
	return _c
}

// CommandName provides a mock function for the type MockIncomingCommandMessage
func (_mock *MockIncomingCommandMessage) CommandName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CommandName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingCommandMessage_CommandName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommandName'
type MockIncomingCommandMessage_CommandName_Call struct {
	*mock.Call
}

// CommandName is a helper method to define mock.On call
func (_e *MockIncomingCommandMessage_Expecter) CommandName() *MockIncomingCommandMessage_CommandName_Call {
	return &MockIncomingCommandMessage_CommandName_Call{Call: _e.mock.On("CommandName")}
}

func (_c *MockIncomingCommandMessage_CommandName_Call) Run(run func()) *MockIncomingCommandMessage_CommandName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingCommandMessage_CommandName_Call) Return(s string) *MockIncomingCommandMessage_CommandName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingCommandMessage_CommandName_Call) RunAndReturn(run func() string) *MockIncomingCommandMessage_CommandName_Call {
	_c.Call.Return(run)
	return _c
}

// Extend provides a mock function for the type MockIncomingCommandMessage
func (_mock *MockIncomingCommandMessage) Extend() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Extend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingCommandMessage_Extend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extend'
type MockIncomingCommandMessage_Extend_Call struct {
	*mock.Call
}

// Extend is a helper method to define mock.On call
func (_e *MockIncomingCommandMessage_Expecter) Extend() *MockIncomingCommandMessage_Extend_Call {
	return &MockIncomingCommandMessage_Extend_Call{Call: _e.mock.On("Extend")}
}

func (_c *MockIncomingCommandMessage_Extend_Call) Run(run func()) *MockIncomingCommandMessage_Extend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingCommandMessage_Extend_Call) Return(err error) *MockIncomingCommandMessage_Extend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingCommandMessage_Extend_Call) RunAndReturn(run func() error) *MockIncomingCommandMessage_Extend_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockIncomingCommandMessage
func (_mock *MockIncomingCommandMessage) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingCommandMessage_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockIncomingCommandMessage_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockIncomingCommandMessage_Expecter) ID() *MockIncomingCommandMessage_ID_Call {
	return &MockIncomingCommandMessage_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockIncomingCommandMessage_ID_Call) Run(run func()) *MockIncomingCommandMessage_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingCommandMessage_ID_Call) Return(s string) *MockIncomingCommandMessage_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingCommandMessage_ID_Call) RunAndReturn(run func() string) *MockIncomingCommandMessage_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Kill provides a mock function for the type MockIncomingCommandMessage
func (_mock *MockIncomingCommandMessage) Kill() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingCommandMessage_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type MockIncomingCommandMessage_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
func (_e *MockIncomingCommandMessage_Expecter) Kill() *MockIncomingCommandMessage_Kill_Call {
	return &MockIncomingCommandMessage_Kill_Call{Call: _e.mock.On("Kill")}
}

func (_c *MockIncomingCommandMessage_Kill_Call) Run(run func()) *MockIncomingCommandMessage_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingCommandMessage_Kill_Call) Return(err error) *MockIncomingCommandMessage_Kill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingCommandMessage_Kill_Call) RunAndReturn(run func() error) *MockIncomingCommandMessage_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// MessageName provides a mock function for the type MockIncomingCommandMessage
func (_mock *MockIncomingCommandMessage) MessageName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MessageName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingCommandMessage_MessageName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MessageName'
type MockIncomingCommandMessage_MessageName_Call struct {
	*mock.Call
}

// MessageName is a helper method to define mock.On call
func (_e *MockIncomingCommandMessage_Expecter) MessageName() *MockIncomingCommandMessage_MessageName_Call {
	return &MockIncomingCommandMessage_MessageName_Call{Call: _e.mock.On("MessageName")}
}

func (_c *MockIncomingCommandMessage_MessageName_Call) Run(run func()) *MockIncomingCommandMessage_MessageName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingCommandMessage_MessageName_Call) Return(s string) *MockIncomingCommandMessage_MessageName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingCommandMessage_MessageName_Call) RunAndReturn(run func() string) *MockIncomingCommandMessage_MessageName_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function for the type MockIncomingCommandMessage
func (_mock *MockIncomingCommandMessage) Metadata() ddd.Metadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 ddd.Metadata
	if returnFunc, ok := ret.Get(0).(func() ddd.Metadata); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ddd.Metadata)
		}
	}
	return r0
}

// MockIncomingCommandMessage_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockIncomingCommandMessage_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockIncomingCommandMessage_Expecter) Metadata() *MockIncomingCommandMessage_Metadata_Call {
	return &MockIncomingCommandMessage_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockIncomingCommandMessage_Metadata_Call) Run(run func()) *MockIncomingCommandMessage_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingCommandMessage_Metadata_Call) Return(metadata ddd.Metadata) *MockIncomingCommandMessage_Metadata_Call {
	_c.Call.Return(metadata)
	return _c
}

func (_c *MockIncomingCommandMessage_Metadata_Call) RunAndReturn(run func() ddd.Metadata) *MockIncomingCommandMessage_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// NAck provides a mock function for the type MockIncomingCommandMessage
func (_mock *MockIncomingCommandMessage) NAck() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NAck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingCommandMessage_NAck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NAck'
type MockIncomingCommandMessage_NAck_Call struct {
	*mock.Call
}

// NAck is a helper method to define mock.On call
func (_e *MockIncomingCommandMessage_Expecter) NAck() *MockIncomingCommandMessage_NAck_Call {
	return &MockIncomingCommandMessage_NAck_Call{Call: _e.mock.On("NAck")}
}

func (_c *MockIncomingCommandMessage_NAck_Call) Run(run func()) *MockIncomingCommandMessage_NAck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingCommandMessage_NAck_Call) Return(err error) *MockIncomingCommandMessage_NAck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingCommandMessage_NAck_Call) RunAndReturn(run func() error) *MockIncomingCommandMessage_NAck_Call {
	_c.Call.Return(run)
	return _c
}

// OccurredAt provides a mock function for the type MockIncomingCommandMessage
func (_mock *MockIncomingCommandMessage) OccurredAt() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OccurredAt")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockIncomingCommandMessage_OccurredAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OccurredAt'
type MockIncomingCommandMessage_OccurredAt_Call struct {
	*mock.Call
}

// OccurredAt is a helper method to define mock.On call
func (_e *MockIncomingCommandMessage_Expecter) OccurredAt() *MockIncomingCommandMessage_OccurredAt_Call {
	return &MockIncomingCommandMessage_OccurredAt_Call{Call: _e.mock.On("OccurredAt")}
}

func (_c *MockIncomingCommandMessage_OccurredAt_Call) Run(run func()) *MockIncomingCommandMessage_OccurredAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingCommandMessage_OccurredAt_Call) Return(time1 time.Time) *MockIncomingCommandMessage_OccurredAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockIncomingCommandMessage_OccurredAt_Call) RunAndReturn(run func() time.Time) *MockIncomingCommandMessage_OccurredAt_Call {
	_c.Call.Return(run)
	return _c
}

// Payload provides a mock function for the type MockIncomingCommandMessage
func (_mock *MockIncomingCommandMessage) Payload() ddd.CommandPayload {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Payload")
	}

	var r0 ddd.CommandPayload
	if returnFunc, ok := ret.Get(0).(func() ddd.CommandPayload); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ddd.CommandPayload)
		}
	}
	return r0
}

// MockIncomingCommandMessage_Payload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Payload'
type MockIncomingCommandMessage_Payload_Call struct {
	*mock.Call
}

// Payload is a helper method to define mock.On call
func (_e *MockIncomingCommandMessage_Expecter) Payload() *MockIncomingCommandMessage_Payload_Call {
	return &MockIncomingCommandMessage_Payload_Call{Call: _e.mock.On("Payload")}
}

func (_c *MockIncomingCommandMessage_Payload_Call) Run(run func()) *MockIncomingCommandMessage_Payload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingCommandMessage_Payload_Call) Return(commandPayload ddd.CommandPayload) *MockIncomingCommandMessage_Payload_Call {
	_c.Call.Return(commandPayload)
	return _c
}

func (_c *MockIncomingCommandMessage_Payload_Call) RunAndReturn(run func() ddd.CommandPayload) *MockIncomingCommandMessage_Payload_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function for the type MockIncomingCommandMessage
func (_mock *MockIncomingCommandMessage) Subject() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingCommandMessage_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type MockIncomingCommandMessage_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
func (_e *MockIncomingCommandMessage_Expecter) Subject() *MockIncomingCommandMessage_Subject_Call {
	return &MockIncomingCommandMessage_Subject_Call{Call: _e.mock.On("Subject")}
}

func (_c *MockIncomingCommandMessage_Subject_Call) Run(run func()) *MockIncomingCommandMessage_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingCommandMessage_Subject_Call) Return(s string) *MockIncomingCommandMessage_Subject_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingCommandMessage_Subject_Call) RunAndReturn(run func() string) *MockIncomingCommandMessage_Subject_Call {
	_c.Call.Return(run)
	return _c
}
