// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIncomingRawMessage creates a new instance of MockIncomingRawMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIncomingRawMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIncomingRawMessage {
	mock := &MockIncomingRawMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIncomingRawMessage is an autogenerated mock type for the IncomingRawMessage type
type MockIncomingRawMessage struct {
	mock.Mock
}

type MockIncomingRawMessage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIncomingRawMessage) EXPECT() *MockIncomingRawMessage_Expecter {
	return &MockIncomingRawMessage_Expecter{mock: &_m.Mock}
}

// Ack provides a mock function for the type MockIncomingRawMessage
func (_mock *MockIncomingRawMessage) Ack() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ack")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingRawMessage_Ack_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ack'
type MockIncomingRawMessage_Ack_Call struct {
	*mock.Call
}

// Ack is a helper method to define mock.On call
func (_e *MockIncomingRawMessage_Expecter) Ack() *MockIncomingRawMessage_Ack_Call {
	return &MockIncomingRawMessage_Ack_Call{Call: _e.mock.On("Ack")}
}

func (_c *MockIncomingRawMessage_Ack_Call) Run(run func()) *MockIncomingRawMessage_Ack_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingRawMessage_Ack_Call) Return(err error) *MockIncomingRawMessage_Ack_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingRawMessage_Ack_Call) RunAndReturn(run func() error) *MockIncomingRawMessage_Ack_Call {
	_c.Call.Return(run)
	return _c
}

// Data provides a mock function for the type MockIncomingRawMessage
func (_mock *MockIncomingRawMessage) Data() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Data")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockIncomingRawMessage_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Data'
type MockIncomingRawMessage_Data_Call struct {
	*mock.Call
}

// Data is a helper method to define mock.On call
func (_e *MockIncomingRawMessage_Expecter) Data() *MockIncomingRawMessage_Data_Call {
	return &MockIncomingRawMessage_Data_Call{Call: _e.mock.On("Data")}
}

func (_c *MockIncomingRawMessage_Data_Call) Run(run func()) *MockIncomingRawMessage_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingRawMessage_Data_Call) Return(bytes []byte) *MockIncomingRawMessage_Data_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockIncomingRawMessage_Data_Call) RunAndReturn(run func() []byte) *MockIncomingRawMessage_Data_Call {
	_c.Call.Return(run)
	return _c
}

// Extend provides a mock function for the type MockIncomingRawMessage
func (_mock *MockIncomingRawMessage) Extend() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Extend")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingRawMessage_Extend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extend'
type MockIncomingRawMessage_Extend_Call struct {
	*mock.Call
}

// Extend is a helper method to define mock.On call
func (_e *MockIncomingRawMessage_Expecter) Extend() *MockIncomingRawMessage_Extend_Call {
	return &MockIncomingRawMessage_Extend_Call{Call: _e.mock.On("Extend")}
}

func (_c *MockIncomingRawMessage_Extend_Call) Run(run func()) *MockIncomingRawMessage_Extend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingRawMessage_Extend_Call) Return(err error) *MockIncomingRawMessage_Extend_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingRawMessage_Extend_Call) RunAndReturn(run func() error) *MockIncomingRawMessage_Extend_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockIncomingRawMessage
func (_mock *MockIncomingRawMessage) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingRawMessage_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockIncomingRawMessage_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockIncomingRawMessage_Expecter) ID() *MockIncomingRawMessage_ID_Call {
	return &MockIncomingRawMessage_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockIncomingRawMessage_ID_Call) Run(run func()) *MockIncomingRawMessage_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingRawMessage_ID_Call) Return(s string) *MockIncomingRawMessage_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingRawMessage_ID_Call) RunAndReturn(run func() string) *MockIncomingRawMessage_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Kill provides a mock function for the type MockIncomingRawMessage
func (_mock *MockIncomingRawMessage) Kill() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kill")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingRawMessage_Kill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kill'
type MockIncomingRawMessage_Kill_Call struct {
	*mock.Call
}

// Kill is a helper method to define mock.On call
func (_e *MockIncomingRawMessage_Expecter) Kill() *MockIncomingRawMessage_Kill_Call {
	return &MockIncomingRawMessage_Kill_Call{Call: _e.mock.On("Kill")}
}

func (_c *MockIncomingRawMessage_Kill_Call) Run(run func()) *MockIncomingRawMessage_Kill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingRawMessage_Kill_Call) Return(err error) *MockIncomingRawMessage_Kill_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingRawMessage_Kill_Call) RunAndReturn(run func() error) *MockIncomingRawMessage_Kill_Call {
	_c.Call.Return(run)
	return _c
}

// MessageName provides a mock function for the type MockIncomingRawMessage
func (_mock *MockIncomingRawMessage) MessageName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MessageName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingRawMessage_MessageName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MessageName'
type MockIncomingRawMessage_MessageName_Call struct {
	*mock.Call
}

// MessageName is a helper method to define mock.On call
func (_e *MockIncomingRawMessage_Expecter) MessageName() *MockIncomingRawMessage_MessageName_Call {
	return &MockIncomingRawMessage_MessageName_Call{Call: _e.mock.On("MessageName")}
}

func (_c *MockIncomingRawMessage_MessageName_Call) Run(run func()) *MockIncomingRawMessage_MessageName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingRawMessage_MessageName_Call) Return(s string) *MockIncomingRawMessage_MessageName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingRawMessage_MessageName_Call) RunAndReturn(run func() string) *MockIncomingRawMessage_MessageName_Call {
	_c.Call.Return(run)
	return _c
}

// NAck provides a mock function for the type MockIncomingRawMessage
func (_mock *MockIncomingRawMessage) NAck() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NAck")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIncomingRawMessage_NAck_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NAck'
type MockIncomingRawMessage_NAck_Call struct {
	*mock.Call
}

// NAck is a helper method to define mock.On call
func (_e *MockIncomingRawMessage_Expecter) NAck() *MockIncomingRawMessage_NAck_Call {
	return &MockIncomingRawMessage_NAck_Call{Call: _e.mock.On("NAck")}
}

func (_c *MockIncomingRawMessage_NAck_Call) Run(run func()) *MockIncomingRawMessage_NAck_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingRawMessage_NAck_Call) Return(err error) *MockIncomingRawMessage_NAck_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIncomingRawMessage_NAck_Call) RunAndReturn(run func() error) *MockIncomingRawMessage_NAck_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function for the type MockIncomingRawMessage
func (_mock *MockIncomingRawMessage) Subject() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIncomingRawMessage_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type MockIncomingRawMessage_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
func (_e *MockIncomingRawMessage_Expecter) Subject() *MockIncomingRawMessage_Subject_Call {
	return &MockIncomingRawMessage_Subject_Call{Call: _e.mock.On("Subject")}
}

func (_c *MockIncomingRawMessage_Subject_Call) Run(run func()) *MockIncomingRawMessage_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIncomingRawMessage_Subject_Call) Return(s string) *MockIncomingRawMessage_Subject_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIncomingRawMessage_Subject_Call) RunAndReturn(run func() string) *MockIncomingRawMessage_Subject_Call {
	_c.Call.Return(run)
	return _c
}
