// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageSubscriber creates a new instance of MockMessageSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageSubscriber[I IncomingMessage](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageSubscriber[I] {
	mock := &MockMessageSubscriber[I]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageSubscriber is an autogenerated mock type for the MessageSubscriber type
type MockMessageSubscriber[I IncomingMessage] struct {
	mock.Mock
}

type MockMessageSubscriber_Expecter[I IncomingMessage] struct {
	mock *mock.Mock
}

func (_m *MockMessageSubscriber[I]) EXPECT() *MockMessageSubscriber_Expecter[I] {
	return &MockMessageSubscriber_Expecter[I]{mock: &_m.Mock}
}

// Subscribe provides a mock function for the type MockMessageSubscriber
func (_mock *MockMessageSubscriber[I]) Subscribe(topicName string, handler MessageHandler[I], options ...SubscriberOption) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(topicName, handler, options)
	} else {
		tmpRet = _mock.Called(topicName, handler)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, MessageHandler[I], ...SubscriberOption) error); ok {
		r0 = returnFunc(topicName, handler, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockMessageSubscriber_Subscribe_Call[I IncomingMessage] struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topicName string
//   - handler MessageHandler[I]
//   - options ...SubscriberOption
func (_e *MockMessageSubscriber_Expecter[I]) Subscribe(topicName interface{}, handler interface{}, options ...interface{}) *MockMessageSubscriber_Subscribe_Call[I] {
	return &MockMessageSubscriber_Subscribe_Call[I]{Call: _e.mock.On("Subscribe",
		append([]interface{}{topicName, handler}, options...)...)}
}

func (_c *MockMessageSubscriber_Subscribe_Call[I]) Run(run func(topicName string, handler MessageHandler[I], options ...SubscriberOption)) *MockMessageSubscriber_Subscribe_Call[I] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 MessageHandler[I]
		if args[1] != nil {
			arg1 = args[1].(MessageHandler[I])
		}
		var arg2 []SubscriberOption
		var variadicArgs []SubscriberOption
		if len(args) > 2 {
			variadicArgs = args[2].([]SubscriberOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMessageSubscriber_Subscribe_Call[I]) Return(err error) *MockMessageSubscriber_Subscribe_Call[I] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageSubscriber_Subscribe_Call[I]) RunAndReturn(run func(topicName string, handler MessageHandler[I], options ...SubscriberOption) error) *MockMessageSubscriber_Subscribe_Call[I] {
	_c.Call.Return(run)
	return _c
}
