// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageStream creates a new instance of MockMessageStream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageStream[O any, I IncomingMessage](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageStream[O, I] {
	mock := &MockMessageStream[O, I]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageStream is an autogenerated mock type for the MessageStream type
type MockMessageStream[O any, I IncomingMessage] struct {
	mock.Mock
}

type MockMessageStream_Expecter[O any, I IncomingMessage] struct {
	mock *mock.Mock
}

func (_m *MockMessageStream[O, I]) EXPECT() *MockMessageStream_Expecter[O, I] {
	return &MockMessageStream_Expecter[O, I]{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockMessageStream
func (_mock *MockMessageStream[O, I]) Publish(ctx context.Context, topicName string, v O) error {
	ret := _mock.Called(ctx, topicName, v)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, O) error); ok {
		r0 = returnFunc(ctx, topicName, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageStream_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockMessageStream_Publish_Call[O any, I IncomingMessage] struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - topicName string
//   - v O
func (_e *MockMessageStream_Expecter[O, I]) Publish(ctx interface{}, topicName interface{}, v interface{}) *MockMessageStream_Publish_Call[O, I] {
	return &MockMessageStream_Publish_Call[O, I]{Call: _e.mock.On("Publish", ctx, topicName, v)}
}

func (_c *MockMessageStream_Publish_Call[O, I]) Run(run func(ctx context.Context, topicName string, v O)) *MockMessageStream_Publish_Call[O, I] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 O
		if args[2] != nil {
			arg2 = args[2].(O)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMessageStream_Publish_Call[O, I]) Return(err error) *MockMessageStream_Publish_Call[O, I] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageStream_Publish_Call[O, I]) RunAndReturn(run func(ctx context.Context, topicName string, v O) error) *MockMessageStream_Publish_Call[O, I] {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockMessageStream
func (_mock *MockMessageStream[O, I]) Subscribe(topicName string, handler MessageHandler[I], options ...SubscriberOption) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(topicName, handler, options)
	} else {
		tmpRet = _mock.Called(topicName, handler)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, MessageHandler[I], ...SubscriberOption) error); ok {
		r0 = returnFunc(topicName, handler, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageStream_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockMessageStream_Subscribe_Call[O any, I IncomingMessage] struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topicName string
//   - handler MessageHandler[I]
//   - options ...SubscriberOption
func (_e *MockMessageStream_Expecter[O, I]) Subscribe(topicName interface{}, handler interface{}, options ...interface{}) *MockMessageStream_Subscribe_Call[O, I] {
	return &MockMessageStream_Subscribe_Call[O, I]{Call: _e.mock.On("Subscribe",
		append([]interface{}{topicName, handler}, options...)...)}
}

func (_c *MockMessageStream_Subscribe_Call[O, I]) Run(run func(topicName string, handler MessageHandler[I], options ...SubscriberOption)) *MockMessageStream_Subscribe_Call[O, I] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 MessageHandler[I]
		if args[1] != nil {
			arg1 = args[1].(MessageHandler[I])
		}
		var arg2 []SubscriberOption
		var variadicArgs []SubscriberOption
		if len(args) > 2 {
			variadicArgs = args[2].([]SubscriberOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMessageStream_Subscribe_Call[O, I]) Return(err error) *MockMessageStream_Subscribe_Call[O, I] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageStream_Subscribe_Call[O, I]) RunAndReturn(run func(topicName string, handler MessageHandler[I], options ...SubscriberOption) error) *MockMessageStream_Subscribe_Call[O, I] {
	_c.Call.Return(run)
	return _c
}
