// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockMessage creates a new instance of MockMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessage {
	mock := &MockMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessage is an autogenerated mock type for the Message type
type MockMessage struct {
	mock.Mock
}

type MockMessage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessage) EXPECT() *MockMessage_Expecter {
	return &MockMessage_Expecter{mock: &_m.Mock}
}

// ID provides a mock function for the type MockMessage
func (_mock *MockMessage) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMessage_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockMessage_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockMessage_Expecter) ID() *MockMessage_ID_Call {
	return &MockMessage_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockMessage_ID_Call) Run(run func()) *MockMessage_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessage_ID_Call) Return(s string) *MockMessage_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMessage_ID_Call) RunAndReturn(run func() string) *MockMessage_ID_Call {
	_c.Call.Return(run)
	return _c
}

// MessageName provides a mock function for the type MockMessage
func (_mock *MockMessage) MessageName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MessageName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMessage_MessageName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MessageName'
type MockMessage_MessageName_Call struct {
	*mock.Call
}

// MessageName is a helper method to define mock.On call
func (_e *MockMessage_Expecter) MessageName() *MockMessage_MessageName_Call {
	return &MockMessage_MessageName_Call{Call: _e.mock.On("MessageName")}
}

func (_c *MockMessage_MessageName_Call) Run(run func()) *MockMessage_MessageName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessage_MessageName_Call) Return(s string) *MockMessage_MessageName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMessage_MessageName_Call) RunAndReturn(run func() string) *MockMessage_MessageName_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function for the type MockMessage
func (_mock *MockMessage) Subject() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMessage_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type MockMessage_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
func (_e *MockMessage_Expecter) Subject() *MockMessage_Subject_Call {
	return &MockMessage_Subject_Call{Call: _e.mock.On("Subject")}
}

func (_c *MockMessage_Subject_Call) Run(run func()) *MockMessage_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessage_Subject_Call) Return(s string) *MockMessage_Subject_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMessage_Subject_Call) RunAndReturn(run func() string) *MockMessage_Subject_Call {
	_c.Call.Return(run)
	return _c
}
