// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMessageHandler creates a new instance of MockMessageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageHandler[I IncomingMessage](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageHandler[I] {
	mock := &MockMessageHandler[I]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMessageHandler is an autogenerated mock type for the MessageHandler type
type MockMessageHandler[I IncomingMessage] struct {
	mock.Mock
}

type MockMessageHandler_Expecter[I IncomingMessage] struct {
	mock *mock.Mock
}

func (_m *MockMessageHandler[I]) EXPECT() *MockMessageHandler_Expecter[I] {
	return &MockMessageHandler_Expecter[I]{mock: &_m.Mock}
}

// HandleMessage provides a mock function for the type MockMessageHandler
func (_mock *MockMessageHandler[I]) HandleMessage(ctx context.Context, msg I) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for HandleMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, I) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMessageHandler_HandleMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleMessage'
type MockMessageHandler_HandleMessage_Call[I IncomingMessage] struct {
	*mock.Call
}

// HandleMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg I
func (_e *MockMessageHandler_Expecter[I]) HandleMessage(ctx interface{}, msg interface{}) *MockMessageHandler_HandleMessage_Call[I] {
	return &MockMessageHandler_HandleMessage_Call[I]{Call: _e.mock.On("HandleMessage", ctx, msg)}
}

func (_c *MockMessageHandler_HandleMessage_Call[I]) Run(run func(ctx context.Context, msg I)) *MockMessageHandler_HandleMessage_Call[I] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 I
		if args[1] != nil {
			arg1 = args[1].(I)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMessageHandler_HandleMessage_Call[I]) Return(err error) *MockMessageHandler_HandleMessage_Call[I] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMessageHandler_HandleMessage_Call[I]) RunAndReturn(run func(ctx context.Context, msg I) error) *MockMessageHandler_HandleMessage_Call[I] {
	_c.Call.Return(run)
	return _c
}
