// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRawMessageStream creates a new instance of MockRawMessageStream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRawMessageStream(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRawMessageStream {
	mock := &MockRawMessageStream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRawMessageStream is an autogenerated mock type for the RawMessageStream type
type MockRawMessageStream struct {
	mock.Mock
}

type MockRawMessageStream_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRawMessageStream) EXPECT() *MockRawMessageStream_Expecter {
	return &MockRawMessageStream_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockRawMessageStream
func (_mock *MockRawMessageStream) Publish(ctx context.Context, topicName string, v RawMessage) error {
	ret := _mock.Called(ctx, topicName, v)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, RawMessage) error); ok {
		r0 = returnFunc(ctx, topicName, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRawMessageStream_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockRawMessageStream_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - topicName string
//   - v RawMessage
func (_e *MockRawMessageStream_Expecter) Publish(ctx interface{}, topicName interface{}, v interface{}) *MockRawMessageStream_Publish_Call {
	return &MockRawMessageStream_Publish_Call{Call: _e.mock.On("Publish", ctx, topicName, v)}
}

func (_c *MockRawMessageStream_Publish_Call) Run(run func(ctx context.Context, topicName string, v RawMessage)) *MockRawMessageStream_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 RawMessage
		if args[2] != nil {
			arg2 = args[2].(RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRawMessageStream_Publish_Call) Return(err error) *MockRawMessageStream_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRawMessageStream_Publish_Call) RunAndReturn(run func(ctx context.Context, topicName string, v RawMessage) error) *MockRawMessageStream_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockRawMessageStream
func (_mock *MockRawMessageStream) Subscribe(topicName string, handler MessageHandler[IncomingRawMessage], options ...SubscriberOption) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(topicName, handler, options)
	} else {
		tmpRet = _mock.Called(topicName, handler)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, MessageHandler[IncomingRawMessage], ...SubscriberOption) error); ok {
		r0 = returnFunc(topicName, handler, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRawMessageStream_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockRawMessageStream_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topicName string
//   - handler MessageHandler[IncomingRawMessage]
//   - options ...SubscriberOption
func (_e *MockRawMessageStream_Expecter) Subscribe(topicName interface{}, handler interface{}, options ...interface{}) *MockRawMessageStream_Subscribe_Call {
	return &MockRawMessageStream_Subscribe_Call{Call: _e.mock.On("Subscribe",
		append([]interface{}{topicName, handler}, options...)...)}
}

func (_c *MockRawMessageStream_Subscribe_Call) Run(run func(topicName string, handler MessageHandler[IncomingRawMessage], options ...SubscriberOption)) *MockRawMessageStream_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 MessageHandler[IncomingRawMessage]
		if args[1] != nil {
			arg1 = args[1].(MessageHandler[IncomingRawMessage])
		}
		var arg2 []SubscriberOption
		var variadicArgs []SubscriberOption
		if len(args) > 2 {
			variadicArgs = args[2].([]SubscriberOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRawMessageStream_Subscribe_Call) Return(err error) *MockRawMessageStream_Subscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRawMessageStream_Subscribe_Call) RunAndReturn(run func(topicName string, handler MessageHandler[IncomingRawMessage], options ...SubscriberOption) error) *MockRawMessageStream_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
