// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRawMessageSubscriber creates a new instance of MockRawMessageSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRawMessageSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRawMessageSubscriber {
	mock := &MockRawMessageSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRawMessageSubscriber is an autogenerated mock type for the RawMessageSubscriber type
type MockRawMessageSubscriber struct {
	mock.Mock
}

type MockRawMessageSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRawMessageSubscriber) EXPECT() *MockRawMessageSubscriber_Expecter {
	return &MockRawMessageSubscriber_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function for the type MockRawMessageSubscriber
func (_mock *MockRawMessageSubscriber) Subscribe(topicName string, handler MessageHandler[IncomingRawMessage], options ...SubscriberOption) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(topicName, handler, options)
	} else {
		tmpRet = _mock.Called(topicName, handler)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, MessageHandler[IncomingRawMessage], ...SubscriberOption) error); ok {
		r0 = returnFunc(topicName, handler, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRawMessageSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockRawMessageSubscriber_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topicName string
//   - handler MessageHandler[IncomingRawMessage]
//   - options ...SubscriberOption
func (_e *MockRawMessageSubscriber_Expecter) Subscribe(topicName interface{}, handler interface{}, options ...interface{}) *MockRawMessageSubscriber_Subscribe_Call {
	return &MockRawMessageSubscriber_Subscribe_Call{Call: _e.mock.On("Subscribe",
		append([]interface{}{topicName, handler}, options...)...)}
}

func (_c *MockRawMessageSubscriber_Subscribe_Call) Run(run func(topicName string, handler MessageHandler[IncomingRawMessage], options ...SubscriberOption)) *MockRawMessageSubscriber_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 MessageHandler[IncomingRawMessage]
		if args[1] != nil {
			arg1 = args[1].(MessageHandler[IncomingRawMessage])
		}
		var arg2 []SubscriberOption
		var variadicArgs []SubscriberOption
		if len(args) > 2 {
			variadicArgs = args[2].([]SubscriberOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRawMessageSubscriber_Subscribe_Call) Return(err error) *MockRawMessageSubscriber_Subscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRawMessageSubscriber_Subscribe_Call) RunAndReturn(run func(topicName string, handler MessageHandler[IncomingRawMessage], options ...SubscriberOption) error) *MockRawMessageSubscriber_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
