// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRawMessage creates a new instance of MockRawMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRawMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRawMessage {
	mock := &MockRawMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRawMessage is an autogenerated mock type for the RawMessage type
type MockRawMessage struct {
	mock.Mock
}

type MockRawMessage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRawMessage) EXPECT() *MockRawMessage_Expecter {
	return &MockRawMessage_Expecter{mock: &_m.Mock}
}

// Data provides a mock function for the type MockRawMessage
func (_mock *MockRawMessage) Data() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Data")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// MockRawMessage_Data_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Data'
type MockRawMessage_Data_Call struct {
	*mock.Call
}

// Data is a helper method to define mock.On call
func (_e *MockRawMessage_Expecter) Data() *MockRawMessage_Data_Call {
	return &MockRawMessage_Data_Call{Call: _e.mock.On("Data")}
}

func (_c *MockRawMessage_Data_Call) Run(run func()) *MockRawMessage_Data_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRawMessage_Data_Call) Return(bytes []byte) *MockRawMessage_Data_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *MockRawMessage_Data_Call) RunAndReturn(run func() []byte) *MockRawMessage_Data_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockRawMessage
func (_mock *MockRawMessage) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRawMessage_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockRawMessage_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockRawMessage_Expecter) ID() *MockRawMessage_ID_Call {
	return &MockRawMessage_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockRawMessage_ID_Call) Run(run func()) *MockRawMessage_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRawMessage_ID_Call) Return(s string) *MockRawMessage_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRawMessage_ID_Call) RunAndReturn(run func() string) *MockRawMessage_ID_Call {
	_c.Call.Return(run)
	return _c
}

// MessageName provides a mock function for the type MockRawMessage
func (_mock *MockRawMessage) MessageName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MessageName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRawMessage_MessageName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MessageName'
type MockRawMessage_MessageName_Call struct {
	*mock.Call
}

// MessageName is a helper method to define mock.On call
func (_e *MockRawMessage_Expecter) MessageName() *MockRawMessage_MessageName_Call {
	return &MockRawMessage_MessageName_Call{Call: _e.mock.On("MessageName")}
}

func (_c *MockRawMessage_MessageName_Call) Run(run func()) *MockRawMessage_MessageName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRawMessage_MessageName_Call) Return(s string) *MockRawMessage_MessageName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRawMessage_MessageName_Call) RunAndReturn(run func() string) *MockRawMessage_MessageName_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function for the type MockRawMessage
func (_mock *MockRawMessage) Subject() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRawMessage_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type MockRawMessage_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
func (_e *MockRawMessage_Expecter) Subject() *MockRawMessage_Subject_Call {
	return &MockRawMessage_Subject_Call{Call: _e.mock.On("Subject")}
}

func (_c *MockRawMessage_Subject_Call) Run(run func()) *MockRawMessage_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRawMessage_Subject_Call) Return(s string) *MockRawMessage_Subject_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRawMessage_Subject_Call) RunAndReturn(run func() string) *MockRawMessage_Subject_Call {
	_c.Call.Return(run)
	return _c
}
