// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRawMessageHandler creates a new instance of MockRawMessageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRawMessageHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRawMessageHandler {
	mock := &MockRawMessageHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRawMessageHandler is an autogenerated mock type for the RawMessageHandler type
type MockRawMessageHandler struct {
	mock.Mock
}

type MockRawMessageHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRawMessageHandler) EXPECT() *MockRawMessageHandler_Expecter {
	return &MockRawMessageHandler_Expecter{mock: &_m.Mock}
}

// HandleMessage provides a mock function for the type MockRawMessageHandler
func (_mock *MockRawMessageHandler) HandleMessage(ctx context.Context, msg IncomingRawMessage) error {
	ret := _mock.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for HandleMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, IncomingRawMessage) error); ok {
		r0 = returnFunc(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRawMessageHandler_HandleMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleMessage'
type MockRawMessageHandler_HandleMessage_Call struct {
	*mock.Call
}

// HandleMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg IncomingRawMessage
func (_e *MockRawMessageHandler_Expecter) HandleMessage(ctx interface{}, msg interface{}) *MockRawMessageHandler_HandleMessage_Call {
	return &MockRawMessageHandler_HandleMessage_Call{Call: _e.mock.On("HandleMessage", ctx, msg)}
}

func (_c *MockRawMessageHandler_HandleMessage_Call) Run(run func(ctx context.Context, msg IncomingRawMessage)) *MockRawMessageHandler_HandleMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 IncomingRawMessage
		if args[1] != nil {
			arg1 = args[1].(IncomingRawMessage)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRawMessageHandler_HandleMessage_Call) Return(err error) *MockRawMessageHandler_HandleMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRawMessageHandler_HandleMessage_Call) RunAndReturn(run func(ctx context.Context, msg IncomingRawMessage) error) *MockRawMessageHandler_HandleMessage_Call {
	_c.Call.Return(run)
	return _c
}
