// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	"eda-in-golang/internal/ddd"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReplyMessage creates a new instance of MockReplyMessage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReplyMessage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReplyMessage {
	mock := &MockReplyMessage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReplyMessage is an autogenerated mock type for the ReplyMessage type
type MockReplyMessage struct {
	mock.Mock
}

type MockReplyMessage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReplyMessage) EXPECT() *MockReplyMessage_Expecter {
	return &MockReplyMessage_Expecter{mock: &_m.Mock}
}

// ID provides a mock function for the type MockReplyMessage
func (_mock *MockReplyMessage) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReplyMessage_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockReplyMessage_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockReplyMessage_Expecter) ID() *MockReplyMessage_ID_Call {
	return &MockReplyMessage_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockReplyMessage_ID_Call) Run(run func()) *MockReplyMessage_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReplyMessage_ID_Call) Return(s string) *MockReplyMessage_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReplyMessage_ID_Call) RunAndReturn(run func() string) *MockReplyMessage_ID_Call {
	_c.Call.Return(run)
	return _c
}

// MessageName provides a mock function for the type MockReplyMessage
func (_mock *MockReplyMessage) MessageName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for MessageName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReplyMessage_MessageName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MessageName'
type MockReplyMessage_MessageName_Call struct {
	*mock.Call
}

// MessageName is a helper method to define mock.On call
func (_e *MockReplyMessage_Expecter) MessageName() *MockReplyMessage_MessageName_Call {
	return &MockReplyMessage_MessageName_Call{Call: _e.mock.On("MessageName")}
}

func (_c *MockReplyMessage_MessageName_Call) Run(run func()) *MockReplyMessage_MessageName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReplyMessage_MessageName_Call) Return(s string) *MockReplyMessage_MessageName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReplyMessage_MessageName_Call) RunAndReturn(run func() string) *MockReplyMessage_MessageName_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function for the type MockReplyMessage
func (_mock *MockReplyMessage) Metadata() ddd.Metadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 ddd.Metadata
	if returnFunc, ok := ret.Get(0).(func() ddd.Metadata); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ddd.Metadata)
		}
	}
	return r0
}

// MockReplyMessage_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockReplyMessage_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockReplyMessage_Expecter) Metadata() *MockReplyMessage_Metadata_Call {
	return &MockReplyMessage_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockReplyMessage_Metadata_Call) Run(run func()) *MockReplyMessage_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReplyMessage_Metadata_Call) Return(metadata ddd.Metadata) *MockReplyMessage_Metadata_Call {
	_c.Call.Return(metadata)
	return _c
}

func (_c *MockReplyMessage_Metadata_Call) RunAndReturn(run func() ddd.Metadata) *MockReplyMessage_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// OccurredAt provides a mock function for the type MockReplyMessage
func (_mock *MockReplyMessage) OccurredAt() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OccurredAt")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockReplyMessage_OccurredAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OccurredAt'
type MockReplyMessage_OccurredAt_Call struct {
	*mock.Call
}

// OccurredAt is a helper method to define mock.On call
func (_e *MockReplyMessage_Expecter) OccurredAt() *MockReplyMessage_OccurredAt_Call {
	return &MockReplyMessage_OccurredAt_Call{Call: _e.mock.On("OccurredAt")}
}

func (_c *MockReplyMessage_OccurredAt_Call) Run(run func()) *MockReplyMessage_OccurredAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReplyMessage_OccurredAt_Call) Return(time1 time.Time) *MockReplyMessage_OccurredAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockReplyMessage_OccurredAt_Call) RunAndReturn(run func() time.Time) *MockReplyMessage_OccurredAt_Call {
	_c.Call.Return(run)
	return _c
}

// Payload provides a mock function for the type MockReplyMessage
func (_mock *MockReplyMessage) Payload() ddd.ReplyPayload {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Payload")
	}

	var r0 ddd.ReplyPayload
	if returnFunc, ok := ret.Get(0).(func() ddd.ReplyPayload); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ddd.ReplyPayload)
		}
	}
	return r0
}

// MockReplyMessage_Payload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Payload'
type MockReplyMessage_Payload_Call struct {
	*mock.Call
}

// Payload is a helper method to define mock.On call
func (_e *MockReplyMessage_Expecter) Payload() *MockReplyMessage_Payload_Call {
	return &MockReplyMessage_Payload_Call{Call: _e.mock.On("Payload")}
}

func (_c *MockReplyMessage_Payload_Call) Run(run func()) *MockReplyMessage_Payload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReplyMessage_Payload_Call) Return(replyPayload ddd.ReplyPayload) *MockReplyMessage_Payload_Call {
	_c.Call.Return(replyPayload)
	return _c
}

func (_c *MockReplyMessage_Payload_Call) RunAndReturn(run func() ddd.ReplyPayload) *MockReplyMessage_Payload_Call {
	_c.Call.Return(run)
	return _c
}

// ReplyName provides a mock function for the type MockReplyMessage
func (_mock *MockReplyMessage) ReplyName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReplyName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReplyMessage_ReplyName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplyName'
type MockReplyMessage_ReplyName_Call struct {
	*mock.Call
}

// ReplyName is a helper method to define mock.On call
func (_e *MockReplyMessage_Expecter) ReplyName() *MockReplyMessage_ReplyName_Call {
	return &MockReplyMessage_ReplyName_Call{Call: _e.mock.On("ReplyName")}
}

func (_c *MockReplyMessage_ReplyName_Call) Run(run func()) *MockReplyMessage_ReplyName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReplyMessage_ReplyName_Call) Return(s string) *MockReplyMessage_ReplyName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReplyMessage_ReplyName_Call) RunAndReturn(run func() string) *MockReplyMessage_ReplyName_Call {
	_c.Call.Return(run)
	return _c
}

// Subject provides a mock function for the type MockReplyMessage
func (_mock *MockReplyMessage) Subject() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subject")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReplyMessage_Subject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subject'
type MockReplyMessage_Subject_Call struct {
	*mock.Call
}

// Subject is a helper method to define mock.On call
func (_e *MockReplyMessage_Expecter) Subject() *MockReplyMessage_Subject_Call {
	return &MockReplyMessage_Subject_Call{Call: _e.mock.On("Subject")}
}

func (_c *MockReplyMessage_Subject_Call) Run(run func()) *MockReplyMessage_Subject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReplyMessage_Subject_Call) Return(s string) *MockReplyMessage_Subject_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReplyMessage_Subject_Call) RunAndReturn(run func() string) *MockReplyMessage_Subject_Call {
	_c.Call.Return(run)
	return _c
}
