// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	"context"
	"eda-in-golang/internal/ddd"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReplyStream creates a new instance of MockReplyStream. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReplyStream(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReplyStream {
	mock := &MockReplyStream{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReplyStream is an autogenerated mock type for the ReplyStream type
type MockReplyStream struct {
	mock.Mock
}

type MockReplyStream_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReplyStream) EXPECT() *MockReplyStream_Expecter {
	return &MockReplyStream_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockReplyStream
func (_mock *MockReplyStream) Publish(ctx context.Context, topicName string, v ddd.Reply) error {
	ret := _mock.Called(ctx, topicName, v)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ddd.Reply) error); ok {
		r0 = returnFunc(ctx, topicName, v)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReplyStream_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockReplyStream_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - topicName string
//   - v ddd.Reply
func (_e *MockReplyStream_Expecter) Publish(ctx interface{}, topicName interface{}, v interface{}) *MockReplyStream_Publish_Call {
	return &MockReplyStream_Publish_Call{Call: _e.mock.On("Publish", ctx, topicName, v)}
}

func (_c *MockReplyStream_Publish_Call) Run(run func(ctx context.Context, topicName string, v ddd.Reply)) *MockReplyStream_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 ddd.Reply
		if args[2] != nil {
			arg2 = args[2].(ddd.Reply)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReplyStream_Publish_Call) Return(err error) *MockReplyStream_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReplyStream_Publish_Call) RunAndReturn(run func(ctx context.Context, topicName string, v ddd.Reply) error) *MockReplyStream_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function for the type MockReplyStream
func (_mock *MockReplyStream) Subscribe(topicName string, handler MessageHandler[IncomingReplyMessage], options ...SubscriberOption) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(topicName, handler, options)
	} else {
		tmpRet = _mock.Called(topicName, handler)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, MessageHandler[IncomingReplyMessage], ...SubscriberOption) error); ok {
		r0 = returnFunc(topicName, handler, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReplyStream_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockReplyStream_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topicName string
//   - handler MessageHandler[IncomingReplyMessage]
//   - options ...SubscriberOption
func (_e *MockReplyStream_Expecter) Subscribe(topicName interface{}, handler interface{}, options ...interface{}) *MockReplyStream_Subscribe_Call {
	return &MockReplyStream_Subscribe_Call{Call: _e.mock.On("Subscribe",
		append([]interface{}{topicName, handler}, options...)...)}
}

func (_c *MockReplyStream_Subscribe_Call) Run(run func(topicName string, handler MessageHandler[IncomingReplyMessage], options ...SubscriberOption)) *MockReplyStream_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 MessageHandler[IncomingReplyMessage]
		if args[1] != nil {
			arg1 = args[1].(MessageHandler[IncomingReplyMessage])
		}
		var arg2 []SubscriberOption
		var variadicArgs []SubscriberOption
		if len(args) > 2 {
			variadicArgs = args[2].([]SubscriberOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockReplyStream_Subscribe_Call) Return(err error) *MockReplyStream_Subscribe_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReplyStream_Subscribe_Call) RunAndReturn(run func(topicName string, handler MessageHandler[IncomingReplyMessage], options ...SubscriberOption) error) *MockReplyStream_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
