// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package am

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSubscriberOption creates a new instance of MockSubscriberOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSubscriberOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSubscriberOption {
	mock := &MockSubscriberOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSubscriberOption is an autogenerated mock type for the SubscriberOption type
type MockSubscriberOption struct {
	mock.Mock
}

type MockSubscriberOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSubscriberOption) EXPECT() *MockSubscriberOption_Expecter {
	return &MockSubscriberOption_Expecter{mock: &_m.Mock}
}

// configureSubscriberConfig provides a mock function for the type MockSubscriberOption
func (_mock *MockSubscriberOption) configureSubscriberConfig(subscriberConfig *SubscriberConfig) {
	_mock.Called(subscriberConfig)
	return
}

// MockSubscriberOption_configureSubscriberConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'configureSubscriberConfig'
type MockSubscriberOption_configureSubscriberConfig_Call struct {
	*mock.Call
}

// configureSubscriberConfig is a helper method to define mock.On call
//   - subscriberConfig *SubscriberConfig
func (_e *MockSubscriberOption_Expecter) configureSubscriberConfig(subscriberConfig interface{}) *MockSubscriberOption_configureSubscriberConfig_Call {
	return &MockSubscriberOption_configureSubscriberConfig_Call{Call: _e.mock.On("configureSubscriberConfig", subscriberConfig)}
}

func (_c *MockSubscriberOption_configureSubscriberConfig_Call) Run(run func(subscriberConfig *SubscriberConfig)) *MockSubscriberOption_configureSubscriberConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *SubscriberConfig
		if args[0] != nil {
			arg0 = args[0].(*SubscriberConfig)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSubscriberOption_configureSubscriberConfig_Call) Return() *MockSubscriberOption_configureSubscriberConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSubscriberOption_configureSubscriberConfig_Call) RunAndReturn(run func(subscriberConfig *SubscriberConfig)) *MockSubscriberOption_configureSubscriberConfig_Call {
	_c.Run(run)
	return _c
}
