// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMallRepository creates a new instance of MockMallRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMallRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMallRepository {
	mock := &MockMallRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMallRepository is an autogenerated mock type for the MallRepository type
type MockMallRepository struct {
	mock.Mock
}

type MockMallRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMallRepository) EXPECT() *MockMallRepository_Expecter {
	return &MockMallRepository_Expecter{mock: &_m.Mock}
}

// AddStore provides a mock function for the type MockMallRepository
func (_mock *MockMallRepository) AddStore(ctx context.Context, storeID string, name string, location string) error {
	ret := _mock.Called(ctx, storeID, name, location)

	if len(ret) == 0 {
		panic("no return value specified for AddStore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, storeID, name, location)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMallRepository_AddStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddStore'
type MockMallRepository_AddStore_Call struct {
	*mock.Call
}

// AddStore is a helper method to define mock.On call
//   - ctx context.Context
//   - storeID string
//   - name string
//   - location string
func (_e *MockMallRepository_Expecter) AddStore(ctx interface{}, storeID interface{}, name interface{}, location interface{}) *MockMallRepository_AddStore_Call {
	return &MockMallRepository_AddStore_Call{Call: _e.mock.On("AddStore", ctx, storeID, name, location)}
}

func (_c *MockMallRepository_AddStore_Call) Run(run func(ctx context.Context, storeID string, name string, location string)) *MockMallRepository_AddStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMallRepository_AddStore_Call) Return(err error) *MockMallRepository_AddStore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMallRepository_AddStore_Call) RunAndReturn(run func(ctx context.Context, storeID string, name string, location string) error) *MockMallRepository_AddStore_Call {
	_c.Call.Return(run)
	return _c
}

// All provides a mock function for the type MockMallRepository
func (_mock *MockMallRepository) All(ctx context.Context) ([]*MallStore, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []*MallStore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*MallStore, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*MallStore); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*MallStore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMallRepository_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockMallRepository_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMallRepository_Expecter) All(ctx interface{}) *MockMallRepository_All_Call {
	return &MockMallRepository_All_Call{Call: _e.mock.On("All", ctx)}
}

func (_c *MockMallRepository_All_Call) Run(run func(ctx context.Context)) *MockMallRepository_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMallRepository_All_Call) Return(mallStores []*MallStore, err error) *MockMallRepository_All_Call {
	_c.Call.Return(mallStores, err)
	return _c
}

func (_c *MockMallRepository_All_Call) RunAndReturn(run func(ctx context.Context) ([]*MallStore, error)) *MockMallRepository_All_Call {
	_c.Call.Return(run)
	return _c
}

// AllParticipating provides a mock function for the type MockMallRepository
func (_mock *MockMallRepository) AllParticipating(ctx context.Context) ([]*MallStore, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllParticipating")
	}

	var r0 []*MallStore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) ([]*MallStore, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) []*MallStore); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*MallStore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMallRepository_AllParticipating_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllParticipating'
type MockMallRepository_AllParticipating_Call struct {
	*mock.Call
}

// AllParticipating is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockMallRepository_Expecter) AllParticipating(ctx interface{}) *MockMallRepository_AllParticipating_Call {
	return &MockMallRepository_AllParticipating_Call{Call: _e.mock.On("AllParticipating", ctx)}
}

func (_c *MockMallRepository_AllParticipating_Call) Run(run func(ctx context.Context)) *MockMallRepository_AllParticipating_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMallRepository_AllParticipating_Call) Return(mallStores []*MallStore, err error) *MockMallRepository_AllParticipating_Call {
	_c.Call.Return(mallStores, err)
	return _c
}

func (_c *MockMallRepository_AllParticipating_Call) RunAndReturn(run func(ctx context.Context) ([]*MallStore, error)) *MockMallRepository_AllParticipating_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockMallRepository
func (_mock *MockMallRepository) Find(ctx context.Context, storeID string) (*MallStore, error) {
	ret := _mock.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *MallStore
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*MallStore, error)); ok {
		return returnFunc(ctx, storeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *MallStore); ok {
		r0 = returnFunc(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*MallStore)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMallRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockMallRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - storeID string
func (_e *MockMallRepository_Expecter) Find(ctx interface{}, storeID interface{}) *MockMallRepository_Find_Call {
	return &MockMallRepository_Find_Call{Call: _e.mock.On("Find", ctx, storeID)}
}

func (_c *MockMallRepository_Find_Call) Run(run func(ctx context.Context, storeID string)) *MockMallRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMallRepository_Find_Call) Return(mallStore *MallStore, err error) *MockMallRepository_Find_Call {
	_c.Call.Return(mallStore, err)
	return _c
}

func (_c *MockMallRepository_Find_Call) RunAndReturn(run func(ctx context.Context, storeID string) (*MallStore, error)) *MockMallRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// RenameStore provides a mock function for the type MockMallRepository
func (_mock *MockMallRepository) RenameStore(ctx context.Context, storeID string, name string) error {
	ret := _mock.Called(ctx, storeID, name)

	if len(ret) == 0 {
		panic("no return value specified for RenameStore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, storeID, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMallRepository_RenameStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RenameStore'
type MockMallRepository_RenameStore_Call struct {
	*mock.Call
}

// RenameStore is a helper method to define mock.On call
//   - ctx context.Context
//   - storeID string
//   - name string
func (_e *MockMallRepository_Expecter) RenameStore(ctx interface{}, storeID interface{}, name interface{}) *MockMallRepository_RenameStore_Call {
	return &MockMallRepository_RenameStore_Call{Call: _e.mock.On("RenameStore", ctx, storeID, name)}
}

func (_c *MockMallRepository_RenameStore_Call) Run(run func(ctx context.Context, storeID string, name string)) *MockMallRepository_RenameStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMallRepository_RenameStore_Call) Return(err error) *MockMallRepository_RenameStore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMallRepository_RenameStore_Call) RunAndReturn(run func(ctx context.Context, storeID string, name string) error) *MockMallRepository_RenameStore_Call {
	_c.Call.Return(run)
	return _c
}

// SetStoreParticipation provides a mock function for the type MockMallRepository
func (_mock *MockMallRepository) SetStoreParticipation(ctx context.Context, storeID string, participating bool) error {
	ret := _mock.Called(ctx, storeID, participating)

	if len(ret) == 0 {
		panic("no return value specified for SetStoreParticipation")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) error); ok {
		r0 = returnFunc(ctx, storeID, participating)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMallRepository_SetStoreParticipation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetStoreParticipation'
type MockMallRepository_SetStoreParticipation_Call struct {
	*mock.Call
}

// SetStoreParticipation is a helper method to define mock.On call
//   - ctx context.Context
//   - storeID string
//   - participating bool
func (_e *MockMallRepository_Expecter) SetStoreParticipation(ctx interface{}, storeID interface{}, participating interface{}) *MockMallRepository_SetStoreParticipation_Call {
	return &MockMallRepository_SetStoreParticipation_Call{Call: _e.mock.On("SetStoreParticipation", ctx, storeID, participating)}
}

func (_c *MockMallRepository_SetStoreParticipation_Call) Run(run func(ctx context.Context, storeID string, participating bool)) *MockMallRepository_SetStoreParticipation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMallRepository_SetStoreParticipation_Call) Return(err error) *MockMallRepository_SetStoreParticipation_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMallRepository_SetStoreParticipation_Call) RunAndReturn(run func(ctx context.Context, storeID string, participating bool) error) *MockMallRepository_SetStoreParticipation_Call {
	_c.Call.Return(run)
	return _c
}
