// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockBasketRepository creates a new instance of MockBasketRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBasketRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBasketRepository {
	mock := &MockBasketRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBasketRepository is an autogenerated mock type for the BasketRepository type
type MockBasketRepository struct {
	mock.Mock
}

type MockBasketRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBasketRepository) EXPECT() *MockBasketRepository_Expecter {
	return &MockBasketRepository_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockBasketRepository
func (_mock *MockBasketRepository) Load(ctx context.Context, basketID string) (*Basket, error) {
	ret := _mock.Called(ctx, basketID)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *Basket
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Basket, error)); ok {
		return returnFunc(ctx, basketID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Basket); ok {
		r0 = returnFunc(ctx, basketID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Basket)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, basketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBasketRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockBasketRepository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - basketID string
func (_e *MockBasketRepository_Expecter) Load(ctx interface{}, basketID interface{}) *MockBasketRepository_Load_Call {
	return &MockBasketRepository_Load_Call{Call: _e.mock.On("Load", ctx, basketID)}
}

func (_c *MockBasketRepository_Load_Call) Run(run func(ctx context.Context, basketID string)) *MockBasketRepository_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBasketRepository_Load_Call) Return(basket *Basket, err error) *MockBasketRepository_Load_Call {
	_c.Call.Return(basket, err)
	return _c
}

func (_c *MockBasketRepository_Load_Call) RunAndReturn(run func(ctx context.Context, basketID string) (*Basket, error)) *MockBasketRepository_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockBasketRepository
func (_mock *MockBasketRepository) Save(ctx context.Context, basket *Basket) error {
	ret := _mock.Called(ctx, basket)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Basket) error); ok {
		r0 = returnFunc(ctx, basket)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBasketRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockBasketRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - basket *Basket
func (_e *MockBasketRepository_Expecter) Save(ctx interface{}, basket interface{}) *MockBasketRepository_Save_Call {
	return &MockBasketRepository_Save_Call{Call: _e.mock.On("Save", ctx, basket)}
}

func (_c *MockBasketRepository_Save_Call) Run(run func(ctx context.Context, basket *Basket)) *MockBasketRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Basket
		if args[1] != nil {
			arg1 = args[1].(*Basket)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBasketRepository_Save_Call) Return(err error) *MockBasketRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBasketRepository_Save_Call) RunAndReturn(run func(ctx context.Context, basket *Basket) error) *MockBasketRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
