// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStoreCacheRepository creates a new instance of MockStoreCacheRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoreCacheRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoreCacheRepository {
	mock := &MockStoreCacheRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStoreCacheRepository is an autogenerated mock type for the StoreCacheRepository type
type MockStoreCacheRepository struct {
	mock.Mock
}

type MockStoreCacheRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoreCacheRepository) EXPECT() *MockStoreCacheRepository_Expecter {
	return &MockStoreCacheRepository_Expecter{mock: &_m.Mock}
}

// Add provides a mock function for the type MockStoreCacheRepository
func (_mock *MockStoreCacheRepository) Add(ctx context.Context, storeID string, name string) error {
	ret := _mock.Called(ctx, storeID, name)

	if len(ret) == 0 {
		panic("no return value specified for Add")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, storeID, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoreCacheRepository_Add_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Add'
type MockStoreCacheRepository_Add_Call struct {
	*mock.Call
}

// Add is a helper method to define mock.On call
//   - ctx context.Context
//   - storeID string
//   - name string
func (_e *MockStoreCacheRepository_Expecter) Add(ctx interface{}, storeID interface{}, name interface{}) *MockStoreCacheRepository_Add_Call {
	return &MockStoreCacheRepository_Add_Call{Call: _e.mock.On("Add", ctx, storeID, name)}
}

func (_c *MockStoreCacheRepository_Add_Call) Run(run func(ctx context.Context, storeID string, name string)) *MockStoreCacheRepository_Add_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStoreCacheRepository_Add_Call) Return(err error) *MockStoreCacheRepository_Add_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoreCacheRepository_Add_Call) RunAndReturn(run func(ctx context.Context, storeID string, name string) error) *MockStoreCacheRepository_Add_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function for the type MockStoreCacheRepository
func (_mock *MockStoreCacheRepository) Find(ctx context.Context, storeID string) (*Store, error) {
	ret := _mock.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *Store
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Store, error)); ok {
		return returnFunc(ctx, storeID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Store); ok {
		r0 = returnFunc(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Store)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStoreCacheRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockStoreCacheRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - storeID string
func (_e *MockStoreCacheRepository_Expecter) Find(ctx interface{}, storeID interface{}) *MockStoreCacheRepository_Find_Call {
	return &MockStoreCacheRepository_Find_Call{Call: _e.mock.On("Find", ctx, storeID)}
}

func (_c *MockStoreCacheRepository_Find_Call) Run(run func(ctx context.Context, storeID string)) *MockStoreCacheRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStoreCacheRepository_Find_Call) Return(store *Store, err error) *MockStoreCacheRepository_Find_Call {
	_c.Call.Return(store, err)
	return _c
}

func (_c *MockStoreCacheRepository_Find_Call) RunAndReturn(run func(ctx context.Context, storeID string) (*Store, error)) *MockStoreCacheRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type MockStoreCacheRepository
func (_mock *MockStoreCacheRepository) Rename(ctx context.Context, storeID string, name string) error {
	ret := _mock.Called(ctx, storeID, name)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, storeID, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStoreCacheRepository_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type MockStoreCacheRepository_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - ctx context.Context
//   - storeID string
//   - name string
func (_e *MockStoreCacheRepository_Expecter) Rename(ctx interface{}, storeID interface{}, name interface{}) *MockStoreCacheRepository_Rename_Call {
	return &MockStoreCacheRepository_Rename_Call{Call: _e.mock.On("Rename", ctx, storeID, name)}
}

func (_c *MockStoreCacheRepository_Rename_Call) Run(run func(ctx context.Context, storeID string, name string)) *MockStoreCacheRepository_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStoreCacheRepository_Rename_Call) Return(err error) *MockStoreCacheRepository_Rename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStoreCacheRepository_Rename_Call) RunAndReturn(run func(ctx context.Context, storeID string, name string) error) *MockStoreCacheRepository_Rename_Call {
	_c.Call.Return(run)
	return _c
}
