// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package registry

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRegistrable creates a new instance of MockRegistrable. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistrable(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistrable {
	mock := &MockRegistrable{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistrable is an autogenerated mock type for the Registrable type
type MockRegistrable struct {
	mock.Mock
}

type MockRegistrable_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistrable) EXPECT() *MockRegistrable_Expecter {
	return &MockRegistrable_Expecter{mock: &_m.Mock}
}

// Key provides a mock function for the type MockRegistrable
func (_mock *MockRegistrable) Key() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Key")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockRegistrable_Key_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Key'
type MockRegistrable_Key_Call struct {
	*mock.Call
}

// Key is a helper method to define mock.On call
func (_e *MockRegistrable_Expecter) Key() *MockRegistrable_Key_Call {
	return &MockRegistrable_Key_Call{Call: _e.mock.On("Key")}
}

func (_c *MockRegistrable_Key_Call) Run(run func()) *MockRegistrable_Key_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistrable_Key_Call) Return(s string) *MockRegistrable_Key_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockRegistrable_Key_Call) RunAndReturn(run func() string) *MockRegistrable_Key_Call {
	_c.Call.Return(run)
	return _c
}
