// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package registry

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockRegistry creates a new instance of MockRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistry {
	mock := &MockRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistry is an autogenerated mock type for the Registry type
type MockRegistry struct {
	mock.Mock
}

type MockRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistry) EXPECT() *MockRegistry_Expecter {
	return &MockRegistry_Expecter{mock: &_m.Mock}
}

// Build provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Build(key string, options ...BuildOption) (interface{}, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(key, options)
	} else {
		tmpRet = _mock.Called(key)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Build")
	}

	var r0 interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...BuildOption) (interface{}, error)); ok {
		return returnFunc(key, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...BuildOption) interface{}); ok {
		r0 = returnFunc(key, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...BuildOption) error); ok {
		r1 = returnFunc(key, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistry_Build_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Build'
type MockRegistry_Build_Call struct {
	*mock.Call
}

// Build is a helper method to define mock.On call
//   - key string
//   - options ...BuildOption
func (_e *MockRegistry_Expecter) Build(key interface{}, options ...interface{}) *MockRegistry_Build_Call {
	return &MockRegistry_Build_Call{Call: _e.mock.On("Build",
		append([]interface{}{key}, options...)...)}
}

func (_c *MockRegistry_Build_Call) Run(run func(key string, options ...BuildOption)) *MockRegistry_Build_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []BuildOption
		var variadicArgs []BuildOption
		if len(args) > 1 {
			variadicArgs = args[1].([]BuildOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockRegistry_Build_Call) Return(ifaceVal interface{}, err error) *MockRegistry_Build_Call {
	_c.Call.Return(ifaceVal, err)
	return _c
}

func (_c *MockRegistry_Build_Call) RunAndReturn(run func(key string, options ...BuildOption) (interface{}, error)) *MockRegistry_Build_Call {
	_c.Call.Return(run)
	return _c
}

// Deserialize provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Deserialize(key string, data []byte, options ...BuildOption) (interface{}, error) {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(key, data, options)
	} else {
		tmpRet = _mock.Called(key, data)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Deserialize")
	}

	var r0 interface{}
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, ...BuildOption) (interface{}, error)); ok {
		return returnFunc(key, data, options...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, []byte, ...BuildOption) interface{}); ok {
		r0 = returnFunc(key, data, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, []byte, ...BuildOption) error); ok {
		r1 = returnFunc(key, data, options...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistry_Deserialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deserialize'
type MockRegistry_Deserialize_Call struct {
	*mock.Call
}

// Deserialize is a helper method to define mock.On call
//   - key string
//   - data []byte
//   - options ...BuildOption
func (_e *MockRegistry_Expecter) Deserialize(key interface{}, data interface{}, options ...interface{}) *MockRegistry_Deserialize_Call {
	return &MockRegistry_Deserialize_Call{Call: _e.mock.On("Deserialize",
		append([]interface{}{key, data}, options...)...)}
}

func (_c *MockRegistry_Deserialize_Call) Run(run func(key string, data []byte, options ...BuildOption)) *MockRegistry_Deserialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []byte
		if args[1] != nil {
			arg1 = args[1].([]byte)
		}
		var arg2 []BuildOption
		var variadicArgs []BuildOption
		if len(args) > 2 {
			variadicArgs = args[2].([]BuildOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockRegistry_Deserialize_Call) Return(ifaceVal interface{}, err error) *MockRegistry_Deserialize_Call {
	_c.Call.Return(ifaceVal, err)
	return _c
}

func (_c *MockRegistry_Deserialize_Call) RunAndReturn(run func(key string, data []byte, options ...BuildOption) (interface{}, error)) *MockRegistry_Deserialize_Call {
	_c.Call.Return(run)
	return _c
}

// Serialize provides a mock function for the type MockRegistry
func (_mock *MockRegistry) Serialize(key string, v interface{}) ([]byte, error) {
	ret := _mock.Called(key, v)

	if len(ret) == 0 {
		panic("no return value specified for Serialize")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}) ([]byte, error)); ok {
		return returnFunc(key, v)
	}
	if returnFunc, ok := ret.Get(0).(func(string, interface{}) []byte); ok {
		r0 = returnFunc(key, v)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, interface{}) error); ok {
		r1 = returnFunc(key, v)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistry_Serialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Serialize'
type MockRegistry_Serialize_Call struct {
	*mock.Call
}

// Serialize is a helper method to define mock.On call
//   - key string
//   - v interface{}
func (_e *MockRegistry_Expecter) Serialize(key interface{}, v interface{}) *MockRegistry_Serialize_Call {
	return &MockRegistry_Serialize_Call{Call: _e.mock.On("Serialize", key, v)}
}

func (_c *MockRegistry_Serialize_Call) Run(run func(key string, v interface{})) *MockRegistry_Serialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRegistry_Serialize_Call) Return(bytes []byte, err error) *MockRegistry_Serialize_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockRegistry_Serialize_Call) RunAndReturn(run func(key string, v interface{}) ([]byte, error)) *MockRegistry_Serialize_Call {
	_c.Call.Return(run)
	return _c
}

// register provides a mock function for the type MockRegistry
func (_mock *MockRegistry) register(key string, fn func() interface{}, s Serializer, d Deserializer, o []BuildOption) error {
	ret := _mock.Called(key, fn, s, d, o)

	if len(ret) == 0 {
		panic("no return value specified for register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, func() interface{}, Serializer, Deserializer, []BuildOption) error); ok {
		r0 = returnFunc(key, fn, s, d, o)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRegistry_register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'register'
type MockRegistry_register_Call struct {
	*mock.Call
}

// register is a helper method to define mock.On call
//   - key string
//   - fn func() interface{}
//   - s Serializer
//   - d Deserializer
//   - o []BuildOption
func (_e *MockRegistry_Expecter) register(key interface{}, fn interface{}, s interface{}, d interface{}, o interface{}) *MockRegistry_register_Call {
	return &MockRegistry_register_Call{Call: _e.mock.On("register", key, fn, s, d, o)}
}

func (_c *MockRegistry_register_Call) Run(run func(key string, fn func() interface{}, s Serializer, d Deserializer, o []BuildOption)) *MockRegistry_register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func() interface{}
		if args[1] != nil {
			arg1 = args[1].(func() interface{})
		}
		var arg2 Serializer
		if args[2] != nil {
			arg2 = args[2].(Serializer)
		}
		var arg3 Deserializer
		if args[3] != nil {
			arg3 = args[3].(Deserializer)
		}
		var arg4 []BuildOption
		if args[4] != nil {
			arg4 = args[4].([]BuildOption)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRegistry_register_Call) Return(err error) *MockRegistry_register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistry_register_Call) RunAndReturn(run func(key string, fn func() interface{}, s Serializer, d Deserializer, o []BuildOption) error) *MockRegistry_register_Call {
	_c.Call.Return(run)
	return _c
}
