// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package registry

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSerde creates a new instance of MockSerde. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSerde(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSerde {
	mock := &MockSerde{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSerde is an autogenerated mock type for the Serde type
type MockSerde struct {
	mock.Mock
}

type MockSerde_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSerde) EXPECT() *MockSerde_Expecter {
	return &MockSerde_Expecter{mock: &_m.Mock}
}

// Register provides a mock function for the type MockSerde
func (_mock *MockSerde) Register(v Registrable, options ...BuildOption) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(v, options)
	} else {
		tmpRet = _mock.Called(v)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Registrable, ...BuildOption) error); ok {
		r0 = returnFunc(v, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSerde_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockSerde_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - v Registrable
//   - options ...BuildOption
func (_e *MockSerde_Expecter) Register(v interface{}, options ...interface{}) *MockSerde_Register_Call {
	return &MockSerde_Register_Call{Call: _e.mock.On("Register",
		append([]interface{}{v}, options...)...)}
}

func (_c *MockSerde_Register_Call) Run(run func(v Registrable, options ...BuildOption)) *MockSerde_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Registrable
		if args[0] != nil {
			arg0 = args[0].(Registrable)
		}
		var arg1 []BuildOption
		var variadicArgs []BuildOption
		if len(args) > 1 {
			variadicArgs = args[1].([]BuildOption)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockSerde_Register_Call) Return(err error) *MockSerde_Register_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSerde_Register_Call) RunAndReturn(run func(v Registrable, options ...BuildOption) error) *MockSerde_Register_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterFactory provides a mock function for the type MockSerde
func (_mock *MockSerde) RegisterFactory(key string, fn func() interface{}, options ...BuildOption) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(key, fn, options)
	} else {
		tmpRet = _mock.Called(key, fn)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RegisterFactory")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, func() interface{}, ...BuildOption) error); ok {
		r0 = returnFunc(key, fn, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSerde_RegisterFactory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterFactory'
type MockSerde_RegisterFactory_Call struct {
	*mock.Call
}

// RegisterFactory is a helper method to define mock.On call
//   - key string
//   - fn func() interface{}
//   - options ...BuildOption
func (_e *MockSerde_Expecter) RegisterFactory(key interface{}, fn interface{}, options ...interface{}) *MockSerde_RegisterFactory_Call {
	return &MockSerde_RegisterFactory_Call{Call: _e.mock.On("RegisterFactory",
		append([]interface{}{key, fn}, options...)...)}
}

func (_c *MockSerde_RegisterFactory_Call) Run(run func(key string, fn func() interface{}, options ...BuildOption)) *MockSerde_RegisterFactory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func() interface{}
		if args[1] != nil {
			arg1 = args[1].(func() interface{})
		}
		var arg2 []BuildOption
		var variadicArgs []BuildOption
		if len(args) > 2 {
			variadicArgs = args[2].([]BuildOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSerde_RegisterFactory_Call) Return(err error) *MockSerde_RegisterFactory_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSerde_RegisterFactory_Call) RunAndReturn(run func(key string, fn func() interface{}, options ...BuildOption) error) *MockSerde_RegisterFactory_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterKey provides a mock function for the type MockSerde
func (_mock *MockSerde) RegisterKey(key string, v interface{}, options ...BuildOption) error {
	var tmpRet mock.Arguments
	if len(options) > 0 {
		tmpRet = _mock.Called(key, v, options)
	} else {
		tmpRet = _mock.Called(key, v)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RegisterKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, interface{}, ...BuildOption) error); ok {
		r0 = returnFunc(key, v, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSerde_RegisterKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterKey'
type MockSerde_RegisterKey_Call struct {
	*mock.Call
}

// RegisterKey is a helper method to define mock.On call
//   - key string
//   - v interface{}
//   - options ...BuildOption
func (_e *MockSerde_Expecter) RegisterKey(key interface{}, v interface{}, options ...interface{}) *MockSerde_RegisterKey_Call {
	return &MockSerde_RegisterKey_Call{Call: _e.mock.On("RegisterKey",
		append([]interface{}{key, v}, options...)...)}
}

func (_c *MockSerde_RegisterKey_Call) Run(run func(key string, v interface{}, options ...BuildOption)) *MockSerde_RegisterKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 interface{}
		if args[1] != nil {
			arg1 = args[1].(interface{})
		}
		var arg2 []BuildOption
		var variadicArgs []BuildOption
		if len(args) > 2 {
			variadicArgs = args[2].([]BuildOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSerde_RegisterKey_Call) Return(err error) *MockSerde_RegisterKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSerde_RegisterKey_Call) RunAndReturn(run func(key string, v interface{}, options ...BuildOption) error) *MockSerde_RegisterKey_Call {
	_c.Call.Return(run)
	return _c
}
