// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockProductRepository
func (_mock *MockProductRepository) Find(ctx context.Context, productID string) (*Product, error) {
	ret := _mock.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *Product
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Product, error)); ok {
		return returnFunc(ctx, productID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Product); ok {
		r0 = returnFunc(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Product)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProductRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockProductRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
func (_e *MockProductRepository_Expecter) Find(ctx interface{}, productID interface{}) *MockProductRepository_Find_Call {
	return &MockProductRepository_Find_Call{Call: _e.mock.On("Find", ctx, productID)}
}

func (_c *MockProductRepository_Find_Call) Run(run func(ctx context.Context, productID string)) *MockProductRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProductRepository_Find_Call) Return(product *Product, err error) *MockProductRepository_Find_Call {
	_c.Call.Return(product, err)
	return _c
}

func (_c *MockProductRepository_Find_Call) RunAndReturn(run func(ctx context.Context, productID string) (*Product, error)) *MockProductRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}
