// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockShoppingListRepository creates a new instance of MockShoppingListRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShoppingListRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShoppingListRepository {
	mock := &MockShoppingListRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShoppingListRepository is an autogenerated mock type for the ShoppingListRepository type
type MockShoppingListRepository struct {
	mock.Mock
}

type MockShoppingListRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShoppingListRepository) EXPECT() *MockShoppingListRepository_Expecter {
	return &MockShoppingListRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function for the type MockShoppingListRepository
func (_mock *MockShoppingListRepository) Find(ctx context.Context, shoppingListID string) (*ShoppingList, error) {
	ret := _mock.Called(ctx, shoppingListID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *ShoppingList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*ShoppingList, error)); ok {
		return returnFunc(ctx, shoppingListID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *ShoppingList); ok {
		r0 = returnFunc(ctx, shoppingListID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ShoppingList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, shoppingListID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShoppingListRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockShoppingListRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - shoppingListID string
func (_e *MockShoppingListRepository_Expecter) Find(ctx interface{}, shoppingListID interface{}) *MockShoppingListRepository_Find_Call {
	return &MockShoppingListRepository_Find_Call{Call: _e.mock.On("Find", ctx, shoppingListID)}
}

func (_c *MockShoppingListRepository_Find_Call) Run(run func(ctx context.Context, shoppingListID string)) *MockShoppingListRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShoppingListRepository_Find_Call) Return(shoppingList *ShoppingList, err error) *MockShoppingListRepository_Find_Call {
	_c.Call.Return(shoppingList, err)
	return _c
}

func (_c *MockShoppingListRepository_Find_Call) RunAndReturn(run func(ctx context.Context, shoppingListID string) (*ShoppingList, error)) *MockShoppingListRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockShoppingListRepository
func (_mock *MockShoppingListRepository) Save(ctx context.Context, list *ShoppingList) error {
	ret := _mock.Called(ctx, list)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ShoppingList) error); ok {
		r0 = returnFunc(ctx, list)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShoppingListRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockShoppingListRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - list *ShoppingList
func (_e *MockShoppingListRepository_Expecter) Save(ctx interface{}, list interface{}) *MockShoppingListRepository_Save_Call {
	return &MockShoppingListRepository_Save_Call{Call: _e.mock.On("Save", ctx, list)}
}

func (_c *MockShoppingListRepository_Save_Call) Run(run func(ctx context.Context, list *ShoppingList)) *MockShoppingListRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ShoppingList
		if args[1] != nil {
			arg1 = args[1].(*ShoppingList)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShoppingListRepository_Save_Call) Return(err error) *MockShoppingListRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShoppingListRepository_Save_Call) RunAndReturn(run func(ctx context.Context, list *ShoppingList) error) *MockShoppingListRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockShoppingListRepository
func (_mock *MockShoppingListRepository) Update(ctx context.Context, list *ShoppingList) error {
	ret := _mock.Called(ctx, list)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ShoppingList) error); ok {
		r0 = returnFunc(ctx, list)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShoppingListRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockShoppingListRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - list *ShoppingList
func (_e *MockShoppingListRepository_Expecter) Update(ctx interface{}, list interface{}) *MockShoppingListRepository_Update_Call {
	return &MockShoppingListRepository_Update_Call{Call: _e.mock.On("Update", ctx, list)}
}

func (_c *MockShoppingListRepository_Update_Call) Run(run func(ctx context.Context, list *ShoppingList)) *MockShoppingListRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ShoppingList
		if args[1] != nil {
			arg1 = args[1].(*ShoppingList)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShoppingListRepository_Update_Call) Return(err error) *MockShoppingListRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShoppingListRepository_Update_Call) RunAndReturn(run func(ctx context.Context, list *ShoppingList) error) *MockShoppingListRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
