// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandHandler creates a new instance of MockCommandHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandHandler[T Command](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandHandler[T] {
	mock := &MockCommandHandler[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandHandler is an autogenerated mock type for the CommandHandler type
type MockCommandHandler[T Command] struct {
	mock.Mock
}

type MockCommandHandler_Expecter[T Command] struct {
	mock *mock.Mock
}

func (_m *MockCommandHandler[T]) EXPECT() *MockCommandHandler_Expecter[T] {
	return &MockCommandHandler_Expecter[T]{mock: &_m.Mock}
}

// HandleCommand provides a mock function for the type MockCommandHandler
func (_mock *MockCommandHandler[T]) HandleCommand(ctx context.Context, cmd T) (Reply, error) {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for HandleCommand")
	}

	var r0 Reply
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) (Reply, error)); ok {
		return returnFunc(ctx, cmd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, T) Reply); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Reply)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = returnFunc(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommandHandler_HandleCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCommand'
type MockCommandHandler_HandleCommand_Call[T Command] struct {
	*mock.Call
}

// HandleCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd T
func (_e *MockCommandHandler_Expecter[T]) HandleCommand(ctx interface{}, cmd interface{}) *MockCommandHandler_HandleCommand_Call[T] {
	return &MockCommandHandler_HandleCommand_Call[T]{Call: _e.mock.On("HandleCommand", ctx, cmd)}
}

func (_c *MockCommandHandler_HandleCommand_Call[T]) Run(run func(ctx context.Context, cmd T)) *MockCommandHandler_HandleCommand_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 T
		if args[1] != nil {
			arg1 = args[1].(T)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCommandHandler_HandleCommand_Call[T]) Return(reply Reply, err error) *MockCommandHandler_HandleCommand_Call[T] {
	_c.Call.Return(reply, err)
	return _c
}

func (_c *MockCommandHandler_HandleCommand_Call[T]) RunAndReturn(run func(ctx context.Context, cmd T) (Reply, error)) *MockCommandHandler_HandleCommand_Call[T] {
	_c.Call.Return(run)
	return _c
}
