// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandOption creates a new instance of MockCommandOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandOption {
	mock := &MockCommandOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandOption is an autogenerated mock type for the CommandOption type
type MockCommandOption struct {
	mock.Mock
}

type MockCommandOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandOption) EXPECT() *MockCommandOption_Expecter {
	return &MockCommandOption_Expecter{mock: &_m.Mock}
}

// configureCommand provides a mock function for the type MockCommandOption
func (_mock *MockCommandOption) configureCommand(commandMoqParam *command) {
	_mock.Called(commandMoqParam)
	return
}

// MockCommandOption_configureCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'configureCommand'
type MockCommandOption_configureCommand_Call struct {
	*mock.Call
}

// configureCommand is a helper method to define mock.On call
//   - commandMoqParam *command
func (_e *MockCommandOption_Expecter) configureCommand(commandMoqParam interface{}) *MockCommandOption_configureCommand_Call {
	return &MockCommandOption_configureCommand_Call{Call: _e.mock.On("configureCommand", commandMoqParam)}
}

func (_c *MockCommandOption_configureCommand_Call) Run(run func(commandMoqParam *command)) *MockCommandOption_configureCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *command
		if args[0] != nil {
			arg0 = args[0].(*command)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockCommandOption_configureCommand_Call) Return() *MockCommandOption_configureCommand_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockCommandOption_configureCommand_Call) RunAndReturn(run func(commandMoqParam *command)) *MockCommandOption_configureCommand_Call {
	_c.Run(run)
	return _c
}
