// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCommandPayload creates a new instance of MockCommandPayload. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandPayload(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandPayload {
	mock := &MockCommandPayload{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandPayload is an autogenerated mock type for the CommandPayload type
type MockCommandPayload struct {
	mock.Mock
}

type MockCommandPayload_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandPayload) EXPECT() *MockCommandPayload_Expecter {
	return &MockCommandPayload_Expecter{mock: &_m.Mock}
}
