// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockReply creates a new instance of MockReply. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReply(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReply {
	mock := &MockReply{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReply is an autogenerated mock type for the Reply type
type MockReply struct {
	mock.Mock
}

type MockReply_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReply) EXPECT() *MockReply_Expecter {
	return &MockReply_Expecter{mock: &_m.Mock}
}

// ID provides a mock function for the type MockReply
func (_mock *MockReply) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReply_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockReply_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockReply_Expecter) ID() *MockReply_ID_Call {
	return &MockReply_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockReply_ID_Call) Run(run func()) *MockReply_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReply_ID_Call) Return(s string) *MockReply_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReply_ID_Call) RunAndReturn(run func() string) *MockReply_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Metadata provides a mock function for the type MockReply
func (_mock *MockReply) Metadata() Metadata {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Metadata")
	}

	var r0 Metadata
	if returnFunc, ok := ret.Get(0).(func() Metadata); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Metadata)
		}
	}
	return r0
}

// MockReply_Metadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Metadata'
type MockReply_Metadata_Call struct {
	*mock.Call
}

// Metadata is a helper method to define mock.On call
func (_e *MockReply_Expecter) Metadata() *MockReply_Metadata_Call {
	return &MockReply_Metadata_Call{Call: _e.mock.On("Metadata")}
}

func (_c *MockReply_Metadata_Call) Run(run func()) *MockReply_Metadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReply_Metadata_Call) Return(metadata Metadata) *MockReply_Metadata_Call {
	_c.Call.Return(metadata)
	return _c
}

func (_c *MockReply_Metadata_Call) RunAndReturn(run func() Metadata) *MockReply_Metadata_Call {
	_c.Call.Return(run)
	return _c
}

// OccurredAt provides a mock function for the type MockReply
func (_mock *MockReply) OccurredAt() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for OccurredAt")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// MockReply_OccurredAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OccurredAt'
type MockReply_OccurredAt_Call struct {
	*mock.Call
}

// OccurredAt is a helper method to define mock.On call
func (_e *MockReply_Expecter) OccurredAt() *MockReply_OccurredAt_Call {
	return &MockReply_OccurredAt_Call{Call: _e.mock.On("OccurredAt")}
}

func (_c *MockReply_OccurredAt_Call) Run(run func()) *MockReply_OccurredAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReply_OccurredAt_Call) Return(time1 time.Time) *MockReply_OccurredAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *MockReply_OccurredAt_Call) RunAndReturn(run func() time.Time) *MockReply_OccurredAt_Call {
	_c.Call.Return(run)
	return _c
}

// Payload provides a mock function for the type MockReply
func (_mock *MockReply) Payload() ReplyPayload {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Payload")
	}

	var r0 ReplyPayload
	if returnFunc, ok := ret.Get(0).(func() ReplyPayload); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ReplyPayload)
		}
	}
	return r0
}

// MockReply_Payload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Payload'
type MockReply_Payload_Call struct {
	*mock.Call
}

// Payload is a helper method to define mock.On call
func (_e *MockReply_Expecter) Payload() *MockReply_Payload_Call {
	return &MockReply_Payload_Call{Call: _e.mock.On("Payload")}
}

func (_c *MockReply_Payload_Call) Run(run func()) *MockReply_Payload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReply_Payload_Call) Return(replyPayload ReplyPayload) *MockReply_Payload_Call {
	_c.Call.Return(replyPayload)
	return _c
}

func (_c *MockReply_Payload_Call) RunAndReturn(run func() ReplyPayload) *MockReply_Payload_Call {
	_c.Call.Return(run)
	return _c
}

// ReplyName provides a mock function for the type MockReply
func (_mock *MockReply) ReplyName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReplyName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockReply_ReplyName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplyName'
type MockReply_ReplyName_Call struct {
	*mock.Call
}

// ReplyName is a helper method to define mock.On call
func (_e *MockReply_Expecter) ReplyName() *MockReply_ReplyName_Call {
	return &MockReply_ReplyName_Call{Call: _e.mock.On("ReplyName")}
}

func (_c *MockReply_ReplyName_Call) Run(run func()) *MockReply_ReplyName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReply_ReplyName_Call) Return(s string) *MockReply_ReplyName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockReply_ReplyName_Call) RunAndReturn(run func() string) *MockReply_ReplyName_Call {
	_c.Call.Return(run)
	return _c
}
