// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockReplyOption creates a new instance of MockReplyOption. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReplyOption(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReplyOption {
	mock := &MockReplyOption{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReplyOption is an autogenerated mock type for the ReplyOption type
type MockReplyOption struct {
	mock.Mock
}

type MockReplyOption_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReplyOption) EXPECT() *MockReplyOption_Expecter {
	return &MockReplyOption_Expecter{mock: &_m.Mock}
}

// configureReply provides a mock function for the type MockReplyOption
func (_mock *MockReplyOption) configureReply(replyMoqParam *reply) {
	_mock.Called(replyMoqParam)
	return
}

// MockReplyOption_configureReply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'configureReply'
type MockReplyOption_configureReply_Call struct {
	*mock.Call
}

// configureReply is a helper method to define mock.On call
//   - replyMoqParam *reply
func (_e *MockReplyOption_Expecter) configureReply(replyMoqParam interface{}) *MockReplyOption_configureReply_Call {
	return &MockReplyOption_configureReply_Call{Call: _e.mock.On("configureReply", replyMoqParam)}
}

func (_c *MockReplyOption_configureReply_Call) Run(run func(replyMoqParam *reply)) *MockReplyOption_configureReply_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *reply
		if args[0] != nil {
			arg0 = args[0].(*reply)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReplyOption_configureReply_Call) Return() *MockReplyOption_configureReply_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockReplyOption_configureReply_Call) RunAndReturn(run func(replyMoqParam *reply)) *MockReplyOption_configureReply_Call {
	_c.Run(run)
	return _c
}
