// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ddd

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockReplyPayload creates a new instance of MockReplyPayload. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReplyPayload(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReplyPayload {
	mock := &MockReplyPayload{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReplyPayload is an autogenerated mock type for the ReplyPayload type
type MockReplyPayload struct {
	mock.Mock
}

type MockReplyPayload_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReplyPayload) EXPECT() *MockReplyPayload_Expecter {
	return &MockReplyPayload_Expecter{mock: &_m.Mock}
}
