// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sec

import (
	"context"
	"eda-in-golang/internal/ddd"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrchestrator creates a new instance of MockOrchestrator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrchestrator[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrchestrator[T] {
	mock := &MockOrchestrator[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrchestrator is an autogenerated mock type for the Orchestrator type
type MockOrchestrator[T any] struct {
	mock.Mock
}

type MockOrchestrator_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockOrchestrator[T]) EXPECT() *MockOrchestrator_Expecter[T] {
	return &MockOrchestrator_Expecter[T]{mock: &_m.Mock}
}

// HandleReply provides a mock function for the type MockOrchestrator
func (_mock *MockOrchestrator[T]) HandleReply(ctx context.Context, reply ddd.Reply) error {
	ret := _mock.Called(ctx, reply)

	if len(ret) == 0 {
		panic("no return value specified for HandleReply")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ddd.Reply) error); ok {
		r0 = returnFunc(ctx, reply)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrchestrator_HandleReply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleReply'
type MockOrchestrator_HandleReply_Call[T any] struct {
	*mock.Call
}

// HandleReply is a helper method to define mock.On call
//   - ctx context.Context
//   - reply ddd.Reply
func (_e *MockOrchestrator_Expecter[T]) HandleReply(ctx interface{}, reply interface{}) *MockOrchestrator_HandleReply_Call[T] {
	return &MockOrchestrator_HandleReply_Call[T]{Call: _e.mock.On("HandleReply", ctx, reply)}
}

func (_c *MockOrchestrator_HandleReply_Call[T]) Run(run func(ctx context.Context, reply ddd.Reply)) *MockOrchestrator_HandleReply_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ddd.Reply
		if args[1] != nil {
			arg1 = args[1].(ddd.Reply)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrchestrator_HandleReply_Call[T]) Return(err error) *MockOrchestrator_HandleReply_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrchestrator_HandleReply_Call[T]) RunAndReturn(run func(ctx context.Context, reply ddd.Reply) error) *MockOrchestrator_HandleReply_Call[T] {
	_c.Call.Return(run)
	return _c
}

// ReplyTopic provides a mock function for the type MockOrchestrator
func (_mock *MockOrchestrator[T]) ReplyTopic() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReplyTopic")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockOrchestrator_ReplyTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplyTopic'
type MockOrchestrator_ReplyTopic_Call[T any] struct {
	*mock.Call
}

// ReplyTopic is a helper method to define mock.On call
func (_e *MockOrchestrator_Expecter[T]) ReplyTopic() *MockOrchestrator_ReplyTopic_Call[T] {
	return &MockOrchestrator_ReplyTopic_Call[T]{Call: _e.mock.On("ReplyTopic")}
}

func (_c *MockOrchestrator_ReplyTopic_Call[T]) Run(run func()) *MockOrchestrator_ReplyTopic_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrchestrator_ReplyTopic_Call[T]) Return(s string) *MockOrchestrator_ReplyTopic_Call[T] {
	_c.Call.Return(s)
	return _c
}

func (_c *MockOrchestrator_ReplyTopic_Call[T]) RunAndReturn(run func() string) *MockOrchestrator_ReplyTopic_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function for the type MockOrchestrator
func (_mock *MockOrchestrator[T]) Start(ctx context.Context, id string, data T) error {
	ret := _mock.Called(ctx, id, data)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, T) error); ok {
		r0 = returnFunc(ctx, id, data)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrchestrator_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockOrchestrator_Start_Call[T any] struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - data T
func (_e *MockOrchestrator_Expecter[T]) Start(ctx interface{}, id interface{}, data interface{}) *MockOrchestrator_Start_Call[T] {
	return &MockOrchestrator_Start_Call[T]{Call: _e.mock.On("Start", ctx, id, data)}
}

func (_c *MockOrchestrator_Start_Call[T]) Run(run func(ctx context.Context, id string, data T)) *MockOrchestrator_Start_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 T
		if args[2] != nil {
			arg2 = args[2].(T)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrchestrator_Start_Call[T]) Return(err error) *MockOrchestrator_Start_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrchestrator_Start_Call[T]) RunAndReturn(run func(ctx context.Context, id string, data T) error) *MockOrchestrator_Start_Call[T] {
	_c.Call.Return(run)
	return _c
}
