// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sec

import (
	"context"
	"eda-in-golang/internal/ddd"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSagaStep creates a new instance of MockSagaStep. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSagaStep[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSagaStep[T] {
	mock := &MockSagaStep[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSagaStep is an autogenerated mock type for the SagaStep type
type MockSagaStep[T any] struct {
	mock.Mock
}

type MockSagaStep_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockSagaStep[T]) EXPECT() *MockSagaStep_Expecter[T] {
	return &MockSagaStep_Expecter[T]{mock: &_m.Mock}
}

// Action provides a mock function for the type MockSagaStep
func (_mock *MockSagaStep[T]) Action(fn StepActionFunc[T]) SagaStep[T] {
	ret := _mock.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for Action")
	}

	var r0 SagaStep[T]
	if returnFunc, ok := ret.Get(0).(func(StepActionFunc[T]) SagaStep[T]); ok {
		r0 = returnFunc(fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SagaStep[T])
		}
	}
	return r0
}

// MockSagaStep_Action_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Action'
type MockSagaStep_Action_Call[T any] struct {
	*mock.Call
}

// Action is a helper method to define mock.On call
//   - fn StepActionFunc[T]
func (_e *MockSagaStep_Expecter[T]) Action(fn interface{}) *MockSagaStep_Action_Call[T] {
	return &MockSagaStep_Action_Call[T]{Call: _e.mock.On("Action", fn)}
}

func (_c *MockSagaStep_Action_Call[T]) Run(run func(fn StepActionFunc[T])) *MockSagaStep_Action_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 StepActionFunc[T]
		if args[0] != nil {
			arg0 = args[0].(StepActionFunc[T])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSagaStep_Action_Call[T]) Return(sagaStep SagaStep[T]) *MockSagaStep_Action_Call[T] {
	_c.Call.Return(sagaStep)
	return _c
}

func (_c *MockSagaStep_Action_Call[T]) RunAndReturn(run func(fn StepActionFunc[T]) SagaStep[T]) *MockSagaStep_Action_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Compensation provides a mock function for the type MockSagaStep
func (_mock *MockSagaStep[T]) Compensation(fn StepActionFunc[T]) SagaStep[T] {
	ret := _mock.Called(fn)

	if len(ret) == 0 {
		panic("no return value specified for Compensation")
	}

	var r0 SagaStep[T]
	if returnFunc, ok := ret.Get(0).(func(StepActionFunc[T]) SagaStep[T]); ok {
		r0 = returnFunc(fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SagaStep[T])
		}
	}
	return r0
}

// MockSagaStep_Compensation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compensation'
type MockSagaStep_Compensation_Call[T any] struct {
	*mock.Call
}

// Compensation is a helper method to define mock.On call
//   - fn StepActionFunc[T]
func (_e *MockSagaStep_Expecter[T]) Compensation(fn interface{}) *MockSagaStep_Compensation_Call[T] {
	return &MockSagaStep_Compensation_Call[T]{Call: _e.mock.On("Compensation", fn)}
}

func (_c *MockSagaStep_Compensation_Call[T]) Run(run func(fn StepActionFunc[T])) *MockSagaStep_Compensation_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 StepActionFunc[T]
		if args[0] != nil {
			arg0 = args[0].(StepActionFunc[T])
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSagaStep_Compensation_Call[T]) Return(sagaStep SagaStep[T]) *MockSagaStep_Compensation_Call[T] {
	_c.Call.Return(sagaStep)
	return _c
}

func (_c *MockSagaStep_Compensation_Call[T]) RunAndReturn(run func(fn StepActionFunc[T]) SagaStep[T]) *MockSagaStep_Compensation_Call[T] {
	_c.Call.Return(run)
	return _c
}

// OnActionReply provides a mock function for the type MockSagaStep
func (_mock *MockSagaStep[T]) OnActionReply(replyName string, fn StepReplyHandlerFunc[T]) SagaStep[T] {
	ret := _mock.Called(replyName, fn)

	if len(ret) == 0 {
		panic("no return value specified for OnActionReply")
	}

	var r0 SagaStep[T]
	if returnFunc, ok := ret.Get(0).(func(string, StepReplyHandlerFunc[T]) SagaStep[T]); ok {
		r0 = returnFunc(replyName, fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SagaStep[T])
		}
	}
	return r0
}

// MockSagaStep_OnActionReply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnActionReply'
type MockSagaStep_OnActionReply_Call[T any] struct {
	*mock.Call
}

// OnActionReply is a helper method to define mock.On call
//   - replyName string
//   - fn StepReplyHandlerFunc[T]
func (_e *MockSagaStep_Expecter[T]) OnActionReply(replyName interface{}, fn interface{}) *MockSagaStep_OnActionReply_Call[T] {
	return &MockSagaStep_OnActionReply_Call[T]{Call: _e.mock.On("OnActionReply", replyName, fn)}
}

func (_c *MockSagaStep_OnActionReply_Call[T]) Run(run func(replyName string, fn StepReplyHandlerFunc[T])) *MockSagaStep_OnActionReply_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 StepReplyHandlerFunc[T]
		if args[1] != nil {
			arg1 = args[1].(StepReplyHandlerFunc[T])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSagaStep_OnActionReply_Call[T]) Return(sagaStep SagaStep[T]) *MockSagaStep_OnActionReply_Call[T] {
	_c.Call.Return(sagaStep)
	return _c
}

func (_c *MockSagaStep_OnActionReply_Call[T]) RunAndReturn(run func(replyName string, fn StepReplyHandlerFunc[T]) SagaStep[T]) *MockSagaStep_OnActionReply_Call[T] {
	_c.Call.Return(run)
	return _c
}

// OnCompensationReply provides a mock function for the type MockSagaStep
func (_mock *MockSagaStep[T]) OnCompensationReply(replyName string, fn StepReplyHandlerFunc[T]) SagaStep[T] {
	ret := _mock.Called(replyName, fn)

	if len(ret) == 0 {
		panic("no return value specified for OnCompensationReply")
	}

	var r0 SagaStep[T]
	if returnFunc, ok := ret.Get(0).(func(string, StepReplyHandlerFunc[T]) SagaStep[T]); ok {
		r0 = returnFunc(replyName, fn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SagaStep[T])
		}
	}
	return r0
}

// MockSagaStep_OnCompensationReply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OnCompensationReply'
type MockSagaStep_OnCompensationReply_Call[T any] struct {
	*mock.Call
}

// OnCompensationReply is a helper method to define mock.On call
//   - replyName string
//   - fn StepReplyHandlerFunc[T]
func (_e *MockSagaStep_Expecter[T]) OnCompensationReply(replyName interface{}, fn interface{}) *MockSagaStep_OnCompensationReply_Call[T] {
	return &MockSagaStep_OnCompensationReply_Call[T]{Call: _e.mock.On("OnCompensationReply", replyName, fn)}
}

func (_c *MockSagaStep_OnCompensationReply_Call[T]) Run(run func(replyName string, fn StepReplyHandlerFunc[T])) *MockSagaStep_OnCompensationReply_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 StepReplyHandlerFunc[T]
		if args[1] != nil {
			arg1 = args[1].(StepReplyHandlerFunc[T])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSagaStep_OnCompensationReply_Call[T]) Return(sagaStep SagaStep[T]) *MockSagaStep_OnCompensationReply_Call[T] {
	_c.Call.Return(sagaStep)
	return _c
}

func (_c *MockSagaStep_OnCompensationReply_Call[T]) RunAndReturn(run func(replyName string, fn StepReplyHandlerFunc[T]) SagaStep[T]) *MockSagaStep_OnCompensationReply_Call[T] {
	_c.Call.Return(run)
	return _c
}

// execute provides a mock function for the type MockSagaStep
func (_mock *MockSagaStep[T]) execute(ctx context.Context, sagaCtx *SagaKontext[T]) stepResult[T] {
	ret := _mock.Called(ctx, sagaCtx)

	if len(ret) == 0 {
		panic("no return value specified for execute")
	}

	var r0 stepResult[T]
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SagaKontext[T]) stepResult[T]); ok {
		r0 = returnFunc(ctx, sagaCtx)
	} else {
		r0 = ret.Get(0).(stepResult[T])
	}
	return r0
}

// MockSagaStep_execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'execute'
type MockSagaStep_execute_Call[T any] struct {
	*mock.Call
}

// execute is a helper method to define mock.On call
//   - ctx context.Context
//   - sagaCtx *SagaKontext[T]
func (_e *MockSagaStep_Expecter[T]) execute(ctx interface{}, sagaCtx interface{}) *MockSagaStep_execute_Call[T] {
	return &MockSagaStep_execute_Call[T]{Call: _e.mock.On("execute", ctx, sagaCtx)}
}

func (_c *MockSagaStep_execute_Call[T]) Run(run func(ctx context.Context, sagaCtx *SagaKontext[T])) *MockSagaStep_execute_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *SagaKontext[T]
		if args[1] != nil {
			arg1 = args[1].(*SagaKontext[T])
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSagaStep_execute_Call[T]) Return(stepResultMoqParam stepResult[T]) *MockSagaStep_execute_Call[T] {
	_c.Call.Return(stepResultMoqParam)
	return _c
}

func (_c *MockSagaStep_execute_Call[T]) RunAndReturn(run func(ctx context.Context, sagaCtx *SagaKontext[T]) stepResult[T]) *MockSagaStep_execute_Call[T] {
	_c.Call.Return(run)
	return _c
}

// handle provides a mock function for the type MockSagaStep
func (_mock *MockSagaStep[T]) handle(ctx context.Context, sagaCtx *SagaKontext[T], reply ddd.Reply) error {
	ret := _mock.Called(ctx, sagaCtx, reply)

	if len(ret) == 0 {
		panic("no return value specified for handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *SagaKontext[T], ddd.Reply) error); ok {
		r0 = returnFunc(ctx, sagaCtx, reply)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSagaStep_handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'handle'
type MockSagaStep_handle_Call[T any] struct {
	*mock.Call
}

// handle is a helper method to define mock.On call
//   - ctx context.Context
//   - sagaCtx *SagaKontext[T]
//   - reply ddd.Reply
func (_e *MockSagaStep_Expecter[T]) handle(ctx interface{}, sagaCtx interface{}, reply interface{}) *MockSagaStep_handle_Call[T] {
	return &MockSagaStep_handle_Call[T]{Call: _e.mock.On("handle", ctx, sagaCtx, reply)}
}

func (_c *MockSagaStep_handle_Call[T]) Run(run func(ctx context.Context, sagaCtx *SagaKontext[T], reply ddd.Reply)) *MockSagaStep_handle_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *SagaKontext[T]
		if args[1] != nil {
			arg1 = args[1].(*SagaKontext[T])
		}
		var arg2 ddd.Reply
		if args[2] != nil {
			arg2 = args[2].(ddd.Reply)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSagaStep_handle_Call[T]) Return(err error) *MockSagaStep_handle_Call[T] {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSagaStep_handle_Call[T]) RunAndReturn(run func(ctx context.Context, sagaCtx *SagaKontext[T], reply ddd.Reply) error) *MockSagaStep_handle_Call[T] {
	_c.Call.Return(run)
	return _c
}

// isInvokable provides a mock function for the type MockSagaStep
func (_mock *MockSagaStep[T]) isInvokable(compensating bool) bool {
	ret := _mock.Called(compensating)

	if len(ret) == 0 {
		panic("no return value specified for isInvokable")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(bool) bool); ok {
		r0 = returnFunc(compensating)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockSagaStep_isInvokable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'isInvokable'
type MockSagaStep_isInvokable_Call[T any] struct {
	*mock.Call
}

// isInvokable is a helper method to define mock.On call
//   - compensating bool
func (_e *MockSagaStep_Expecter[T]) isInvokable(compensating interface{}) *MockSagaStep_isInvokable_Call[T] {
	return &MockSagaStep_isInvokable_Call[T]{Call: _e.mock.On("isInvokable", compensating)}
}

func (_c *MockSagaStep_isInvokable_Call[T]) Run(run func(compensating bool)) *MockSagaStep_isInvokable_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 bool
		if args[0] != nil {
			arg0 = args[0].(bool)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSagaStep_isInvokable_Call[T]) Return(b bool) *MockSagaStep_isInvokable_Call[T] {
	_c.Call.Return(b)
	return _c
}

func (_c *MockSagaStep_isInvokable_Call[T]) RunAndReturn(run func(compensating bool) bool) *MockSagaStep_isInvokable_Call[T] {
	_c.Call.Return(run)
	return _c
}
