// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sec

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSaga creates a new instance of MockSaga. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSaga[T any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSaga[T] {
	mock := &MockSaga[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSaga is an autogenerated mock type for the Saga type
type MockSaga[T any] struct {
	mock.Mock
}

type MockSaga_Expecter[T any] struct {
	mock *mock.Mock
}

func (_m *MockSaga[T]) EXPECT() *MockSaga_Expecter[T] {
	return &MockSaga_Expecter[T]{mock: &_m.Mock}
}

// AddStep provides a mock function for the type MockSaga
func (_mock *MockSaga[T]) AddStep() SagaStep[T] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AddStep")
	}

	var r0 SagaStep[T]
	if returnFunc, ok := ret.Get(0).(func() SagaStep[T]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(SagaStep[T])
		}
	}
	return r0
}

// MockSaga_AddStep_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddStep'
type MockSaga_AddStep_Call[T any] struct {
	*mock.Call
}

// AddStep is a helper method to define mock.On call
func (_e *MockSaga_Expecter[T]) AddStep() *MockSaga_AddStep_Call[T] {
	return &MockSaga_AddStep_Call[T]{Call: _e.mock.On("AddStep")}
}

func (_c *MockSaga_AddStep_Call[T]) Run(run func()) *MockSaga_AddStep_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSaga_AddStep_Call[T]) Return(sagaStep SagaStep[T]) *MockSaga_AddStep_Call[T] {
	_c.Call.Return(sagaStep)
	return _c
}

func (_c *MockSaga_AddStep_Call[T]) RunAndReturn(run func() SagaStep[T]) *MockSaga_AddStep_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockSaga
func (_mock *MockSaga[T]) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSaga_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockSaga_Name_Call[T any] struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockSaga_Expecter[T]) Name() *MockSaga_Name_Call[T] {
	return &MockSaga_Name_Call[T]{Call: _e.mock.On("Name")}
}

func (_c *MockSaga_Name_Call[T]) Run(run func()) *MockSaga_Name_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSaga_Name_Call[T]) Return(s string) *MockSaga_Name_Call[T] {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSaga_Name_Call[T]) RunAndReturn(run func() string) *MockSaga_Name_Call[T] {
	_c.Call.Return(run)
	return _c
}

// ReplyTopic provides a mock function for the type MockSaga
func (_mock *MockSaga[T]) ReplyTopic() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReplyTopic")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSaga_ReplyTopic_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplyTopic'
type MockSaga_ReplyTopic_Call[T any] struct {
	*mock.Call
}

// ReplyTopic is a helper method to define mock.On call
func (_e *MockSaga_Expecter[T]) ReplyTopic() *MockSaga_ReplyTopic_Call[T] {
	return &MockSaga_ReplyTopic_Call[T]{Call: _e.mock.On("ReplyTopic")}
}

func (_c *MockSaga_ReplyTopic_Call[T]) Run(run func()) *MockSaga_ReplyTopic_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSaga_ReplyTopic_Call[T]) Return(s string) *MockSaga_ReplyTopic_Call[T] {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSaga_ReplyTopic_Call[T]) RunAndReturn(run func() string) *MockSaga_ReplyTopic_Call[T] {
	_c.Call.Return(run)
	return _c
}

// getSteps provides a mock function for the type MockSaga
func (_mock *MockSaga[T]) getSteps() []SagaStep[T] {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for getSteps")
	}

	var r0 []SagaStep[T]
	if returnFunc, ok := ret.Get(0).(func() []SagaStep[T]); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]SagaStep[T])
		}
	}
	return r0
}

// MockSaga_getSteps_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'getSteps'
type MockSaga_getSteps_Call[T any] struct {
	*mock.Call
}

// getSteps is a helper method to define mock.On call
func (_e *MockSaga_Expecter[T]) getSteps() *MockSaga_getSteps_Call[T] {
	return &MockSaga_getSteps_Call[T]{Call: _e.mock.On("getSteps")}
}

func (_c *MockSaga_getSteps_Call[T]) Run(run func()) *MockSaga_getSteps_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSaga_getSteps_Call[T]) Return(sagaSteps []SagaStep[T]) *MockSaga_getSteps_Call[T] {
	_c.Call.Return(sagaSteps)
	return _c
}

func (_c *MockSaga_getSteps_Call[T]) RunAndReturn(run func() []SagaStep[T]) *MockSaga_getSteps_Call[T] {
	_c.Call.Return(run)
	return _c
}
