// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sec

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSagaStore creates a new instance of MockSagaStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSagaStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSagaStore {
	mock := &MockSagaStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSagaStore is an autogenerated mock type for the SagaStore type
type MockSagaStore struct {
	mock.Mock
}

type MockSagaStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSagaStore) EXPECT() *MockSagaStore_Expecter {
	return &MockSagaStore_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockSagaStore
func (_mock *MockSagaStore) Load(ctx context.Context, sagaName string, sagaID string) (*SagaKontext[[]byte], error) {
	ret := _mock.Called(ctx, sagaName, sagaID)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *SagaKontext[[]byte]
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*SagaKontext[[]byte], error)); ok {
		return returnFunc(ctx, sagaName, sagaID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *SagaKontext[[]byte]); ok {
		r0 = returnFunc(ctx, sagaName, sagaID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*SagaKontext[[]byte])
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, sagaName, sagaID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSagaStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockSagaStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - sagaName string
//   - sagaID string
func (_e *MockSagaStore_Expecter) Load(ctx interface{}, sagaName interface{}, sagaID interface{}) *MockSagaStore_Load_Call {
	return &MockSagaStore_Load_Call{Call: _e.mock.On("Load", ctx, sagaName, sagaID)}
}

func (_c *MockSagaStore_Load_Call) Run(run func(ctx context.Context, sagaName string, sagaID string)) *MockSagaStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSagaStore_Load_Call) Return(sagaKontext *SagaKontext[[]byte], err error) *MockSagaStore_Load_Call {
	_c.Call.Return(sagaKontext, err)
	return _c
}

func (_c *MockSagaStore_Load_Call) RunAndReturn(run func(ctx context.Context, sagaName string, sagaID string) (*SagaKontext[[]byte], error)) *MockSagaStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockSagaStore
func (_mock *MockSagaStore) Save(ctx context.Context, sagaName string, sagaCtx *SagaKontext[[]byte]) error {
	ret := _mock.Called(ctx, sagaName, sagaCtx)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *SagaKontext[[]byte]) error); ok {
		r0 = returnFunc(ctx, sagaName, sagaCtx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSagaStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockSagaStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - sagaName string
//   - sagaCtx *SagaKontext[[]byte]
func (_e *MockSagaStore_Expecter) Save(ctx interface{}, sagaName interface{}, sagaCtx interface{}) *MockSagaStore_Save_Call {
	return &MockSagaStore_Save_Call{Call: _e.mock.On("Save", ctx, sagaName, sagaCtx)}
}

func (_c *MockSagaStore_Save_Call) Run(run func(ctx context.Context, sagaName string, sagaCtx *SagaKontext[[]byte])) *MockSagaStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *SagaKontext[[]byte]
		if args[2] != nil {
			arg2 = args[2].(*SagaKontext[[]byte])
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockSagaStore_Save_Call) Return(err error) *MockSagaStore_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSagaStore_Save_Call) RunAndReturn(run func(ctx context.Context, sagaName string, sagaCtx *SagaKontext[[]byte]) error) *MockSagaStore_Save_Call {
	_c.Call.Return(run)
	return _c
}
