// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package monolith

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockModule creates a new instance of MockModule. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModule(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModule {
	mock := &MockModule{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockModule is an autogenerated mock type for the Module type
type MockModule struct {
	mock.Mock
}

type MockModule_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModule) EXPECT() *MockModule_Expecter {
	return &MockModule_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type MockModule
func (_mock *MockModule) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockModule_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockModule_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockModule_Expecter) Name() *MockModule_Name_Call {
	return &MockModule_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockModule_Name_Call) Run(run func()) *MockModule_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockModule_Name_Call) Return(s string) *MockModule_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockModule_Name_Call) RunAndReturn(run func() string) *MockModule_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Startup provides a mock function for the type MockModule
func (_mock *MockModule) Startup(context1 context.Context, monolith Monolith) error {
	ret := _mock.Called(context1, monolith)

	if len(ret) == 0 {
		panic("no return value specified for Startup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Monolith) error); ok {
		r0 = returnFunc(context1, monolith)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockModule_Startup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Startup'
type MockModule_Startup_Call struct {
	*mock.Call
}

// Startup is a helper method to define mock.On call
//   - context1 context.Context
//   - monolith Monolith
func (_e *MockModule_Expecter) Startup(context1 interface{}, monolith interface{}) *MockModule_Startup_Call {
	return &MockModule_Startup_Call{Call: _e.mock.On("Startup", context1, monolith)}
}

func (_c *MockModule_Startup_Call) Run(run func(context1 context.Context, monolith Monolith)) *MockModule_Startup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Monolith
		if args[1] != nil {
			arg1 = args[1].(Monolith)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockModule_Startup_Call) Return(err error) *MockModule_Startup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockModule_Startup_Call) RunAndReturn(run func(context1 context.Context, monolith Monolith) error) *MockModule_Startup_Call {
	_c.Call.Return(run)
	return _c
}
