// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package monolith

import (
	"database/sql"
	"eda-in-golang/internal/config"
	"eda-in-golang/internal/waiter"

	"github.com/go-chi/chi/v5"
	"github.com/nats-io/nats.go"
	"github.com/rs/zerolog"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockMonolith creates a new instance of MockMonolith. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMonolith(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMonolith {
	mock := &MockMonolith{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMonolith is an autogenerated mock type for the Monolith type
type MockMonolith struct {
	mock.Mock
}

type MockMonolith_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMonolith) EXPECT() *MockMonolith_Expecter {
	return &MockMonolith_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockMonolith
func (_mock *MockMonolith) Config() config.AppConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.AppConfig
	if returnFunc, ok := ret.Get(0).(func() config.AppConfig); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(config.AppConfig)
	}
	return r0
}

// MockMonolith_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockMonolith_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockMonolith_Expecter) Config() *MockMonolith_Config_Call {
	return &MockMonolith_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockMonolith_Config_Call) Run(run func()) *MockMonolith_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMonolith_Config_Call) Return(appConfig config.AppConfig) *MockMonolith_Config_Call {
	_c.Call.Return(appConfig)
	return _c
}

func (_c *MockMonolith_Config_Call) RunAndReturn(run func() config.AppConfig) *MockMonolith_Config_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockMonolith
func (_mock *MockMonolith) DB() *sql.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *sql.DB
	if returnFunc, ok := ret.Get(0).(func() *sql.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sql.DB)
		}
	}
	return r0
}

// MockMonolith_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockMonolith_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockMonolith_Expecter) DB() *MockMonolith_DB_Call {
	return &MockMonolith_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockMonolith_DB_Call) Run(run func()) *MockMonolith_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMonolith_DB_Call) Return(dB *sql.DB) *MockMonolith_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockMonolith_DB_Call) RunAndReturn(run func() *sql.DB) *MockMonolith_DB_Call {
	_c.Call.Return(run)
	return _c
}

// JS provides a mock function for the type MockMonolith
func (_mock *MockMonolith) JS() nats.JetStreamContext {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for JS")
	}

	var r0 nats.JetStreamContext
	if returnFunc, ok := ret.Get(0).(func() nats.JetStreamContext); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(nats.JetStreamContext)
		}
	}
	return r0
}

// MockMonolith_JS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JS'
type MockMonolith_JS_Call struct {
	*mock.Call
}

// JS is a helper method to define mock.On call
func (_e *MockMonolith_Expecter) JS() *MockMonolith_JS_Call {
	return &MockMonolith_JS_Call{Call: _e.mock.On("JS")}
}

func (_c *MockMonolith_JS_Call) Run(run func()) *MockMonolith_JS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMonolith_JS_Call) Return(jetStreamContext nats.JetStreamContext) *MockMonolith_JS_Call {
	_c.Call.Return(jetStreamContext)
	return _c
}

func (_c *MockMonolith_JS_Call) RunAndReturn(run func() nats.JetStreamContext) *MockMonolith_JS_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockMonolith
func (_mock *MockMonolith) Logger() zerolog.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 zerolog.Logger
	if returnFunc, ok := ret.Get(0).(func() zerolog.Logger); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(zerolog.Logger)
	}
	return r0
}

// MockMonolith_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockMonolith_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockMonolith_Expecter) Logger() *MockMonolith_Logger_Call {
	return &MockMonolith_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockMonolith_Logger_Call) Run(run func()) *MockMonolith_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMonolith_Logger_Call) Return(logger zerolog.Logger) *MockMonolith_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockMonolith_Logger_Call) RunAndReturn(run func() zerolog.Logger) *MockMonolith_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// Mux provides a mock function for the type MockMonolith
func (_mock *MockMonolith) Mux() *chi.Mux {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Mux")
	}

	var r0 *chi.Mux
	if returnFunc, ok := ret.Get(0).(func() *chi.Mux); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chi.Mux)
		}
	}
	return r0
}

// MockMonolith_Mux_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Mux'
type MockMonolith_Mux_Call struct {
	*mock.Call
}

// Mux is a helper method to define mock.On call
func (_e *MockMonolith_Expecter) Mux() *MockMonolith_Mux_Call {
	return &MockMonolith_Mux_Call{Call: _e.mock.On("Mux")}
}

func (_c *MockMonolith_Mux_Call) Run(run func()) *MockMonolith_Mux_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMonolith_Mux_Call) Return(mux *chi.Mux) *MockMonolith_Mux_Call {
	_c.Call.Return(mux)
	return _c
}

func (_c *MockMonolith_Mux_Call) RunAndReturn(run func() *chi.Mux) *MockMonolith_Mux_Call {
	_c.Call.Return(run)
	return _c
}

// RPC provides a mock function for the type MockMonolith
func (_mock *MockMonolith) RPC() *grpc.Server {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RPC")
	}

	var r0 *grpc.Server
	if returnFunc, ok := ret.Get(0).(func() *grpc.Server); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*grpc.Server)
		}
	}
	return r0
}

// MockMonolith_RPC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RPC'
type MockMonolith_RPC_Call struct {
	*mock.Call
}

// RPC is a helper method to define mock.On call
func (_e *MockMonolith_Expecter) RPC() *MockMonolith_RPC_Call {
	return &MockMonolith_RPC_Call{Call: _e.mock.On("RPC")}
}

func (_c *MockMonolith_RPC_Call) Run(run func()) *MockMonolith_RPC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMonolith_RPC_Call) Return(server *grpc.Server) *MockMonolith_RPC_Call {
	_c.Call.Return(server)
	return _c
}

func (_c *MockMonolith_RPC_Call) RunAndReturn(run func() *grpc.Server) *MockMonolith_RPC_Call {
	_c.Call.Return(run)
	return _c
}

// Waiter provides a mock function for the type MockMonolith
func (_mock *MockMonolith) Waiter() waiter.Waiter {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Waiter")
	}

	var r0 waiter.Waiter
	if returnFunc, ok := ret.Get(0).(func() waiter.Waiter); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(waiter.Waiter)
		}
	}
	return r0
}

// MockMonolith_Waiter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Waiter'
type MockMonolith_Waiter_Call struct {
	*mock.Call
}

// Waiter is a helper method to define mock.On call
func (_e *MockMonolith_Expecter) Waiter() *MockMonolith_Waiter_Call {
	return &MockMonolith_Waiter_Call{Call: _e.mock.On("Waiter")}
}

func (_c *MockMonolith_Waiter_Call) Run(run func()) *MockMonolith_Waiter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMonolith_Waiter_Call) Return(waiter1 waiter.Waiter) *MockMonolith_Waiter_Call {
	_c.Call.Return(waiter1)
	return _c
}

func (_c *MockMonolith_Waiter_Call) RunAndReturn(run func() waiter.Waiter) *MockMonolith_Waiter_Call {
	_c.Call.Return(run)
	return _c
}
