// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package es

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventCommitter creates a new instance of MockEventCommitter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventCommitter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventCommitter {
	mock := &MockEventCommitter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventCommitter is an autogenerated mock type for the EventCommitter type
type MockEventCommitter struct {
	mock.Mock
}

type MockEventCommitter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventCommitter) EXPECT() *MockEventCommitter_Expecter {
	return &MockEventCommitter_Expecter{mock: &_m.Mock}
}

// CommitEvents provides a mock function for the type MockEventCommitter
func (_mock *MockEventCommitter) CommitEvents() {
	_mock.Called()
	return
}

// MockEventCommitter_CommitEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitEvents'
type MockEventCommitter_CommitEvents_Call struct {
	*mock.Call
}

// CommitEvents is a helper method to define mock.On call
func (_e *MockEventCommitter_Expecter) CommitEvents() *MockEventCommitter_CommitEvents_Call {
	return &MockEventCommitter_CommitEvents_Call{Call: _e.mock.On("CommitEvents")}
}

func (_c *MockEventCommitter_CommitEvents_Call) Run(run func()) *MockEventCommitter_CommitEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventCommitter_CommitEvents_Call) Return() *MockEventCommitter_CommitEvents_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventCommitter_CommitEvents_Call) RunAndReturn(run func()) *MockEventCommitter_CommitEvents_Call {
	_c.Run(run)
	return _c
}
