// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package es

import (
	"eda-in-golang/internal/ddd"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventApplier creates a new instance of MockEventApplier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventApplier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventApplier {
	mock := &MockEventApplier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventApplier is an autogenerated mock type for the EventApplier type
type MockEventApplier struct {
	mock.Mock
}

type MockEventApplier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventApplier) EXPECT() *MockEventApplier_Expecter {
	return &MockEventApplier_Expecter{mock: &_m.Mock}
}

// ApplyEvent provides a mock function for the type MockEventApplier
func (_mock *MockEventApplier) ApplyEvent(event ddd.Event) error {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for ApplyEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ddd.Event) error); ok {
		r0 = returnFunc(event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventApplier_ApplyEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyEvent'
type MockEventApplier_ApplyEvent_Call struct {
	*mock.Call
}

// ApplyEvent is a helper method to define mock.On call
//   - event ddd.Event
func (_e *MockEventApplier_Expecter) ApplyEvent(event interface{}) *MockEventApplier_ApplyEvent_Call {
	return &MockEventApplier_ApplyEvent_Call{Call: _e.mock.On("ApplyEvent", event)}
}

func (_c *MockEventApplier_ApplyEvent_Call) Run(run func(event ddd.Event)) *MockEventApplier_ApplyEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ddd.Event
		if args[0] != nil {
			arg0 = args[0].(ddd.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventApplier_ApplyEvent_Call) Return(err error) *MockEventApplier_ApplyEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventApplier_ApplyEvent_Call) RunAndReturn(run func(event ddd.Event) error) *MockEventApplier_ApplyEvent_Call {
	_c.Call.Return(run)
	return _c
}
