// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package es

import (
	"eda-in-golang/internal/ddd"

	mock "github.com/stretchr/testify/mock"
)

// NewMockEventSourcedAggregate creates a new instance of MockEventSourcedAggregate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventSourcedAggregate(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventSourcedAggregate {
	mock := &MockEventSourcedAggregate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventSourcedAggregate is an autogenerated mock type for the EventSourcedAggregate type
type MockEventSourcedAggregate struct {
	mock.Mock
}

type MockEventSourcedAggregate_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventSourcedAggregate) EXPECT() *MockEventSourcedAggregate_Expecter {
	return &MockEventSourcedAggregate_Expecter{mock: &_m.Mock}
}

// AddEvent provides a mock function for the type MockEventSourcedAggregate
func (_mock *MockEventSourcedAggregate) AddEvent(s string, eventPayload ddd.EventPayload, eventOptions ...ddd.EventOption) {
	if len(eventOptions) > 0 {
		_mock.Called(s, eventPayload, eventOptions)
	} else {
		_mock.Called(s, eventPayload)
	}

	return
}

// MockEventSourcedAggregate_AddEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEvent'
type MockEventSourcedAggregate_AddEvent_Call struct {
	*mock.Call
}

// AddEvent is a helper method to define mock.On call
//   - s string
//   - eventPayload ddd.EventPayload
//   - eventOptions ...ddd.EventOption
func (_e *MockEventSourcedAggregate_Expecter) AddEvent(s interface{}, eventPayload interface{}, eventOptions ...interface{}) *MockEventSourcedAggregate_AddEvent_Call {
	return &MockEventSourcedAggregate_AddEvent_Call{Call: _e.mock.On("AddEvent",
		append([]interface{}{s, eventPayload}, eventOptions...)...)}
}

func (_c *MockEventSourcedAggregate_AddEvent_Call) Run(run func(s string, eventPayload ddd.EventPayload, eventOptions ...ddd.EventOption)) *MockEventSourcedAggregate_AddEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 ddd.EventPayload
		if args[1] != nil {
			arg1 = args[1].(ddd.EventPayload)
		}
		var arg2 []ddd.EventOption
		var variadicArgs []ddd.EventOption
		if len(args) > 2 {
			variadicArgs = args[2].([]ddd.EventOption)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEventSourcedAggregate_AddEvent_Call) Return() *MockEventSourcedAggregate_AddEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventSourcedAggregate_AddEvent_Call) RunAndReturn(run func(s string, eventPayload ddd.EventPayload, eventOptions ...ddd.EventOption)) *MockEventSourcedAggregate_AddEvent_Call {
	_c.Run(run)
	return _c
}

// AggregateName provides a mock function for the type MockEventSourcedAggregate
func (_mock *MockEventSourcedAggregate) AggregateName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AggregateName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEventSourcedAggregate_AggregateName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggregateName'
type MockEventSourcedAggregate_AggregateName_Call struct {
	*mock.Call
}

// AggregateName is a helper method to define mock.On call
func (_e *MockEventSourcedAggregate_Expecter) AggregateName() *MockEventSourcedAggregate_AggregateName_Call {
	return &MockEventSourcedAggregate_AggregateName_Call{Call: _e.mock.On("AggregateName")}
}

func (_c *MockEventSourcedAggregate_AggregateName_Call) Run(run func()) *MockEventSourcedAggregate_AggregateName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventSourcedAggregate_AggregateName_Call) Return(s string) *MockEventSourcedAggregate_AggregateName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEventSourcedAggregate_AggregateName_Call) RunAndReturn(run func() string) *MockEventSourcedAggregate_AggregateName_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyEvent provides a mock function for the type MockEventSourcedAggregate
func (_mock *MockEventSourcedAggregate) ApplyEvent(event ddd.Event) error {
	ret := _mock.Called(event)

	if len(ret) == 0 {
		panic("no return value specified for ApplyEvent")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(ddd.Event) error); ok {
		r0 = returnFunc(event)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventSourcedAggregate_ApplyEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyEvent'
type MockEventSourcedAggregate_ApplyEvent_Call struct {
	*mock.Call
}

// ApplyEvent is a helper method to define mock.On call
//   - event ddd.Event
func (_e *MockEventSourcedAggregate_Expecter) ApplyEvent(event interface{}) *MockEventSourcedAggregate_ApplyEvent_Call {
	return &MockEventSourcedAggregate_ApplyEvent_Call{Call: _e.mock.On("ApplyEvent", event)}
}

func (_c *MockEventSourcedAggregate_ApplyEvent_Call) Run(run func(event ddd.Event)) *MockEventSourcedAggregate_ApplyEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 ddd.Event
		if args[0] != nil {
			arg0 = args[0].(ddd.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventSourcedAggregate_ApplyEvent_Call) Return(err error) *MockEventSourcedAggregate_ApplyEvent_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventSourcedAggregate_ApplyEvent_Call) RunAndReturn(run func(event ddd.Event) error) *MockEventSourcedAggregate_ApplyEvent_Call {
	_c.Call.Return(run)
	return _c
}

// ClearEvents provides a mock function for the type MockEventSourcedAggregate
func (_mock *MockEventSourcedAggregate) ClearEvents() {
	_mock.Called()
	return
}

// MockEventSourcedAggregate_ClearEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearEvents'
type MockEventSourcedAggregate_ClearEvents_Call struct {
	*mock.Call
}

// ClearEvents is a helper method to define mock.On call
func (_e *MockEventSourcedAggregate_Expecter) ClearEvents() *MockEventSourcedAggregate_ClearEvents_Call {
	return &MockEventSourcedAggregate_ClearEvents_Call{Call: _e.mock.On("ClearEvents")}
}

func (_c *MockEventSourcedAggregate_ClearEvents_Call) Run(run func()) *MockEventSourcedAggregate_ClearEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventSourcedAggregate_ClearEvents_Call) Return() *MockEventSourcedAggregate_ClearEvents_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventSourcedAggregate_ClearEvents_Call) RunAndReturn(run func()) *MockEventSourcedAggregate_ClearEvents_Call {
	_c.Run(run)
	return _c
}

// CommitEvents provides a mock function for the type MockEventSourcedAggregate
func (_mock *MockEventSourcedAggregate) CommitEvents() {
	_mock.Called()
	return
}

// MockEventSourcedAggregate_CommitEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitEvents'
type MockEventSourcedAggregate_CommitEvents_Call struct {
	*mock.Call
}

// CommitEvents is a helper method to define mock.On call
func (_e *MockEventSourcedAggregate_Expecter) CommitEvents() *MockEventSourcedAggregate_CommitEvents_Call {
	return &MockEventSourcedAggregate_CommitEvents_Call{Call: _e.mock.On("CommitEvents")}
}

func (_c *MockEventSourcedAggregate_CommitEvents_Call) Run(run func()) *MockEventSourcedAggregate_CommitEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventSourcedAggregate_CommitEvents_Call) Return() *MockEventSourcedAggregate_CommitEvents_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventSourcedAggregate_CommitEvents_Call) RunAndReturn(run func()) *MockEventSourcedAggregate_CommitEvents_Call {
	_c.Run(run)
	return _c
}

// Events provides a mock function for the type MockEventSourcedAggregate
func (_mock *MockEventSourcedAggregate) Events() []ddd.AggregateEvent {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 []ddd.AggregateEvent
	if returnFunc, ok := ret.Get(0).(func() []ddd.AggregateEvent); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ddd.AggregateEvent)
		}
	}
	return r0
}

// MockEventSourcedAggregate_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type MockEventSourcedAggregate_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
func (_e *MockEventSourcedAggregate_Expecter) Events() *MockEventSourcedAggregate_Events_Call {
	return &MockEventSourcedAggregate_Events_Call{Call: _e.mock.On("Events")}
}

func (_c *MockEventSourcedAggregate_Events_Call) Run(run func()) *MockEventSourcedAggregate_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventSourcedAggregate_Events_Call) Return(aggregateEvents []ddd.AggregateEvent) *MockEventSourcedAggregate_Events_Call {
	_c.Call.Return(aggregateEvents)
	return _c
}

func (_c *MockEventSourcedAggregate_Events_Call) RunAndReturn(run func() []ddd.AggregateEvent) *MockEventSourcedAggregate_Events_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockEventSourcedAggregate
func (_mock *MockEventSourcedAggregate) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEventSourcedAggregate_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockEventSourcedAggregate_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockEventSourcedAggregate_Expecter) ID() *MockEventSourcedAggregate_ID_Call {
	return &MockEventSourcedAggregate_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockEventSourcedAggregate_ID_Call) Run(run func()) *MockEventSourcedAggregate_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventSourcedAggregate_ID_Call) Return(s string) *MockEventSourcedAggregate_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEventSourcedAggregate_ID_Call) RunAndReturn(run func() string) *MockEventSourcedAggregate_ID_Call {
	_c.Call.Return(run)
	return _c
}

// PendingVersion provides a mock function for the type MockEventSourcedAggregate
func (_mock *MockEventSourcedAggregate) PendingVersion() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PendingVersion")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockEventSourcedAggregate_PendingVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingVersion'
type MockEventSourcedAggregate_PendingVersion_Call struct {
	*mock.Call
}

// PendingVersion is a helper method to define mock.On call
func (_e *MockEventSourcedAggregate_Expecter) PendingVersion() *MockEventSourcedAggregate_PendingVersion_Call {
	return &MockEventSourcedAggregate_PendingVersion_Call{Call: _e.mock.On("PendingVersion")}
}

func (_c *MockEventSourcedAggregate_PendingVersion_Call) Run(run func()) *MockEventSourcedAggregate_PendingVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventSourcedAggregate_PendingVersion_Call) Return(n int) *MockEventSourcedAggregate_PendingVersion_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockEventSourcedAggregate_PendingVersion_Call) RunAndReturn(run func() int) *MockEventSourcedAggregate_PendingVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type MockEventSourcedAggregate
func (_mock *MockEventSourcedAggregate) Version() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockEventSourcedAggregate_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockEventSourcedAggregate_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockEventSourcedAggregate_Expecter) Version() *MockEventSourcedAggregate_Version_Call {
	return &MockEventSourcedAggregate_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockEventSourcedAggregate_Version_Call) Run(run func()) *MockEventSourcedAggregate_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventSourcedAggregate_Version_Call) Return(n int) *MockEventSourcedAggregate_Version_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockEventSourcedAggregate_Version_Call) RunAndReturn(run func() int) *MockEventSourcedAggregate_Version_Call {
	_c.Call.Return(run)
	return _c
}
