// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package es

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSnapshotter creates a new instance of MockSnapshotter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnapshotter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnapshotter {
	mock := &MockSnapshotter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSnapshotter is an autogenerated mock type for the Snapshotter type
type MockSnapshotter struct {
	mock.Mock
}

type MockSnapshotter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnapshotter) EXPECT() *MockSnapshotter_Expecter {
	return &MockSnapshotter_Expecter{mock: &_m.Mock}
}

// ApplySnapshot provides a mock function for the type MockSnapshotter
func (_mock *MockSnapshotter) ApplySnapshot(snapshot Snapshot) error {
	ret := _mock.Called(snapshot)

	if len(ret) == 0 {
		panic("no return value specified for ApplySnapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Snapshot) error); ok {
		r0 = returnFunc(snapshot)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSnapshotter_ApplySnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplySnapshot'
type MockSnapshotter_ApplySnapshot_Call struct {
	*mock.Call
}

// ApplySnapshot is a helper method to define mock.On call
//   - snapshot Snapshot
func (_e *MockSnapshotter_Expecter) ApplySnapshot(snapshot interface{}) *MockSnapshotter_ApplySnapshot_Call {
	return &MockSnapshotter_ApplySnapshot_Call{Call: _e.mock.On("ApplySnapshot", snapshot)}
}

func (_c *MockSnapshotter_ApplySnapshot_Call) Run(run func(snapshot Snapshot)) *MockSnapshotter_ApplySnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Snapshot
		if args[0] != nil {
			arg0 = args[0].(Snapshot)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSnapshotter_ApplySnapshot_Call) Return(err error) *MockSnapshotter_ApplySnapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSnapshotter_ApplySnapshot_Call) RunAndReturn(run func(snapshot Snapshot) error) *MockSnapshotter_ApplySnapshot_Call {
	_c.Call.Return(run)
	return _c
}

// ToSnapshot provides a mock function for the type MockSnapshotter
func (_mock *MockSnapshotter) ToSnapshot() Snapshot {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ToSnapshot")
	}

	var r0 Snapshot
	if returnFunc, ok := ret.Get(0).(func() Snapshot); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Snapshot)
		}
	}
	return r0
}

// MockSnapshotter_ToSnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ToSnapshot'
type MockSnapshotter_ToSnapshot_Call struct {
	*mock.Call
}

// ToSnapshot is a helper method to define mock.On call
func (_e *MockSnapshotter_Expecter) ToSnapshot() *MockSnapshotter_ToSnapshot_Call {
	return &MockSnapshotter_ToSnapshot_Call{Call: _e.mock.On("ToSnapshot")}
}

func (_c *MockSnapshotter_ToSnapshot_Call) Run(run func()) *MockSnapshotter_ToSnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSnapshotter_ToSnapshot_Call) Return(snapshot Snapshot) *MockSnapshotter_ToSnapshot_Call {
	_c.Call.Return(snapshot)
	return _c
}

func (_c *MockSnapshotter_ToSnapshot_Call) RunAndReturn(run func() Snapshot) *MockSnapshotter_ToSnapshot_Call {
	_c.Call.Return(run)
	return _c
}
