// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package es

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSnapshotApplier creates a new instance of MockSnapshotApplier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnapshotApplier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnapshotApplier {
	mock := &MockSnapshotApplier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSnapshotApplier is an autogenerated mock type for the SnapshotApplier type
type MockSnapshotApplier struct {
	mock.Mock
}

type MockSnapshotApplier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnapshotApplier) EXPECT() *MockSnapshotApplier_Expecter {
	return &MockSnapshotApplier_Expecter{mock: &_m.Mock}
}

// ApplySnapshot provides a mock function for the type MockSnapshotApplier
func (_mock *MockSnapshotApplier) ApplySnapshot(snapshot Snapshot) error {
	ret := _mock.Called(snapshot)

	if len(ret) == 0 {
		panic("no return value specified for ApplySnapshot")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(Snapshot) error); ok {
		r0 = returnFunc(snapshot)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSnapshotApplier_ApplySnapshot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplySnapshot'
type MockSnapshotApplier_ApplySnapshot_Call struct {
	*mock.Call
}

// ApplySnapshot is a helper method to define mock.On call
//   - snapshot Snapshot
func (_e *MockSnapshotApplier_Expecter) ApplySnapshot(snapshot interface{}) *MockSnapshotApplier_ApplySnapshot_Call {
	return &MockSnapshotApplier_ApplySnapshot_Call{Call: _e.mock.On("ApplySnapshot", snapshot)}
}

func (_c *MockSnapshotApplier_ApplySnapshot_Call) Run(run func(snapshot Snapshot)) *MockSnapshotApplier_ApplySnapshot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 Snapshot
		if args[0] != nil {
			arg0 = args[0].(Snapshot)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSnapshotApplier_ApplySnapshot_Call) Return(err error) *MockSnapshotApplier_ApplySnapshot_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSnapshotApplier_ApplySnapshot_Call) RunAndReturn(run func(snapshot Snapshot) error) *MockSnapshotApplier_ApplySnapshot_Call {
	_c.Call.Return(run)
	return _c
}
