// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package es

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockSnapshot creates a new instance of MockSnapshot. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSnapshot(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSnapshot {
	mock := &MockSnapshot{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSnapshot is an autogenerated mock type for the Snapshot type
type MockSnapshot struct {
	mock.Mock
}

type MockSnapshot_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSnapshot) EXPECT() *MockSnapshot_Expecter {
	return &MockSnapshot_Expecter{mock: &_m.Mock}
}

// SnapshotName provides a mock function for the type MockSnapshot
func (_mock *MockSnapshot) SnapshotName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SnapshotName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockSnapshot_SnapshotName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SnapshotName'
type MockSnapshot_SnapshotName_Call struct {
	*mock.Call
}

// SnapshotName is a helper method to define mock.On call
func (_e *MockSnapshot_Expecter) SnapshotName() *MockSnapshot_SnapshotName_Call {
	return &MockSnapshot_SnapshotName_Call{Call: _e.mock.On("SnapshotName")}
}

func (_c *MockSnapshot_SnapshotName_Call) Run(run func()) *MockSnapshot_SnapshotName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSnapshot_SnapshotName_Call) Return(s string) *MockSnapshot_SnapshotName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockSnapshot_SnapshotName_Call) RunAndReturn(run func() string) *MockSnapshot_SnapshotName_Call {
	_c.Call.Return(run)
	return _c
}
