// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package es

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockVersionSetter creates a new instance of MockVersionSetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVersionSetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVersionSetter {
	mock := &MockVersionSetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVersionSetter is an autogenerated mock type for the VersionSetter type
type MockVersionSetter struct {
	mock.Mock
}

type MockVersionSetter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVersionSetter) EXPECT() *MockVersionSetter_Expecter {
	return &MockVersionSetter_Expecter{mock: &_m.Mock}
}

// setVersion provides a mock function for the type MockVersionSetter
func (_mock *MockVersionSetter) setVersion(n int) {
	_mock.Called(n)
	return
}

// MockVersionSetter_setVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'setVersion'
type MockVersionSetter_setVersion_Call struct {
	*mock.Call
}

// setVersion is a helper method to define mock.On call
//   - n int
func (_e *MockVersionSetter_Expecter) setVersion(n interface{}) *MockVersionSetter_setVersion_Call {
	return &MockVersionSetter_setVersion_Call{Call: _e.mock.On("setVersion", n)}
}

func (_c *MockVersionSetter_setVersion_Call) Run(run func(n int)) *MockVersionSetter_setVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVersionSetter_setVersion_Call) Return() *MockVersionSetter_setVersion_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockVersionSetter_setVersion_Call) RunAndReturn(run func(n int)) *MockVersionSetter_setVersion_Call {
	_c.Run(run)
	return _c
}
