// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package es

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockVersioner creates a new instance of MockVersioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVersioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVersioner {
	mock := &MockVersioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVersioner is an autogenerated mock type for the Versioner type
type MockVersioner struct {
	mock.Mock
}

type MockVersioner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVersioner) EXPECT() *MockVersioner_Expecter {
	return &MockVersioner_Expecter{mock: &_m.Mock}
}

// PendingVersion provides a mock function for the type MockVersioner
func (_mock *MockVersioner) PendingVersion() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PendingVersion")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockVersioner_PendingVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingVersion'
type MockVersioner_PendingVersion_Call struct {
	*mock.Call
}

// PendingVersion is a helper method to define mock.On call
func (_e *MockVersioner_Expecter) PendingVersion() *MockVersioner_PendingVersion_Call {
	return &MockVersioner_PendingVersion_Call{Call: _e.mock.On("PendingVersion")}
}

func (_c *MockVersioner_PendingVersion_Call) Run(run func()) *MockVersioner_PendingVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVersioner_PendingVersion_Call) Return(n int) *MockVersioner_PendingVersion_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockVersioner_PendingVersion_Call) RunAndReturn(run func() int) *MockVersioner_PendingVersion_Call {
	_c.Call.Return(run)
	return _c
}

// Version provides a mock function for the type MockVersioner
func (_mock *MockVersioner) Version() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockVersioner_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockVersioner_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockVersioner_Expecter) Version() *MockVersioner_Version_Call {
	return &MockVersioner_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockVersioner_Version_Call) Run(run func()) *MockVersioner_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockVersioner_Version_Call) Return(n int) *MockVersioner_Version_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockVersioner_Version_Call) RunAndReturn(run func() int) *MockVersioner_Version_Call {
	_c.Call.Return(run)
	return _c
}
