// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockOrderRepository creates a new instance of MockOrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderRepository {
	mock := &MockOrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrderRepository is an autogenerated mock type for the OrderRepository type
type MockOrderRepository struct {
	mock.Mock
}

type MockOrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderRepository) EXPECT() *MockOrderRepository_Expecter {
	return &MockOrderRepository_Expecter{mock: &_m.Mock}
}

// Load provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Load(ctx context.Context, id string) (*Order, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*Order, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *Order); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrderRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockOrderRepository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockOrderRepository_Expecter) Load(ctx interface{}, id interface{}) *MockOrderRepository_Load_Call {
	return &MockOrderRepository_Load_Call{Call: _e.mock.On("Load", ctx, id)}
}

func (_c *MockOrderRepository_Load_Call) Run(run func(ctx context.Context, id string)) *MockOrderRepository_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Load_Call) Return(order *Order, err error) *MockOrderRepository_Load_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockOrderRepository_Load_Call) RunAndReturn(run func(ctx context.Context, id string) (*Order, error)) *MockOrderRepository_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockOrderRepository
func (_mock *MockOrderRepository) Save(ctx context.Context, order *Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOrderRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockOrderRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - order *Order
func (_e *MockOrderRepository_Expecter) Save(ctx interface{}, order interface{}) *MockOrderRepository_Save_Call {
	return &MockOrderRepository_Save_Call{Call: _e.mock.On("Save", ctx, order)}
}

func (_c *MockOrderRepository_Save_Call) Run(run func(ctx context.Context, order *Order)) *MockOrderRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Order
		if args[1] != nil {
			arg1 = args[1].(*Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrderRepository_Save_Call) Return(err error) *MockOrderRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOrderRepository_Save_Call) RunAndReturn(run func(ctx context.Context, order *Order) error) *MockOrderRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
