// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPaymentRepository creates a new instance of MockPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepository {
	mock := &MockPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPaymentRepository is an autogenerated mock type for the PaymentRepository type
type MockPaymentRepository struct {
	mock.Mock
}

type MockPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRepository) EXPECT() *MockPaymentRepository_Expecter {
	return &MockPaymentRepository_Expecter{mock: &_m.Mock}
}

// Confirm provides a mock function for the type MockPaymentRepository
func (_mock *MockPaymentRepository) Confirm(ctx context.Context, paymentID string) error {
	ret := _mock.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, paymentID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPaymentRepository_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type MockPaymentRepository_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID string
func (_e *MockPaymentRepository_Expecter) Confirm(ctx interface{}, paymentID interface{}) *MockPaymentRepository_Confirm_Call {
	return &MockPaymentRepository_Confirm_Call{Call: _e.mock.On("Confirm", ctx, paymentID)}
}

func (_c *MockPaymentRepository_Confirm_Call) Run(run func(ctx context.Context, paymentID string)) *MockPaymentRepository_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPaymentRepository_Confirm_Call) Return(err error) *MockPaymentRepository_Confirm_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPaymentRepository_Confirm_Call) RunAndReturn(run func(ctx context.Context, paymentID string) error) *MockPaymentRepository_Confirm_Call {
	_c.Call.Return(run)
	return _c
}
