// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockShoppingRepository creates a new instance of MockShoppingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShoppingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShoppingRepository {
	mock := &MockShoppingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShoppingRepository is an autogenerated mock type for the ShoppingRepository type
type MockShoppingRepository struct {
	mock.Mock
}

type MockShoppingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShoppingRepository) EXPECT() *MockShoppingRepository_Expecter {
	return &MockShoppingRepository_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockShoppingRepository
func (_mock *MockShoppingRepository) Cancel(ctx context.Context, shoppingID string) error {
	ret := _mock.Called(ctx, shoppingID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, shoppingID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShoppingRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockShoppingRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - shoppingID string
func (_e *MockShoppingRepository_Expecter) Cancel(ctx interface{}, shoppingID interface{}) *MockShoppingRepository_Cancel_Call {
	return &MockShoppingRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, shoppingID)}
}

func (_c *MockShoppingRepository_Cancel_Call) Run(run func(ctx context.Context, shoppingID string)) *MockShoppingRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockShoppingRepository_Cancel_Call) Return(err error) *MockShoppingRepository_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShoppingRepository_Cancel_Call) RunAndReturn(run func(ctx context.Context, shoppingID string) error) *MockShoppingRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockShoppingRepository
func (_mock *MockShoppingRepository) Create(ctx context.Context, orderID string, items []Item) (string, error) {
	ret := _mock.Called(ctx, orderID, items)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []Item) (string, error)); ok {
		return returnFunc(ctx, orderID, items)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []Item) string); ok {
		r0 = returnFunc(ctx, orderID, items)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []Item) error); ok {
		r1 = returnFunc(ctx, orderID, items)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShoppingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockShoppingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - items []Item
func (_e *MockShoppingRepository_Expecter) Create(ctx interface{}, orderID interface{}, items interface{}) *MockShoppingRepository_Create_Call {
	return &MockShoppingRepository_Create_Call{Call: _e.mock.On("Create", ctx, orderID, items)}
}

func (_c *MockShoppingRepository_Create_Call) Run(run func(ctx context.Context, orderID string, items []Item)) *MockShoppingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []Item
		if args[2] != nil {
			arg2 = args[2].([]Item)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockShoppingRepository_Create_Call) Return(s string, err error) *MockShoppingRepository_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockShoppingRepository_Create_Call) RunAndReturn(run func(ctx context.Context, orderID string, items []Item) (string, error)) *MockShoppingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}
